// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'dart:ui' show ImageFilter;

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';
import '../button/button_style.dart';

/// The look of a `DsToast`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsToastStyle with Diagnosticable {
  /// Creates a style.
  const DsToastStyle({
    this.background,
    this.backdropFilter,
    this.shadows,
    this.borderRadius,
    this.padding,
    this.maxWidth,
    this.gap,
    this.iconSize,
    this.closeIconSize,
    this.titleStyle,
    this.descriptionStyle,
    this.textGap,
    this.actionStyle,
    this.closeStyle,
  });

  /// Fill.
  final Color? background;

  /// Filter for what shows through a translucent fill, e.g. `ImageFilter.blur` for a frosted layer; null filters nothing. Opaque by default.
  final ImageFilter? backdropFilter;

  /// Floating edge and shadow.
  final List<DsShadow>? shadows;

  /// Corners.
  final BorderRadiusGeometry? borderRadius;

  /// Inner padding.
  final EdgeInsetsGeometry? padding;

  /// Largest width.
  final double? maxWidth;

  /// Space between parts.
  final double? gap;

  /// Status icon size.
  final double? iconSize;

  /// Dismiss button icon size. A `closeStyle` that sets its own `iconSize` wins.
  final double? closeIconSize;

  /// Title style, merged.
  final TextStyle? titleStyle;

  /// Description style, merged.
  final TextStyle? descriptionStyle;

  /// Space between title and description.
  final double? textGap;

  /// The action button, laid over a ghost small button.
  final DsButtonStyle? actionStyle;

  /// The dismiss button, laid over a ghost small icon button.
  final DsButtonStyle? closeStyle;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsToastStyle merge(DsToastStyle? other) {
    if (other == null) return this;
    return DsToastStyle(
      background: other.background ?? background,
      backdropFilter: other.backdropFilter ?? backdropFilter,
      shadows: other.shadows ?? shadows,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      maxWidth: other.maxWidth ?? maxWidth,
      gap: other.gap ?? gap,
      iconSize: other.iconSize ?? iconSize,
      closeIconSize: other.closeIconSize ?? closeIconSize,
      titleStyle: titleStyle?.merge(other.titleStyle) ?? other.titleStyle,
      descriptionStyle:
          descriptionStyle?.merge(other.descriptionStyle) ??
          other.descriptionStyle,
      textGap: other.textGap ?? textGap,
      actionStyle: actionStyle?.merge(other.actionStyle) ?? other.actionStyle,
      closeStyle: closeStyle?.merge(other.closeStyle) ?? other.closeStyle,
    );
  }

  /// This style; it has no state styles.
  DsToastStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsToastStyle resolveLayers(
    Iterable<DsToastStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsToastStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    background,
    backdropFilter,
    shadows,
    borderRadius,
    padding,
    maxWidth,
    gap,
    iconSize,
    closeIconSize,
    titleStyle,
    descriptionStyle,
    textGap,
    actionStyle,
    closeStyle,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsToastStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(
      DiagnosticsProperty('backdropFilter', backdropFilter, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('shadows', shadows, defaultValue: null));
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(DoubleProperty('maxWidth', maxWidth, defaultValue: null));
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(
      DoubleProperty('closeIconSize', closeIconSize, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('titleStyle', titleStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty(
        'descriptionStyle',
        descriptionStyle,
        defaultValue: null,
      ),
    );
    properties.add(DoubleProperty('textGap', textGap, defaultValue: null));
    properties.add(
      DiagnosticsProperty('actionStyle', actionStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('closeStyle', closeStyle, defaultValue: null),
    );
  }
}

/// Defaults for every `DsToast` in a subtree; see [DsToastTheme].
class DsToastThemeData extends DsComponentThemeData<DsToastThemeData> {
  /// Creates defaults.
  const DsToastThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsToastStyle? style;

  @override
  DsToastThemeData merge(DsToastThemeData? other) {
    if (other == null) return this;
    return DsToastThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsToastThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsToastThemeData] to a subtree, merged over any outer one.
class DsToastTheme extends DsComponentTheme<DsToastThemeData> {
  /// Applies [data] to [child].
  const DsToastTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsToastThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsToastThemeData>(context) ??
      const DsToastThemeData();
}
