// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../theme/status.dart';

/// The look of a `DsBadge`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsBadgeStyle with Diagnosticable {
  /// Creates a style.
  const DsBadgeStyle({
    this.height,
    this.padding,
    this.background,
    this.foreground,
    this.dotColor,
    this.borderColor,
    this.borderRadius,
    this.textStyle,
    this.dotSize,
    this.iconSize,
    this.gap,
  });

  /// Minimum height; grows with large text.
  final double? height;

  /// Inner padding.
  final EdgeInsetsGeometry? padding;

  /// Fill.
  final Color? background;

  /// Text color, and the dot's when [dotColor] is null.
  final Color? foreground;

  /// Leading dot color.
  final Color? dotColor;

  /// Inner 1px outline; none by default.
  final Color? borderColor;

  /// Corners.
  final BorderRadiusGeometry? borderRadius;

  /// Text style, merged.
  final TextStyle? textStyle;

  /// Leading dot diameter.
  final double? dotSize;

  /// Leading icon size.
  final double? iconSize;

  /// Space between dot and text.
  final double? gap;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsBadgeStyle merge(DsBadgeStyle? other) {
    if (other == null) return this;
    return DsBadgeStyle(
      height: other.height ?? height,
      padding: other.padding ?? padding,
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      dotColor: other.dotColor ?? dotColor,
      borderColor: other.borderColor ?? borderColor,
      borderRadius: other.borderRadius ?? borderRadius,
      textStyle: textStyle?.merge(other.textStyle) ?? other.textStyle,
      dotSize: other.dotSize ?? dotSize,
      iconSize: other.iconSize ?? iconSize,
      gap: other.gap ?? gap,
    );
  }

  /// This style; it has no state styles.
  DsBadgeStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsBadgeStyle resolveLayers(
    Iterable<DsBadgeStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsBadgeStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    height,
    padding,
    background,
    foreground,
    dotColor,
    borderColor,
    borderRadius,
    textStyle,
    dotSize,
    iconSize,
    gap,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsBadgeStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(ColorProperty('dotColor', dotColor, defaultValue: null));
    properties.add(
      ColorProperty('borderColor', borderColor, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('textStyle', textStyle, defaultValue: null),
    );
    properties.add(DoubleProperty('dotSize', dotSize, defaultValue: null));
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
  }
}

/// Defaults for every `DsBadge` in a subtree; see [DsBadgeTheme].
class DsBadgeThemeData extends DsComponentThemeData<DsBadgeThemeData> {
  /// Creates defaults.
  const DsBadgeThemeData({this.style, this.statuses = const {}});

  /// Laid over Desen's defaults for every status.
  final DsBadgeStyle? style;

  /// Laid over [style] for one DsStatus each.
  final Map<DsStatus, DsBadgeStyle> statuses;

  @override
  DsBadgeThemeData merge(DsBadgeThemeData? other) {
    if (other == null) return this;
    return DsBadgeThemeData(
      style: style?.merge(other.style) ?? other.style,
      statuses: {
        for (final k in {...statuses.keys, ...other.statuses.keys})
          k: statuses[k]?.merge(other.statuses[k]) ?? other.statuses[k]!,
      },
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsBadgeThemeData &&
      other.style == style &&
      mapEquals(other.statuses, statuses);

  @override
  int get hashCode => Object.hash(
    style,
    Object.hashAllUnordered(
      statuses.entries.map((e) => Object.hash(e.key, e.value)),
    ),
  );

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsBadgeThemeData] to a subtree, merged over any outer one.
class DsBadgeTheme extends DsComponentTheme<DsBadgeThemeData> {
  /// Applies [data] to [child].
  const DsBadgeTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsBadgeThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsBadgeThemeData>(context) ??
      const DsBadgeThemeData();
}
