// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import 'badge.dart';

/// The look of a `DsCount`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsCountStyle with Diagnosticable {
  /// Creates a style.
  const DsCountStyle({
    this.minSize,
    this.padding,
    this.background,
    this.foreground,
    this.borderColor,
    this.borderRadius,
    this.ringColor,
    this.ringWidth,
    this.textStyle,
  });

  /// Minimum width and height; the bubble grows with the number and with large text.
  final double? minSize;

  /// Inner padding.
  final EdgeInsetsGeometry? padding;

  /// Fill.
  final Color? background;

  /// Number color.
  final Color? foreground;

  /// Inner 1px outline; none by default.
  final Color? borderColor;

  /// Corners.
  final BorderRadiusGeometry? borderRadius;

  /// Ring separating the bubble from what it sits on. Set the real background when it is not the surface, or transparent to drop the ring.
  final Color? ringColor;

  /// Width of that ring.
  final double? ringWidth;

  /// Number text style, merged (tabular figures).
  final TextStyle? textStyle;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsCountStyle merge(DsCountStyle? other) {
    if (other == null) return this;
    return DsCountStyle(
      minSize: other.minSize ?? minSize,
      padding: other.padding ?? padding,
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      borderColor: other.borderColor ?? borderColor,
      borderRadius: other.borderRadius ?? borderRadius,
      ringColor: other.ringColor ?? ringColor,
      ringWidth: other.ringWidth ?? ringWidth,
      textStyle: textStyle?.merge(other.textStyle) ?? other.textStyle,
    );
  }

  /// This style; it has no state styles.
  DsCountStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsCountStyle resolveLayers(
    Iterable<DsCountStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsCountStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    minSize,
    padding,
    background,
    foreground,
    borderColor,
    borderRadius,
    ringColor,
    ringWidth,
    textStyle,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsCountStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('minSize', minSize, defaultValue: null));
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(
      ColorProperty('borderColor', borderColor, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(ColorProperty('ringColor', ringColor, defaultValue: null));
    properties.add(DoubleProperty('ringWidth', ringWidth, defaultValue: null));
    properties.add(
      DiagnosticsProperty('textStyle', textStyle, defaultValue: null),
    );
  }
}

/// Defaults for every `DsCount` in a subtree; see [DsCountTheme].
class DsCountThemeData extends DsComponentThemeData<DsCountThemeData> {
  /// Creates defaults.
  const DsCountThemeData({this.style, this.tones = const {}});

  /// Laid over Desen's defaults for every tone.
  final DsCountStyle? style;

  /// Laid over [style] for one DsCountTone each.
  final Map<DsCountTone, DsCountStyle> tones;

  @override
  DsCountThemeData merge(DsCountThemeData? other) {
    if (other == null) return this;
    return DsCountThemeData(
      style: style?.merge(other.style) ?? other.style,
      tones: {
        for (final k in {...tones.keys, ...other.tones.keys})
          k: tones[k]?.merge(other.tones[k]) ?? other.tones[k]!,
      },
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsCountThemeData &&
      other.style == style &&
      mapEquals(other.tones, tones);

  @override
  int get hashCode => Object.hash(
    style,
    Object.hashAllUnordered(
      tones.entries.map((e) => Object.hash(e.key, e.value)),
    ),
  );

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsCountThemeData] to a subtree, merged over any outer one.
class DsCountTheme extends DsComponentTheme<DsCountThemeData> {
  /// Applies [data] to [child].
  const DsCountTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsCountThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsCountThemeData>(context) ??
      const DsCountThemeData();
}
