// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'dart:ui' show ImageFilter;

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';
import 'bottom_nav.dart';

/// The look of a `DsBottomNav` container.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsBottomNavStyle with Diagnosticable {
  /// Creates a style.
  const DsBottomNavStyle({
    this.background,
    this.backdropFilter,
    this.shadows,
    this.borderRadius,
    this.padding,
    this.gap,
  });

  /// Fill.
  final Color? background;

  /// Filter for what shows through a translucent fill, e.g. `ImageFilter.blur` for a frosted layer; null filters nothing. Opaque by default.
  final ImageFilter? backdropFilter;

  /// Edge, top line or floating shadow.
  final List<DsShadow>? shadows;

  /// Corners. When no layer sets them, the floating bar is rounded as a control as tall as its items plus its padding (`DsRadii.controlCorners`), so an item height set in a style keeps the bar concentric with its items; the flat bar is square.
  final BorderRadiusGeometry? borderRadius;

  /// Inner padding.
  final EdgeInsetsGeometry? padding;

  /// Space between items.
  final double? gap;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsBottomNavStyle merge(DsBottomNavStyle? other) {
    if (other == null) return this;
    return DsBottomNavStyle(
      background: other.background ?? background,
      backdropFilter: other.backdropFilter ?? backdropFilter,
      shadows: other.shadows ?? shadows,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      gap: other.gap ?? gap,
    );
  }

  /// This style; it has no state styles.
  DsBottomNavStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsBottomNavStyle resolveLayers(
    Iterable<DsBottomNavStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsBottomNavStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    background,
    backdropFilter,
    shadows,
    borderRadius,
    padding,
    gap,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsBottomNavStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(
      DiagnosticsProperty('backdropFilter', backdropFilter, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('shadows', shadows, defaultValue: null));
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
  }
}

/// Defaults for every `DsBottomNav` in a subtree; see [DsBottomNavTheme].
class DsBottomNavThemeData extends DsComponentThemeData<DsBottomNavThemeData> {
  /// Creates defaults.
  const DsBottomNavThemeData({
    this.variant,
    this.style,
    this.variants = const {},
  });

  /// Variant for bottom navs that do not set one; `DsBottomNavVariant.floating` when null.
  final DsBottomNavVariant? variant;

  /// Laid over Desen's defaults for every variant.
  final DsBottomNavStyle? style;

  /// Laid over [style] for one DsBottomNavVariant each.
  final Map<DsBottomNavVariant, DsBottomNavStyle> variants;

  @override
  DsBottomNavThemeData merge(DsBottomNavThemeData? other) {
    if (other == null) return this;
    return DsBottomNavThemeData(
      variant: other.variant ?? variant,
      style: style?.merge(other.style) ?? other.style,
      variants: {
        for (final k in {...variants.keys, ...other.variants.keys})
          k: variants[k]?.merge(other.variants[k]) ?? other.variants[k]!,
      },
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsBottomNavThemeData &&
      other.variant == variant &&
      other.style == style &&
      mapEquals(other.variants, variants);

  @override
  int get hashCode => Object.hash(
    variant,
    style,
    Object.hashAllUnordered(
      variants.entries.map((e) => Object.hash(e.key, e.value)),
    ),
  );

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(EnumProperty('variant', variant, defaultValue: null));
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsBottomNavThemeData] to a subtree, merged over any outer one.
class DsBottomNavTheme extends DsComponentTheme<DsBottomNavThemeData> {
  /// Applies [data] to [child].
  const DsBottomNavTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsBottomNavThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsBottomNavThemeData>(context) ??
      const DsBottomNavThemeData();
}
