// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';
import 'bottom_nav.dart';

/// The look of a `DsBottomNav` item.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsBottomNavItemStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsBottomNavItemStyle with Diagnosticable {
  /// Creates a style.
  const DsBottomNavItemStyle({
    this.width,
    this.height,
    this.borderRadius,
    this.background,
    this.borderColor,
    this.foreground,
    this.iconSize,
    this.labelStyle,
    this.capsuleSize,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
    this.disabled,
  });

  /// Item width (floating bar); the full-width bar shares space.
  final double? width;

  /// Item height.
  final double? height;

  /// Corners of the selected fill. When no layer sets them, concentric with the floating bar (`DsRadii.nestedCorners` by its padding), and on the flat bar rounded as a control of `height` (`DsRadii.controlCorners`).
  final BorderRadiusGeometry? borderRadius;

  /// Selected fill: the whole item, or the capsule when `capsuleSize` is set.
  final Color? background;

  /// Inner 1px outline of the selected fill, e.g. the edge a bright filled selection needs.
  final Color? borderColor;

  /// Icon and label color.
  final Color? foreground;

  /// Icon size.
  final double? iconSize;

  /// Label style, merged.
  final TextStyle? labelStyle;

  /// Size of a capsule behind the icon that takes the selected fill instead of the whole item; null (the default) fills the item.
  final Size? capsuleSize;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsBottomNavItemStyle? focused;

  /// Laid over the base while hovered.
  final DsBottomNavItemStyle? hovered;

  /// Laid over the base while pressed.
  final DsBottomNavItemStyle? pressed;

  /// Laid over the base while selected.
  final DsBottomNavItemStyle? selected;

  /// Laid over the base while disabled.
  final DsBottomNavItemStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsBottomNavItemStyle merge(DsBottomNavItemStyle? other) {
    if (other == null) return this;
    return DsBottomNavItemStyle(
      width: other.width ?? width,
      height: other.height ?? height,
      borderRadius: other.borderRadius ?? borderRadius,
      background: other.background ?? background,
      borderColor: other.borderColor ?? borderColor,
      foreground: other.foreground ?? foreground,
      iconSize: other.iconSize ?? iconSize,
      labelStyle: labelStyle?.merge(other.labelStyle) ?? other.labelStyle,
      capsuleSize: other.capsuleSize ?? capsuleSize,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsBottomNavItemStyle get _base => DsBottomNavItemStyle(
    width: width,
    height: height,
    borderRadius: borderRadius,
    background: background,
    borderColor: borderColor,
    foreground: foreground,
    iconSize: iconSize,
    labelStyle: labelStyle,
    capsuleSize: capsuleSize,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsBottomNavItemStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsBottomNavItemStyle resolveLayers(
    Iterable<DsBottomNavItemStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsBottomNavItemStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    width,
    height,
    borderRadius,
    background,
    borderColor,
    foreground,
    iconSize,
    labelStyle,
    capsuleSize,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsBottomNavItemStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('width', width, defaultValue: null));
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(
      ColorProperty('borderColor', borderColor, defaultValue: null),
    );
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(
      DiagnosticsProperty('labelStyle', labelStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('capsuleSize', capsuleSize, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsBottomNavItem` in a subtree; see [DsBottomNavItemTheme].
class DsBottomNavItemThemeData
    extends DsComponentThemeData<DsBottomNavItemThemeData> {
  /// Creates defaults.
  const DsBottomNavItemThemeData({this.style, this.variants = const {}});

  /// Laid over Desen's defaults for every variant.
  final DsBottomNavItemStyle? style;

  /// Laid over [style] for one DsBottomNavVariant each.
  final Map<DsBottomNavVariant, DsBottomNavItemStyle> variants;

  @override
  DsBottomNavItemThemeData merge(DsBottomNavItemThemeData? other) {
    if (other == null) return this;
    return DsBottomNavItemThemeData(
      style: style?.merge(other.style) ?? other.style,
      variants: {
        for (final k in {...variants.keys, ...other.variants.keys})
          k: variants[k]?.merge(other.variants[k]) ?? other.variants[k]!,
      },
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsBottomNavItemThemeData &&
      other.style == style &&
      mapEquals(other.variants, variants);

  @override
  int get hashCode => Object.hash(
    style,
    Object.hashAllUnordered(
      variants.entries.map((e) => Object.hash(e.key, e.value)),
    ),
  );

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsBottomNavItemThemeData] to a subtree, merged over any outer one.
class DsBottomNavItemTheme extends DsComponentTheme<DsBottomNavItemThemeData> {
  /// Applies [data] to [child].
  const DsBottomNavItemTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsBottomNavItemThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsBottomNavItemThemeData>(context) ??
      const DsBottomNavItemThemeData();
}
