// GENERATED by tool/gen_icons.py. Do not edit by hand.
// Shapes from Lucide (https://lucide.dev), ISC license.

import 'icon.dart';

/// The built-in icon set: Lucide-style 24×24 stroke icons.
///
/// Desen uses these internally (chevrons, checks, alerts). Components take
/// icons as widgets, so any icon set works in your own UI.
abstract final class DsIcons {
  /// Plus.
  static const plus = DsIconData(['M5 12h14', 'M12 5v14']);

  /// Minus.
  static const minus = DsIconData(['M5 12h14']);

  /// Check mark.
  static const check = DsIconData(['M20 6 9 17l-5-5']);

  /// Close / clear.
  static const x = DsIconData(['M18 6 6 18', 'm6 6 12 12']);

  /// Chevron pointing down.
  static const chevronDown = DsIconData(['m6 9 6 6 6-6']);

  /// Chevron pointing up.
  static const chevronUp = DsIconData(['m18 15-6-6-6 6']);

  /// Chevron pointing left.
  static const chevronLeft = DsIconData([
    'm15 18-6-6 6-6',
  ], matchTextDirection: true);

  /// Chevron pointing right.
  static const chevronRight = DsIconData([
    'm9 18 6-6-6-6',
  ], matchTextDirection: true);

  /// Horizontal ellipsis (more).
  static const ellipsis = DsIconData([
    'M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
    'M18 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
    'M4 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
  ]);

  /// Magnifier.
  static const search = DsIconData([
    'M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0',
    'm21 21-4.3-4.3',
  ]);

  /// Error.
  static const circleAlert = DsIconData([
    'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
    'M12 8L12 12',
    'M12 16L12.01 16',
  ]);

  /// Success.
  static const circleCheck = DsIconData([
    'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
    'm9 12 2 2 4-4',
  ]);

  /// Information.
  static const info = DsIconData([
    'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
    'M12 16v-4',
    'M12 8h.01',
  ]);

  /// Warning.
  static const triangleAlert = DsIconData([
    'm21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3',
    'M12 9v4',
    'M12 17h.01',
  ]);

  /// Envelope.
  static const mail = DsIconData([
    'M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2z',
    'm22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7',
  ]);

  /// Calendar.
  static const calendar = DsIconData([
    'M8 2v4',
    'M16 2v4',
    'M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
    'M3 10h18',
  ]);

  /// Grid layout.
  static const layoutGrid = DsIconData([
    'M4 3h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z',
    'M15 3h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z',
    'M15 14h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z',
    'M4 14h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z',
  ]);

  /// List layout.
  static const list = DsIconData([
    'M3 12h.01',
    'M3 18h.01',
    'M3 6h.01',
    'M8 12h13',
    'M8 18h13',
    'M8 6h13',
  ]);

  /// Bold text.
  static const bold = DsIconData([
    'M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8',
  ]);

  /// Italic text.
  static const italic = DsIconData(['M19 4L10 4', 'M14 20L5 20', 'M15 4L9 20']);

  /// Underlined text.
  static const underline = DsIconData([
    'M6 4v6a6 6 0 0 0 12 0V4',
    'M4 20L20 20',
  ]);

  /// Notifications.
  static const bell = DsIconData([
    'M10.268 21a2 2 0 0 0 3.464 0',
    'M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326',
  ]);

  /// Inbox.
  static const inbox = DsIconData([
    'M22 12h-6l-2 3h-4l-2-3H2',
    'M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z',
  ]);

  /// Person.
  static const user = DsIconData([
    'M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2',
    'M8 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0',
  ]);

  /// External link.
  static const arrowUpRight = DsIconData(['M7 7h10v10', 'M7 17 17 7']);

  /// Volume, low.
  static const volumeLow = DsIconData([
    'M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z',
    'M16 9a5 5 0 0 1 0 6',
  ]);

  /// Volume, high.
  static const volumeHigh = DsIconData([
    'M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z',
    'M16 9a5 5 0 0 1 0 6',
    'M19.364 18.364a9 9 0 0 0 0-12.728',
  ]);

  /// Two chevrons: a switcher or sort.
  static const chevronsUpDown = DsIconData(['m7 15 5 5 5-5', 'm7 9 5-5 5 5']);

  /// Light appearance.
  static const sun = DsIconData([
    'M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0',
    'M12 2v2',
    'M12 20v2',
    'm4.93 4.93 1.41 1.41',
    'm17.66 17.66 1.41 1.41',
    'M2 12h2',
    'M20 12h2',
    'm6.34 17.66-1.41 1.41',
    'm19.07 4.93-1.41 1.41',
  ]);

  /// Dark appearance.
  static const moon = DsIconData(['M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z']);

  /// Menu (navigation).
  static const menu = DsIconData(['M4 12h16', 'M4 6h16', 'M4 18h16']);

  /// Folder.
  static const folder = DsIconData([
    'M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z',
  ]);

  /// Home.
  static const house = DsIconData([
    'M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8',
    'M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z',
  ]);

  /// Language or web.
  static const globe = DsIconData([
    'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
    'M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20',
    'M2 12h20',
  ]);

  /// Sign out.
  static const logOut = DsIconData([
    'm16 17 5-5-5-5',
    'M21 12H9',
    'M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4',
  ], matchTextDirection: true);

  /// Share.
  static const share = DsIconData([
    'M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8',
    'm16 6-4-4-4 4',
    'M12 2L12 15',
  ]);

  /// Link.
  static const link = DsIconData([
    'M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71',
    'M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71',
  ]);

  /// Copy.
  static const copy = DsIconData([
    'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
    'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
  ]);

  /// Delete.
  static const trash = DsIconData([
    'M3 6h18',
    'M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6',
    'M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2',
    'M10 11L10 17',
    'M14 11L14 17',
  ]);

  /// Filters.
  static const slidersHorizontal = DsIconData([
    'M21 4L14 4',
    'M10 4L3 4',
    'M21 12L12 12',
    'M8 12L3 12',
    'M21 20L16 20',
    'M12 20L3 20',
    'M14 2L14 6',
    'M8 10L8 14',
    'M16 18L16 22',
  ]);

  /// Visible: shows hidden text, e.g. a password.
  static const eye = DsIconData([
    'M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0',
    'M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  ]);

  /// Hidden: hides revealed text again.
  static const eyeOff = DsIconData([
    'M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49',
    'M14.084 14.158a3 3 0 0 1-4.242-4.242',
    'M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143',
    'm2 2 20 20',
  ]);

  /// Command key (⌘).
  static const command = DsIconData([
    'M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3',
  ]);

  /// Option key (⌥).
  static const option = DsIconData(['M3 3h6l6 18h6', 'M14 3h7']);

  /// Shift key (⇧).
  static const shift = DsIconData(['M9 18v-6H5l7-7 7 7h-4v6H9z']);

  /// Backspace / delete key (⌫).
  static const backspace = DsIconData([
    'M10 5a2 2 0 0 0-1.344.519l-6.328 5.74a1 1 0 0 0 0 1.481l6.328 5.741A2 2 0 0 0 10 19h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2z',
    'm12 9 6 6',
    'm18 9-6 6',
  ]);

  /// Return key (⏎).
  static const enter = DsIconData(['M20 4v7a4 4 0 0 1-4 4H4', 'm9 10-5 5 5 5']);

  /// Upload (tray with an arrow up).
  static const upload = DsIconData([
    'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4',
    'M17 8l-5-5-5 5',
    'M12 3v12',
  ]);

  /// File with text lines.
  static const fileText = DsIconData([
    'M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z',
    'M14 2v4a2 2 0 0 0 2 2h4',
    'M10 9H8',
    'M16 13H8',
    'M16 17H8',
  ]);

  /// Clock.
  static const clock = DsIconData([
    'M12 6v6l4 2',
    'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0z',
  ]);

  /// Arrow up, e.g. ascending sort.
  static const arrowUp = DsIconData(['m5 12 7-7 7 7', 'M12 19V5']);

  /// Arrow down, e.g. descending sort.
  static const arrowDown = DsIconData(['M12 5v14', 'm19 12-7 7-7-7']);

  /// Magnifier with a cross: nothing found.
  static const searchX = DsIconData([
    'm13.5 8.5-5 5',
    'm8.5 8.5 5 5',
    'M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0',
    'm21 21-4.3-4.3',
  ]);

  /// Crossed-out picture: an image that cannot be shown.
  static const imageOff = DsIconData([
    'M2 2L22 22',
    'M10.41 10.41a2 2 0 1 1-2.83-2.83',
    'M13.5 13.5L6 21',
    'M18 12L21 15',
    'M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59',
    'M21 15V5a2 2 0 0 0-2-2H9',
  ]);

  /// Settings (gear).
  static const settings = DsIconData([
    'M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z',
    'M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  ]);

  /// Every icon above by its name, in this order (e.g. for an icon
  /// picker or a search).
  static const all = <String, DsIconData>{
    'plus': plus,
    'minus': minus,
    'check': check,
    'x': x,
    'chevronDown': chevronDown,
    'chevronUp': chevronUp,
    'chevronLeft': chevronLeft,
    'chevronRight': chevronRight,
    'ellipsis': ellipsis,
    'search': search,
    'circleAlert': circleAlert,
    'circleCheck': circleCheck,
    'info': info,
    'triangleAlert': triangleAlert,
    'mail': mail,
    'calendar': calendar,
    'layoutGrid': layoutGrid,
    'list': list,
    'bold': bold,
    'italic': italic,
    'underline': underline,
    'bell': bell,
    'inbox': inbox,
    'user': user,
    'arrowUpRight': arrowUpRight,
    'volumeLow': volumeLow,
    'volumeHigh': volumeHigh,
    'chevronsUpDown': chevronsUpDown,
    'sun': sun,
    'moon': moon,
    'menu': menu,
    'folder': folder,
    'house': house,
    'globe': globe,
    'logOut': logOut,
    'share': share,
    'link': link,
    'copy': copy,
    'trash': trash,
    'slidersHorizontal': slidersHorizontal,
    'eye': eye,
    'eyeOff': eyeOff,
    'command': command,
    'option': option,
    'shift': shift,
    'backspace': backspace,
    'enter': enter,
    'upload': upload,
    'fileText': fileText,
    'clock': clock,
    'arrowUp': arrowUp,
    'arrowDown': arrowDown,
    'searchX': searchX,
    'imageOff': imageOff,
    'settings': settings,
  };
}
