// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';

/// The look of a `DsSkeleton`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsSkeletonStyle with Diagnosticable {
  /// Creates a style.
  const DsSkeletonStyle({
    this.height,
    this.color,
    this.strongColor,
    this.borderRadius,
  });

  /// Height of a skeleton that does not set its own.
  final double? height;

  /// Fill.
  final Color? color;

  /// Fill of a `strong` skeleton, e.g. a title line.
  final Color? strongColor;

  /// Corners. When no layer sets them, a line is fully rounded and a block takes the radius of media inside a card (`DsRadii.nested` of the card radius and its padding).
  final BorderRadiusGeometry? borderRadius;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsSkeletonStyle merge(DsSkeletonStyle? other) {
    if (other == null) return this;
    return DsSkeletonStyle(
      height: other.height ?? height,
      color: other.color ?? color,
      strongColor: other.strongColor ?? strongColor,
      borderRadius: other.borderRadius ?? borderRadius,
    );
  }

  /// This style; it has no state styles.
  DsSkeletonStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsSkeletonStyle resolveLayers(
    Iterable<DsSkeletonStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsSkeletonStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [height, color, strongColor, borderRadius];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsSkeletonStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(ColorProperty('color', color, defaultValue: null));
    properties.add(
      ColorProperty('strongColor', strongColor, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
  }
}

/// Defaults for every `DsSkeleton` in a subtree; see [DsSkeletonTheme].
class DsSkeletonThemeData extends DsComponentThemeData<DsSkeletonThemeData> {
  /// Creates defaults.
  const DsSkeletonThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsSkeletonStyle? style;

  @override
  DsSkeletonThemeData merge(DsSkeletonThemeData? other) {
    if (other == null) return this;
    return DsSkeletonThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsSkeletonThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsSkeletonThemeData] to a subtree, merged over any outer one.
class DsSkeletonTheme extends DsComponentTheme<DsSkeletonThemeData> {
  /// Applies [data] to [child].
  const DsSkeletonTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsSkeletonThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsSkeletonThemeData>(context) ??
      const DsSkeletonThemeData();
}
