// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../theme/sizes.dart';

/// The look of a `DsAvatar`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsAvatarStyle with Diagnosticable {
  /// Creates a style.
  const DsAvatarStyle({
    this.diameter,
    this.background,
    this.foreground,
    this.textStyle,
    this.iconSize,
    this.statusSize,
    this.ringColor,
    this.ringWidth,
  });

  /// Circle diameter.
  final double? diameter;

  /// Fill behind initials or the icon. When no layer sets it, the tone picks it (`DsAvatar.toneIndex`).
  final Color? background;

  /// Initials and icon color. When no layer sets it, the tone picks it.
  final Color? foreground;

  /// Initials text style, merged.
  final TextStyle? textStyle;

  /// Person icon size.
  final double? iconSize;

  /// Status dot diameter.
  final double? statusSize;

  /// Ring around the status dot. Set the real background when it is not the surface.
  final Color? ringColor;

  /// Width of that ring.
  final double? ringWidth;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsAvatarStyle merge(DsAvatarStyle? other) {
    if (other == null) return this;
    return DsAvatarStyle(
      diameter: other.diameter ?? diameter,
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      textStyle: textStyle?.merge(other.textStyle) ?? other.textStyle,
      iconSize: other.iconSize ?? iconSize,
      statusSize: other.statusSize ?? statusSize,
      ringColor: other.ringColor ?? ringColor,
      ringWidth: other.ringWidth ?? ringWidth,
    );
  }

  /// This style; it has no state styles.
  DsAvatarStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsAvatarStyle resolveLayers(
    Iterable<DsAvatarStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsAvatarStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    diameter,
    background,
    foreground,
    textStyle,
    iconSize,
    statusSize,
    ringColor,
    ringWidth,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsAvatarStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('diameter', diameter, defaultValue: null));
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(
      DiagnosticsProperty('textStyle', textStyle, defaultValue: null),
    );
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(
      DoubleProperty('statusSize', statusSize, defaultValue: null),
    );
    properties.add(ColorProperty('ringColor', ringColor, defaultValue: null));
    properties.add(DoubleProperty('ringWidth', ringWidth, defaultValue: null));
  }
}

/// Defaults for every `DsAvatar` in a subtree; see [DsAvatarTheme].
class DsAvatarThemeData extends DsComponentThemeData<DsAvatarThemeData> {
  /// Creates defaults.
  const DsAvatarThemeData({this.size, this.style, this.sizes = const {}});

  /// Size for avatars that do not set one; `DsSize.md` when null.
  final DsSize? size;

  /// Laid over Desen's defaults for every size.
  final DsAvatarStyle? style;

  /// Laid over [style] for one DsSize each.
  final Map<DsSize, DsAvatarStyle> sizes;

  @override
  DsAvatarThemeData merge(DsAvatarThemeData? other) {
    if (other == null) return this;
    return DsAvatarThemeData(
      size: other.size ?? size,
      style: style?.merge(other.style) ?? other.style,
      sizes: {
        for (final k in {...sizes.keys, ...other.sizes.keys})
          k: sizes[k]?.merge(other.sizes[k]) ?? other.sizes[k]!,
      },
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsAvatarThemeData &&
      other.size == size &&
      other.style == style &&
      mapEquals(other.sizes, sizes);

  @override
  int get hashCode => Object.hash(
    size,
    style,
    Object.hashAllUnordered(
      sizes.entries.map((e) => Object.hash(e.key, e.value)),
    ),
  );

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(EnumProperty('size', size, defaultValue: null));
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsAvatarThemeData] to a subtree, merged over any outer one.
class DsAvatarTheme extends DsComponentTheme<DsAvatarThemeData> {
  /// Applies [data] to [child].
  const DsAvatarTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsAvatarThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsAvatarThemeData>(context) ??
      const DsAvatarThemeData();
}
