// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../theme/sizes.dart';

/// The look of a `DsAvatarGroup`. The avatars themselves follow `DsAvatarStyle`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsAvatarGroupStyle with Diagnosticable {
  /// Creates a style.
  const DsAvatarGroupStyle({
    this.ringColor,
    this.ringWidth,
    this.overlap,
    this.overflowSurface,
    this.overflowBackground,
    this.overflowForeground,
    this.overflowTextStyle,
  });

  /// Ring that separates overlapping avatars, also used around their status dots. Set the real background when it is not the surface.
  final Color? ringColor;

  /// Width of that ring.
  final double? ringWidth;

  /// How much of each avatar the next one covers, as a fraction of the diameter.
  final double? overlap;

  /// Opaque fill under the `+N` bubble, so its tint does not show what lies beneath.
  final Color? overflowSurface;

  /// `+N` bubble fill.
  final Color? overflowBackground;

  /// `+N` text color.
  final Color? overflowForeground;

  /// `+N` text style, merged (tabular figures).
  final TextStyle? overflowTextStyle;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsAvatarGroupStyle merge(DsAvatarGroupStyle? other) {
    if (other == null) return this;
    return DsAvatarGroupStyle(
      ringColor: other.ringColor ?? ringColor,
      ringWidth: other.ringWidth ?? ringWidth,
      overlap: other.overlap ?? overlap,
      overflowSurface: other.overflowSurface ?? overflowSurface,
      overflowBackground: other.overflowBackground ?? overflowBackground,
      overflowForeground: other.overflowForeground ?? overflowForeground,
      overflowTextStyle:
          overflowTextStyle?.merge(other.overflowTextStyle) ??
          other.overflowTextStyle,
    );
  }

  /// This style; it has no state styles.
  DsAvatarGroupStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsAvatarGroupStyle resolveLayers(
    Iterable<DsAvatarGroupStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsAvatarGroupStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    ringColor,
    ringWidth,
    overlap,
    overflowSurface,
    overflowBackground,
    overflowForeground,
    overflowTextStyle,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsAvatarGroupStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(ColorProperty('ringColor', ringColor, defaultValue: null));
    properties.add(DoubleProperty('ringWidth', ringWidth, defaultValue: null));
    properties.add(DoubleProperty('overlap', overlap, defaultValue: null));
    properties.add(
      ColorProperty('overflowSurface', overflowSurface, defaultValue: null),
    );
    properties.add(
      ColorProperty(
        'overflowBackground',
        overflowBackground,
        defaultValue: null,
      ),
    );
    properties.add(
      ColorProperty(
        'overflowForeground',
        overflowForeground,
        defaultValue: null,
      ),
    );
    properties.add(
      DiagnosticsProperty(
        'overflowTextStyle',
        overflowTextStyle,
        defaultValue: null,
      ),
    );
  }
}

/// Defaults for every `DsAvatarGroup` in a subtree; see [DsAvatarGroupTheme].
class DsAvatarGroupThemeData
    extends DsComponentThemeData<DsAvatarGroupThemeData> {
  /// Creates defaults.
  const DsAvatarGroupThemeData({this.size, this.style});

  /// Size for groups that do not set one; `DsSize.sm` when null.
  final DsSize? size;

  /// Laid over Desen's defaults.
  final DsAvatarGroupStyle? style;

  @override
  DsAvatarGroupThemeData merge(DsAvatarGroupThemeData? other) {
    if (other == null) return this;
    return DsAvatarGroupThemeData(
      size: other.size ?? size,
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsAvatarGroupThemeData &&
      other.size == size &&
      other.style == style;

  @override
  int get hashCode => Object.hash(size, style);

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(EnumProperty('size', size, defaultValue: null));
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsAvatarGroupThemeData] to a subtree, merged over any outer one.
class DsAvatarGroupTheme extends DsComponentTheme<DsAvatarGroupThemeData> {
  /// Applies [data] to [child].
  const DsAvatarGroupTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsAvatarGroupThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsAvatarGroupThemeData>(context) ??
      const DsAvatarGroupThemeData();
}
