// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';

/// The look of a `DsScrollbar`. Hovered is the pointer over the thumb, pressed a drag of the thumb.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsScrollbarStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsScrollbarStyle with Diagnosticable {
  /// Creates a style.
  const DsScrollbarStyle({
    this.thumbColor,
    this.thickness,
    this.crossAxisMargin,
    this.mainAxisMargin,
    this.minThumbLength,
    this.hovered,
    this.pressed,
  });

  /// Thumb fill.
  final Color? thumbColor;

  /// Thumb width across the scroll direction. The thumb is fully rounded.
  final double? thickness;

  /// Space between the thumb and the edge it runs along.
  final double? crossAxisMargin;

  /// Space before the start and after the end of the thumb's run.
  final double? mainAxisMargin;

  /// Shortest the thumb gets on long content.
  final double? minThumbLength;

  /// Laid over the base while hovered.
  final DsScrollbarStyle? hovered;

  /// Laid over the base while pressed.
  final DsScrollbarStyle? pressed;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsScrollbarStyle merge(DsScrollbarStyle? other) {
    if (other == null) return this;
    return DsScrollbarStyle(
      thumbColor: other.thumbColor ?? thumbColor,
      thickness: other.thickness ?? thickness,
      crossAxisMargin: other.crossAxisMargin ?? crossAxisMargin,
      mainAxisMargin: other.mainAxisMargin ?? mainAxisMargin,
      minThumbLength: other.minThumbLength ?? minThumbLength,
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
    );
  }

  DsScrollbarStyle get _base => DsScrollbarStyle(
    thumbColor: thumbColor,
    thickness: thickness,
    crossAxisMargin: crossAxisMargin,
    mainAxisMargin: mainAxisMargin,
    minThumbLength: minThumbLength,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsScrollbarStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsScrollbarStyle resolveLayers(
    Iterable<DsScrollbarStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsScrollbarStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    thumbColor,
    thickness,
    crossAxisMargin,
    mainAxisMargin,
    minThumbLength,
    hovered,
    pressed,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsScrollbarStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(ColorProperty('thumbColor', thumbColor, defaultValue: null));
    properties.add(DoubleProperty('thickness', thickness, defaultValue: null));
    properties.add(
      DoubleProperty('crossAxisMargin', crossAxisMargin, defaultValue: null),
    );
    properties.add(
      DoubleProperty('mainAxisMargin', mainAxisMargin, defaultValue: null),
    );
    properties.add(
      DoubleProperty('minThumbLength', minThumbLength, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
  }
}

/// Defaults for every `DsScrollbar` in a subtree; see [DsScrollbarTheme].
class DsScrollbarThemeData extends DsComponentThemeData<DsScrollbarThemeData> {
  /// Creates defaults.
  const DsScrollbarThemeData({this.alwaysVisible, this.style});

  /// Whether thumbs of scrollbars that do not set it stay visible while the content is at rest; `false` (shown while scrolling) when null.
  final bool? alwaysVisible;

  /// Laid over Desen's defaults.
  final DsScrollbarStyle? style;

  @override
  DsScrollbarThemeData merge(DsScrollbarThemeData? other) {
    if (other == null) return this;
    return DsScrollbarThemeData(
      alwaysVisible: other.alwaysVisible ?? alwaysVisible,
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsScrollbarThemeData &&
      other.alwaysVisible == alwaysVisible &&
      other.style == style;

  @override
  int get hashCode => Object.hash(alwaysVisible, style);

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(
      FlagProperty(
        'alwaysVisible',
        value: alwaysVisible,
        ifTrue: 'alwaysVisible',
        ifFalse: 'not alwaysVisible',
      ),
    );
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsScrollbarThemeData] to a subtree, merged over any outer one.
class DsScrollbarTheme extends DsComponentTheme<DsScrollbarThemeData> {
  /// Applies [data] to [child].
  const DsScrollbarTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsScrollbarThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsScrollbarThemeData>(context) ??
      const DsScrollbarThemeData();
}
