// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';
import '../button/button_style.dart';
import '../popover/popover_style.dart';
import '../text_field/text_field_style.dart';

/// The look of a `DsTimePicker`: the field, its clock button and the popup columns. States resolve per column item; `focused` is the keyboard-focused column's chosen item. Field, button and panel styles lay over their themes; column fields are read unresolved.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsTimePickerStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsTimePickerStyle with Diagnosticable {
  /// Creates a style.
  const DsTimePickerStyle({
    this.fieldStyle,
    this.buttonStyle,
    this.panelStyle,
    this.columnWidth,
    this.columnGap,
    this.dividerColor,
    this.visibleItems,
    this.itemHeight,
    this.itemGap,
    this.itemRadius,
    this.itemBackground,
    this.itemForeground,
    this.itemBorderColor,
    this.itemTextStyle,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
  });

  /// The text field, laid over its own defaults and theme: a default width.
  final DsTextFieldStyle? fieldStyle;

  /// The clock button, laid over a ghost extra-small icon button.
  final DsButtonStyle? buttonStyle;

  /// The popup panel, laid over the popover theme.
  final DsPopoverStyle? panelStyle;

  /// Width of a column.
  final double? columnWidth;

  /// Space between columns; the divider sits in it.
  final double? columnGap;

  /// Line between columns.
  final Color? dividerColor;

  /// How many items a column shows before it scrolls.
  final double? visibleItems;

  /// Minimum item height; grows with large text.
  final double? itemHeight;

  /// Space between items.
  final double? itemGap;

  /// Item corners.
  final BorderRadiusGeometry? itemRadius;

  /// Item fill.
  final Color? itemBackground;

  /// Item text color.
  final Color? itemForeground;

  /// Inner 1px item outline, e.g. the edge a bright filled selection needs.
  final Color? itemBorderColor;

  /// Item text style, merged (tabular digits).
  final TextStyle? itemTextStyle;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsTimePickerStyle? focused;

  /// Laid over the base while hovered.
  final DsTimePickerStyle? hovered;

  /// Laid over the base while pressed.
  final DsTimePickerStyle? pressed;

  /// Laid over the base while selected.
  final DsTimePickerStyle? selected;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsTimePickerStyle merge(DsTimePickerStyle? other) {
    if (other == null) return this;
    return DsTimePickerStyle(
      fieldStyle: fieldStyle?.merge(other.fieldStyle) ?? other.fieldStyle,
      buttonStyle: buttonStyle?.merge(other.buttonStyle) ?? other.buttonStyle,
      panelStyle: panelStyle?.merge(other.panelStyle) ?? other.panelStyle,
      columnWidth: other.columnWidth ?? columnWidth,
      columnGap: other.columnGap ?? columnGap,
      dividerColor: other.dividerColor ?? dividerColor,
      visibleItems: other.visibleItems ?? visibleItems,
      itemHeight: other.itemHeight ?? itemHeight,
      itemGap: other.itemGap ?? itemGap,
      itemRadius: other.itemRadius ?? itemRadius,
      itemBackground: other.itemBackground ?? itemBackground,
      itemForeground: other.itemForeground ?? itemForeground,
      itemBorderColor: other.itemBorderColor ?? itemBorderColor,
      itemTextStyle:
          itemTextStyle?.merge(other.itemTextStyle) ?? other.itemTextStyle,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
    );
  }

  DsTimePickerStyle get _base => DsTimePickerStyle(
    fieldStyle: fieldStyle,
    buttonStyle: buttonStyle,
    panelStyle: panelStyle,
    columnWidth: columnWidth,
    columnGap: columnGap,
    dividerColor: dividerColor,
    visibleItems: visibleItems,
    itemHeight: itemHeight,
    itemGap: itemGap,
    itemRadius: itemRadius,
    itemBackground: itemBackground,
    itemForeground: itemForeground,
    itemBorderColor: itemBorderColor,
    itemTextStyle: itemTextStyle,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsTimePickerStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsTimePickerStyle resolveLayers(
    Iterable<DsTimePickerStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsTimePickerStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    fieldStyle,
    buttonStyle,
    panelStyle,
    columnWidth,
    columnGap,
    dividerColor,
    visibleItems,
    itemHeight,
    itemGap,
    itemRadius,
    itemBackground,
    itemForeground,
    itemBorderColor,
    itemTextStyle,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsTimePickerStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(
      DiagnosticsProperty('fieldStyle', fieldStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('buttonStyle', buttonStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('panelStyle', panelStyle, defaultValue: null),
    );
    properties.add(
      DoubleProperty('columnWidth', columnWidth, defaultValue: null),
    );
    properties.add(DoubleProperty('columnGap', columnGap, defaultValue: null));
    properties.add(
      ColorProperty('dividerColor', dividerColor, defaultValue: null),
    );
    properties.add(
      DoubleProperty('visibleItems', visibleItems, defaultValue: null),
    );
    properties.add(
      DoubleProperty('itemHeight', itemHeight, defaultValue: null),
    );
    properties.add(DoubleProperty('itemGap', itemGap, defaultValue: null));
    properties.add(
      DiagnosticsProperty('itemRadius', itemRadius, defaultValue: null),
    );
    properties.add(
      ColorProperty('itemBackground', itemBackground, defaultValue: null),
    );
    properties.add(
      ColorProperty('itemForeground', itemForeground, defaultValue: null),
    );
    properties.add(
      ColorProperty('itemBorderColor', itemBorderColor, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('itemTextStyle', itemTextStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
  }
}

/// Defaults for every `DsTimePicker` in a subtree; see [DsTimePickerTheme].
class DsTimePickerThemeData
    extends DsComponentThemeData<DsTimePickerThemeData> {
  /// Creates defaults.
  const DsTimePickerThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsTimePickerStyle? style;

  @override
  DsTimePickerThemeData merge(DsTimePickerThemeData? other) {
    if (other == null) return this;
    return DsTimePickerThemeData(
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsTimePickerThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsTimePickerThemeData] to a subtree, merged over any outer one.
class DsTimePickerTheme extends DsComponentTheme<DsTimePickerThemeData> {
  /// Applies [data] to [child].
  const DsTimePickerTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsTimePickerThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsTimePickerThemeData>(context) ??
      const DsTimePickerThemeData();
}
