// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';

/// The look of a `DsSpinner`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsSpinnerStyle with Diagnosticable {
  /// Creates a style.
  const DsSpinnerStyle({this.size, this.color, this.strokeWidth});

  /// Diameter. When no layer sets it, 7/8 of the ambient icon size (14 without one).
  final double? size;

  /// Ring color. When no layer sets it, the ambient icon color.
  final Color? color;

  /// Ring thickness.
  final double? strokeWidth;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsSpinnerStyle merge(DsSpinnerStyle? other) {
    if (other == null) return this;
    return DsSpinnerStyle(
      size: other.size ?? size,
      color: other.color ?? color,
      strokeWidth: other.strokeWidth ?? strokeWidth,
    );
  }

  /// This style; it has no state styles.
  DsSpinnerStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsSpinnerStyle resolveLayers(
    Iterable<DsSpinnerStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsSpinnerStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [size, color, strokeWidth];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsSpinnerStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('size', size, defaultValue: null));
    properties.add(ColorProperty('color', color, defaultValue: null));
    properties.add(
      DoubleProperty('strokeWidth', strokeWidth, defaultValue: null),
    );
  }
}

/// Defaults for every `DsSpinner` in a subtree; see [DsSpinnerTheme].
class DsSpinnerThemeData extends DsComponentThemeData<DsSpinnerThemeData> {
  /// Creates defaults.
  const DsSpinnerThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsSpinnerStyle? style;

  @override
  DsSpinnerThemeData merge(DsSpinnerThemeData? other) {
    if (other == null) return this;
    return DsSpinnerThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsSpinnerThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsSpinnerThemeData] to a subtree, merged over any outer one.
class DsSpinnerTheme extends DsComponentTheme<DsSpinnerThemeData> {
  /// Applies [data] to [child].
  const DsSpinnerTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsSpinnerThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsSpinnerThemeData>(context) ??
      const DsSpinnerThemeData();
}
