// GENERATED by tool/gen_icons.py from tool/icons/. Do not edit by hand.

part of '../icons.dart';

const _arrowBigDownDash = DsIconData([
  'M14 8a1 1 0 0 1 1 1v2a1 1 0 0 0 1 1h3.293a.707.707 0 0 1 .5 1.207l-6.939 6.939a1.207 1.207 0 0 1-1.708 0l-6.94-6.94a.707.707 0 0 1 .5-1.206H8a1 1 0 0 0 1-1V9a1 1 0 0 1 1-1z',
  'M9 4h6',
]);

const _arrowBigDown = DsIconData([
  'M9 5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v6a1 1 0 0 0 1 1h3.293a.707.707 0 0 1 .5 1.207l-7.086 7.086a1 1 0 0 1-1.414 0l-7.086-7.086a.707.707 0 0 1 .5-1.207H8a1 1 0 0 0 1-1z',
]);

const _arrowBigLeftDash = DsIconData([
  'M13 9a1 1 0 0 1-1-1V4.707a.707.707 0 0 0-1.207-.5l-6.94 6.94a1.207 1.207 0 0 0 0 1.707l6.94 6.94a.707.707 0 0 0 1.207-.5V16a1 1 0 0 1 1-1h2a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1z',
  'M20 9v6',
], matchTextDirection: true);

const _arrowBigLeft = DsIconData([
  'M10.793 19.793a.707.707 0 0 0 1.207-.5V16a1 1 0 0 1 1-1h6a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1h-6a1 1 0 0 1-1-1V4.707a.707.707 0 0 0-1.207-.5l-6.94 6.94a1.207 1.207 0 0 0 0 1.707z',
], matchTextDirection: true);

const _arrowBigRightDash = DsIconData([
  'M11 9a1 1 0 0 0 1-1V4.707a.707.707 0 0 1 1.207-.5l6.94 6.94a1.207 1.207 0 0 1 0 1.707l-6.94 6.94a.707.707 0 0 1-1.207-.5V16a1 1 0 0 0-1-1H9a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1z',
  'M4 9v6',
], matchTextDirection: true);

const _arrowBigRight = DsIconData([
  'M13.207 19.793a.707.707 0 0 1-1.207-.5V16a1 1 0 0 0-1-1H5a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1h6a1 1 0 0 0 1-1V4.707a.707.707 0 0 1 1.207-.5l6.94 6.94a1.207 1.207 0 0 1 0 1.707z',
], matchTextDirection: true);

const _arrowBigUpDash = DsIconData([
  'M14 16a1 1 0 0 0 1-1v-2a1 1 0 0 1 1-1h3.293a.707.707 0 0 0 .5-1.207l-6.939-6.939a1.207 1.207 0 0 0-1.708 0l-6.94 6.94a.707.707 0 0 0 .5 1.206H8a1 1 0 0 1 1 1v2a1 1 0 0 0 1 1z',
  'M9 20h6',
]);

const _arrowBigUp = DsIconData([
  'M9 19a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1v-6a1 1 0 0 1 1-1h3.293a.707.707 0 0 0 .5-1.207l-7.086-7.086a1 1 0 0 0-1.414 0l-7.086 7.086a.707.707 0 0 0 .5 1.207H8a1 1 0 0 1 1 1z',
]);

const _arrowDownFromLine = DsIconData(['M19 3H5', 'M12 21V7', 'm6 15 6 6 6-6']);

const _arrowDownLeft = DsIconData(['M17 7 7 17', 'M17 17H7V7']);

const _arrowDownRight = DsIconData(['m7 7 10 10', 'M17 7v10H7']);

const _arrowDownToDot = DsIconData([
  'M12 2v14',
  'm19 9-7 7-7-7',
  'M11 21a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
]);

const _arrowDownToLine = DsIconData(['M12 17V3', 'm6 11 6 6 6-6', 'M19 21H5']);

const _arrowDownUp = DsIconData([
  'm3 16 4 4 4-4',
  'M7 20V4',
  'm21 8-4-4-4 4',
  'M17 4v16',
]);

const _arrowDown = DsIconData(['M12 5v14', 'm19 12-7 7-7-7']);

const _arrowLeftFromLine = DsIconData([
  'm9 6-6 6 6 6',
  'M3 12h14',
  'M21 19V5',
], matchTextDirection: true);

const _arrowLeftRight = DsIconData([
  'M8 3 4 7l4 4',
  'M4 7h16',
  'm16 21 4-4-4-4',
  'M20 17H4',
]);

const _arrowLeftToLine = DsIconData([
  'M3 19V5',
  'm13 6-6 6 6 6',
  'M7 12h14',
], matchTextDirection: true);

const _arrowLeft = DsIconData([
  'm12 19-7-7 7-7',
  'M19 12H5',
], matchTextDirection: true);

const _arrowRightFromLine = DsIconData([
  'M3 5v14',
  'M21 12H7',
  'm15 18 6-6-6-6',
], matchTextDirection: true);

const _arrowRightLeft = DsIconData([
  'm16 3 4 4-4 4',
  'M20 7H4',
  'm8 21-4-4 4-4',
  'M4 17h16',
]);

const _arrowRightToLine = DsIconData([
  'M17 12H3',
  'm11 18 6-6-6-6',
  'M21 5v14',
], matchTextDirection: true);

const _arrowRight = DsIconData([
  'M5 12h14',
  'm12 5 7 7-7 7',
], matchTextDirection: true);

const _arrowUpDown = DsIconData([
  'm21 16-4 4-4-4',
  'M17 20V4',
  'm3 8 4-4 4 4',
  'M7 4v16',
]);

const _arrowUpFromDot = DsIconData([
  'm5 9 7-7 7 7',
  'M12 16V2',
  'M11 21a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
]);

const _arrowUpFromLine = DsIconData(['m18 9-6-6-6 6', 'M12 3v14', 'M5 21h14']);

const _arrowUpLeft = DsIconData(['M7 17V7h10', 'M17 17 7 7']);

const _arrowUpRight = DsIconData(['M7 7h10v10', 'M7 17 17 7']);

const _arrowUpToLine = DsIconData(['M5 3h14', 'm18 13-6-6-6 6', 'M12 7v14']);

const _arrowUp = DsIconData(['m5 12 7-7 7 7', 'M12 19V5']);

const _arrowsUpFromLine = DsIconData([
  'm4 6 3-3 3 3',
  'M7 17V3',
  'm14 6 3-3 3 3',
  'M17 17V3',
  'M4 21h16',
]);

const _calendarSync = DsIconData([
  'M11 10v4h4',
  'm11 14 1.535-1.605a5 5 0 018 1.5',
  'M16 2v3',
  'm21 18-1.535 1.605a5 5 0 01-8-1.5',
  'M21 22v-4h-4',
  'M21 8.517V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h3.517',
  'M3 9h4',
  'M8 2v3',
]);

const _chevronDown = DsIconData(['m6 9 6 6 6-6']);

const _chevronFirst = DsIconData([
  'm17 18-6-6 6-6',
  'M7 6v12',
], matchTextDirection: true);

const _chevronLast = DsIconData([
  'm7 18 6-6-6-6',
  'M17 6v12',
], matchTextDirection: true);

const _chevronLeft = DsIconData(['m15 18-6-6 6-6'], matchTextDirection: true);

const _chevronRight = DsIconData(['m9 18 6-6-6-6'], matchTextDirection: true);

const _chevronUp = DsIconData(['m18 15-6-6-6 6']);

const _chevronsDownUp = DsIconData(['m7 20 5-5 5 5', 'm7 4 5 5 5-5']);

const _chevronsDown = DsIconData(['m7 6 5 5 5-5', 'm7 13 5 5 5-5']);

const _chevronsLeftRight = DsIconData(['m9 7-5 5 5 5', 'm15 7 5 5-5 5']);

const _chevronsLeft = DsIconData([
  'm11 17-5-5 5-5',
  'm18 17-5-5 5-5',
], matchTextDirection: true);

const _chevronsRightLeft = DsIconData(['m20 17-5-5 5-5', 'm4 17 5-5-5-5']);

const _chevronsRight = DsIconData([
  'm6 17 5-5-5-5',
  'm13 17 5-5-5-5',
], matchTextDirection: true);

const _chevronsUpDown = DsIconData(['m7 15 5 5 5-5', 'm7 9 5-5 5 5']);

const _chevronsUp = DsIconData(['m17 11-5-5-5 5', 'm17 18-5-5-5 5']);

const _circleArrowDown = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M12 8v8',
  'm8 12 4 4 4-4',
]);

const _circleArrowLeft = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'm12 8-4 4 4 4',
  'M16 12H8',
], matchTextDirection: true);

const _circleArrowOutDownLeft = DsIconData([
  'M2 12a10 10 0 1 1 10 10',
  'm2 22 10-10',
  'M8 22H2v-6',
]);

const _circleArrowOutDownRight = DsIconData([
  'M12 22a10 10 0 1 1 10-10',
  'M22 22 12 12',
  'M22 16v6h-6',
]);

const _circleArrowOutUpLeft = DsIconData([
  'M2 8V2h6',
  'm2 2 10 10',
  'M12 2A10 10 0 1 1 2 12',
]);

const _circleArrowOutUpRight = DsIconData([
  'M22 12A10 10 0 1 1 12 2',
  'M22 2 12 12',
  'M16 2h6v6',
]);

const _circleArrowRight = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'm12 16 4-4-4-4',
  'M8 12h8',
], matchTextDirection: true);

const _circleArrowUp = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'm16 12-4-4-4 4',
  'M12 16V8',
]);

const _circleChevronDown = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'm16 10-4 4-4-4',
]);

const _circleChevronLeft = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'm14 16-4-4 4-4',
], matchTextDirection: true);

const _circleChevronRight = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'm10 8 4 4-4 4',
], matchTextDirection: true);

const _circleChevronUp = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'm8 14 4-4 4 4',
]);

const _circleFadingArrowUp = DsIconData([
  'M12 2a10 10 0 0 1 7.38 16.75',
  'm16 12-4-4-4 4',
  'M12 16V8',
  'M2.5 8.875a10 10 0 0 0-.5 3',
  'M2.83 16a10 10 0 0 0 2.43 3.4',
  'M4.636 5.235a10 10 0 0 1 .891-.857',
  'M8.644 21.42a10 10 0 0 0 7.631-.38',
]);

const _cloudBackup = DsIconData([
  'M21 15.251A4.5 4.5 0 0 0 17.5 8h-1.79A7 7 0 1 0 3 13.607',
  'M7 11v4h4',
  'M8 19a5 5 0 0 0 9-3 4.5 4.5 0 0 0-4.5-4.5 4.82 4.82 0 0 0-3.41 1.41L7 15',
]);

const _cloudDownload = DsIconData([
  'M12 13v8l-4-4',
  'm12 21 4-4',
  'M4.393 15.269A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.436 8.284',
]);

const _cloudSync = DsIconData([
  'm17 18-1.535 1.605a5 5 0 0 1-8-1.5',
  'M17 22v-4h-4',
  'M20.996 15.251A4.5 4.5 0 0 0 17.495 8h-1.79a7 7 0 1 0-12.709 5.607',
  'M7 10v4h4',
  'm7 14 1.535-1.605a5 5 0 0 1 8 1.5',
]);

const _cloudUpload = DsIconData([
  'M12 13v8',
  'M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242',
  'm8 17 4-4 4 4',
]);

const _cornerDownLeft = DsIconData([
  'M20 4v7a4 4 0 0 1-4 4H4',
  'm9 10-5 5 5 5',
], matchTextDirection: true);

const _cornerDownRight = DsIconData([
  'm15 10 5 5-5 5',
  'M4 4v7a4 4 0 0 0 4 4h12',
], matchTextDirection: true);

const _cornerLeftDown = DsIconData([
  'm14 15-5 5-5-5',
  'M20 4h-7a4 4 0 0 0-4 4v12',
], matchTextDirection: true);

const _cornerLeftUp = DsIconData([
  'M14 9 9 4 4 9',
  'M20 20h-7a4 4 0 0 1-4-4V4',
], matchTextDirection: true);

const _cornerRightDown = DsIconData([
  'm10 15 5 5 5-5',
  'M4 4h7a4 4 0 0 1 4 4v12',
], matchTextDirection: true);

const _cornerRightUp = DsIconData([
  'm10 9 5-5 5 5',
  'M4 20h7a4 4 0 0 0 4-4V4',
], matchTextDirection: true);

const _cornerUpLeft = DsIconData([
  'M20 20v-7a4 4 0 0 0-4-4H4',
  'M9 14 4 9l5-5',
], matchTextDirection: true);

const _cornerUpRight = DsIconData([
  'm15 14 5-5-5-5',
  'M4 20v-7a4 4 0 0 1 4-4h12',
], matchTextDirection: true);

const _download = DsIconData([
  'M12 15V3',
  'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4',
  'm7 10 5 5 5-5',
]);

const _externalLink = DsIconData([
  'M15 3h6v6',
  'M10 14 21 3',
  'M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6',
]);

const _foldHorizontal = DsIconData([
  'M2 12h6',
  'M22 12h-6',
  'M12 2v2',
  'M12 8v2',
  'M12 14v2',
  'M12 20v2',
  'm19 9-3 3 3 3',
  'm5 15 3-3-3-3',
]);

const _foldVertical = DsIconData([
  'M12 22v-6',
  'M12 8V2',
  'M4 12H2',
  'M10 12H8',
  'M16 12h-2',
  'M22 12h-2',
  'm15 19-3-3-3 3',
  'm15 5-3 3-3-3',
]);

const _handGrab = DsIconData([
  'M18 11.5V9a2 2 0 0 0-2-2a2 2 0 0 0-2 2v1.4',
  'M14 10V8a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2',
  'M10 9.9V9a2 2 0 0 0-2-2a2 2 0 0 0-2 2v5',
  'M6 14a2 2 0 0 0-2-2a2 2 0 0 0-2 2',
  'M18 11a2 2 0 1 1 4 0v3a8 8 0 0 1-8 8h-4a8 8 0 0 1-8-8 2 2 0 1 1 4 0',
]);

const _hand = DsIconData([
  'M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2',
  'M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2',
  'M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8',
  'M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15',
]);

const _import = DsIconData([
  'M12 3v12',
  'm8 11 4 4 4-4',
  'M8 5H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-4',
]);

const _iterationCcw = DsIconData(['m16 14 4 4-4 4', 'M20 10a8 8 0 1 0-8 8h8']);

const _iterationCw = DsIconData(['M4 10a8 8 0 1 1 8 8H4', 'm8 22-4-4 4-4']);

const _lassoSelect = DsIconData([
  'M7 22a5 5 0 0 1-2-4',
  'M7 16.93c.96.43 1.96.74 2.99.91',
  'M3.34 14A6.8 6.8 0 0 1 2 10c0-4.42 4.48-8 10-8s10 3.58 10 8a7.19 7.19 0 0 1-.33 2',
  'M5 18a2 2 0 1 0 0-4 2 2 0 0 0 0 4z',
  'M14.33 22h-.09a.35.35 0 0 1-.24-.32v-10a.34.34 0 0 1 .33-.34c.08 0 .15.03.21.08l7.34 6a.33.33 0 0 1-.21.59h-4.49l-2.57 3.85a.35.35 0 0 1-.28.14z',
]);

const _loaderCircle = DsIconData(['M21 12a9 9 0 1 1-6.219-8.56']);

const _loaderPinwheel = DsIconData([
  'M22 12a1 1 0 0 1-10 0 1 1 0 0 0-10 0',
  'M7 20.7a1 1 0 1 1 5-8.7 1 1 0 1 0 5-8.6',
  'M7 3.3a1 1 0 1 1 5 8.6 1 1 0 1 0 5 8.6',
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
]);

const _loader = DsIconData([
  'M12 2v4',
  'm16.2 7.8 2.9-2.9',
  'M18 12h4',
  'm16.2 16.2 2.9 2.9',
  'M12 18v4',
  'm4.9 19.1 2.9-2.9',
  'M2 12h4',
  'm4.9 4.9 2.9 2.9',
]);

const _logIn = DsIconData([
  'm10 17 5-5-5-5',
  'M15 12H3',
  'M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4',
], matchTextDirection: true);

const _logOut = DsIconData([
  'm16 17 5-5-5-5',
  'M21 12H9',
  'M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4',
], matchTextDirection: true);

const _maximize2 = DsIconData([
  'M15 3h6v6',
  'm21 3-7 7',
  'm3 21 7-7',
  'M9 21H3v-6',
]);

const _milestone = DsIconData([
  'M12 13v8',
  'M12 3v3',
  'M18.172 6a2 2 0 0 1 1.414.586l2.06 2.06a1.207 1.207 0 0 1 0 1.708l-2.06 2.06a2 2 0 0 1-1.414.586H4a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1z',
]);

const _minimize2 = DsIconData([
  'm14 10 7-7',
  'M20 10h-6V4',
  'm3 21 7-7',
  'M4 14h6v6',
]);

const _mousePointer2Off = DsIconData([
  'm15.55 8.45 5.138 2.087a.5.5 0 0 1-.063.947l-6.124 1.58a2 2 0 0 0-1.438 1.435l-1.579 6.126a.5.5 0 0 1-.947.063L8.45 15.551',
  'M22 2 2 22',
  'm6.816 11.528-2.779-6.84a.495.495 0 0 1 .651-.651l6.84 2.779',
]);

const _mousePointer2 = DsIconData([
  'M4.037 4.688a.495.495 0 0 1 .651-.651l16 6.5a.5.5 0 0 1-.063.947l-6.124 1.58a2 2 0 0 0-1.438 1.435l-1.579 6.126a.5.5 0 0 1-.947.063z',
]);

const _mousePointerBan = DsIconData([
  'M2.034 2.681a.498.498 0 0 1 .647-.647l9 3.5a.5.5 0 0 1-.033.944L8.204 7.545a1 1 0 0 0-.66.66l-1.066 3.443a.5.5 0 0 1-.944.033z',
  'M10 16a6 6 0 1 0 12 0a6 6 0 1 0 -12 0',
  'm11.8 11.8 8.4 8.4',
]);

const _mousePointerClick = DsIconData([
  'M14 4.1 12 6',
  'm5.1 8-2.9-.8',
  'm6 12-1.9 2',
  'M7.2 2.2 8 5.1',
  'M9.037 9.69a.498.498 0 0 1 .653-.653l11 4.5a.5.5 0 0 1-.074.949l-4.349 1.041a1 1 0 0 0-.74.739l-1.04 4.35a.5.5 0 0 1-.95.074z',
]);

const _mousePointer = DsIconData([
  'M12.586 12.586 19 19',
  'M3.688 3.037a.497.497 0 0 0-.651.651l6.5 15.999a.501.501 0 0 0 .947-.062l1.569-6.083a2 2 0 0 1 1.448-1.479l6.124-1.579a.5.5 0 0 0 .063-.947z',
]);

const _moveDiagonal2 = DsIconData(['M19 13v6h-6', 'M5 11V5h6', 'm5 5 14 14']);

const _moveDiagonal = DsIconData(['M11 19H5v-6', 'M13 5h6v6', 'M19 5 5 19']);

const _moveDownLeft = DsIconData(['M11 19H5V13', 'M19 5L5 19']);

const _moveDownRight = DsIconData(['M19 13V19H13', 'M5 5L19 19']);

const _moveDown = DsIconData(['M8 18L12 22L16 18', 'M12 2V22']);

const _moveHorizontal = DsIconData([
  'm18 8 4 4-4 4',
  'M2 12h20',
  'm6 8-4 4 4 4',
]);

const _moveLeft = DsIconData(['M6 8L2 12L6 16', 'M2 12H22']);

const _moveRight = DsIconData(['M18 8L22 12L18 16', 'M2 12H22']);

const _moveUpLeft = DsIconData(['M5 11V5H11', 'M5 5L19 19']);

const _moveUpRight = DsIconData(['M13 5H19V11', 'M19 5L5 19']);

const _moveUp = DsIconData(['M8 6L12 2L16 6', 'M12 2V22']);

const _moveVertical = DsIconData(['M12 2v20', 'm8 18 4 4 4-4', 'm8 6 4-4 4 4']);

const _move = DsIconData([
  'M12 2v20',
  'm15 19-3 3-3-3',
  'm19 9 3 3-3 3',
  'M2 12h20',
  'm5 9-3 3 3 3',
  'm9 5 3-3 3 3',
]);

const _phoneForwarded = DsIconData([
  'M14 6h8',
  'm18 2 4 4-4 4',
  'M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384',
]);

const _phoneIncoming = DsIconData([
  'M16 2v6h6',
  'm22 2-6 6',
  'M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384',
]);

const _phoneOutgoing = DsIconData([
  'm16 8 6-6',
  'M22 8V2h-6',
  'M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384',
]);

const _play = DsIconData([
  'M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z',
]);

const _pointerOff = DsIconData([
  'M10 4.5V4a2 2 0 0 0-2.41-1.957',
  'M13.9 8.4a2 2 0 0 0-1.26-1.295',
  'M21.7 16.2A8 8 0 0 0 22 14v-3a2 2 0 1 0-4 0v-1a2 2 0 0 0-3.63-1.158',
  'm7 15-1.8-1.8a2 2 0 0 0-2.79 2.86L6 19.7a7.74 7.74 0 0 0 6 2.3h2a8 8 0 0 0 5.657-2.343',
  'M6 6v8',
  'm2 2 20 20',
]);

const _pointer = DsIconData([
  'M22 14a8 8 0 0 1-8 8',
  'M18 11v-1a2 2 0 0 0-2-2a2 2 0 0 0-2 2',
  'M14 10V9a2 2 0 0 0-2-2a2 2 0 0 0-2 2v1',
  'M10 9.5V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v10',
  'M18 11a2 2 0 1 1 4 0v3a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15',
]);

const _refreshCcwDot = DsIconData([
  'M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8',
  'M3 3v5h5',
  'M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16',
  'M16 16h5v5',
  'M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
]);

const _refreshCcw = DsIconData([
  'M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8',
  'M3 3v5h5',
  'M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16',
  'M16 16h5v5',
]);

const _refreshCwOff = DsIconData([
  'M21 8L18.74 5.74A9.75 9.75 0 0 0 12 3C11 3 10.03 3.16 9.13 3.47',
  'M8 16H3v5',
  'M3 12C3 9.51 4 7.26 5.64 5.64',
  'm3 16 2.26 2.26A9.75 9.75 0 0 0 12 21c2.49 0 4.74-1 6.36-2.64',
  'M21 12c0 1-.16 1.97-.47 2.87',
  'M21 3v5h-5',
  'M22 22 2 2',
]);

const _refreshCw = DsIconData([
  'M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8',
  'M21 3v5h-5',
  'M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16',
  'M8 16H3v5',
]);

const _repeat2 = DsIconData([
  'm2 9 3-3 3 3',
  'M13 18H7a2 2 0 0 1-2-2V6',
  'm22 15-3 3-3-3',
  'M11 6h6a2 2 0 0 1 2 2v10',
]);

const _repeatOff = DsIconData([
  'M11.656 6H21l-4-4',
  'M17.898 17.898A4 4 0 0 1 17 18H3l4-4',
  'm2 2 20 20',
  'M21 13v1a4 4 0 0 1-.171 1.159',
  'm21 6-4 4',
  'M3 11v-1a4 4 0 0 1 3.102-3.898',
  'm7 22-4-4',
]);

const _repeat = DsIconData([
  'm17 2 4 4-4 4',
  'M3 11v-1a4 4 0 0 1 4-4h14',
  'm7 22-4-4 4-4',
  'M21 13v1a4 4 0 0 1-4 4H3',
]);

const _rewind = DsIconData([
  'M12 6a2 2 0 0 0-3.414-1.414l-6 6a2 2 0 0 0 0 2.828l6 6A2 2 0 0 0 12 18z',
  'M22 6a2 2 0 0 0-3.414-1.414l-6 6a2 2 0 0 0 0 2.828l6 6A2 2 0 0 0 22 18z',
]);

const _rotateCcwClock = DsIconData([
  'M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8',
  'M3 3v5h5',
  'M12 7v5l4 2',
]);

const _rotateCcw = DsIconData([
  'M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8',
  'M3 3v5h5',
]);

const _rotateCwClock = DsIconData([
  'M12 7v5l4 2',
  'M16 8h5V3',
  'm21 8-2.3-2.3A9.7 9.7 0 0012 3a9 9 0 109 9',
]);

const _rotateCw = DsIconData([
  'M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8',
  'M21 3v5h-5',
]);

const _signpostBig = DsIconData([
  'M10 9H4L2 7l2-2h6',
  'M14 5h6l2 2-2 2h-6',
  'M10 22V4a2 2 0 1 1 4 0v18',
  'M8 22h8',
]);

const _signpost = DsIconData([
  'M12 13v8',
  'M12 3v3',
  'M2.354 10.354a1.207 1.207 0 0 1 0-1.708l2.06-2.06A2 2 0 0 1 5.828 6h12.344a2 2 0 0 1 1.414.586l2.06 2.06a1.207 1.207 0 0 1 0 1.708l-2.06 2.06a2 2 0 0 1-1.414.586H5.828a2 2 0 0 1-1.414-.586z',
]);

const _sparkles = DsIconData([
  'M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z',
  'M20 2v4',
  'M22 4h-4',
  'M2 20a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
]);

const _splinePointer = DsIconData([
  'M12.034 12.681a.498.498 0 0 1 .647-.647l9 3.5a.5.5 0 0 1-.033.943l-3.444 1.068a1 1 0 0 0-.66.66l-1.067 3.443a.5.5 0 0 1-.943.033z',
  'M5 17A12 12 0 0 1 17 5',
  'M17 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
  'M3 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
]);

const _squareArrowDownLeft = DsIconData([
  'M15 15H9l6-6',
  'M9 15V9',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _squareArrowDownRight = DsIconData([
  'M15 15 9 9',
  'M9 15h6V9',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _squareArrowDown = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M12 8v8',
  'm8 12 4 4 4-4',
]);

const _squareArrowLeft = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'm12 8-4 4 4 4',
  'M16 12H8',
], matchTextDirection: true);

const _squareArrowOutDownLeft = DsIconData([
  'M13 21h6a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v6',
  'm3 21 9-9',
  'M9 21H3v-6',
]);

const _squareArrowOutDownRight = DsIconData([
  'M21 11V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h6',
  'm21 21-9-9',
  'M21 15v6h-6',
]);

const _squareArrowOutUpLeft = DsIconData([
  'M13 3h6a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-6',
  'm3 3 9 9',
  'M3 9V3h6',
]);

const _squareArrowOutUpRight = DsIconData([
  'M21 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h6',
  'm21 3-9 9',
  'M15 3h6v6',
]);

const _squareArrowRightEnter = DsIconData([
  'm10 16 4-4-4-4',
  'M3 12h11',
  'M3 8V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-3',
], matchTextDirection: true);

const _squareArrowRightExit = DsIconData([
  'M10 12h11',
  'm17 16 4-4-4-4',
  'M21 6.344V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-1.344',
], matchTextDirection: true);

const _squareArrowRight = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M8 12h8',
  'm12 16 4-4-4-4',
], matchTextDirection: true);

const _squareArrowUpLeft = DsIconData([
  'M15 15 9 9',
  'M9 15V9h6',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _squareArrowUpRight = DsIconData([
  'M15 15V9H9',
  'm9 15 6-6',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _squareArrowUp = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'm16 12-4-4-4 4',
  'M12 16V8',
]);

const _squareChevronDown = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'm16 10-4 4-4-4',
]);

const _squareChevronLeft = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'm14 16-4-4 4-4',
], matchTextDirection: true);

const _squareChevronRight = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'm10 8 4 4-4 4',
], matchTextDirection: true);

const _squareChevronUp = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'm8 14 4-4 4 4',
]);

const _squareDashedMousePointer = DsIconData([
  'M12.034 12.681a.498.498 0 0 1 .647-.647l9 3.5a.5.5 0 0 1-.033.943l-3.444 1.068a1 1 0 0 0-.66.66l-1.067 3.443a.5.5 0 0 1-.943.033z',
  'M5 3a2 2 0 0 0-2 2',
  'M19 3a2 2 0 0 1 2 2',
  'M5 21a2 2 0 0 1-2-2',
  'M9 3h1',
  'M9 21h2',
  'M14 3h1',
  'M3 9v1',
  'M21 9v2',
  'M3 14v1',
]);

const _squareMousePointer = DsIconData([
  'M12.034 12.681a.498.498 0 0 1 .647-.647l9 3.5a.5.5 0 0 1-.033.943l-3.444 1.068a1 1 0 0 0-.66.66l-1.067 3.443a.5.5 0 0 1-.943.033z',
  'M21 11V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h6',
]);

const _squarePlay = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M9 9.003a1 1 0 0 1 1.517-.859l4.997 2.997a1 1 0 0 1 0 1.718l-4.997 2.997A1 1 0 0 1 9 14.996z',
]);

const _sunrise = DsIconData([
  'M12 2v8',
  'm4.93 10.93 1.41 1.41',
  'M2 18h2',
  'M20 18h2',
  'm19.07 10.93-1.41 1.41',
  'M22 22H2',
  'm8 6 4-4 4 4',
  'M16 18a4 4 0 0 0-8 0',
]);

const _sunset = DsIconData([
  'M12 10V2',
  'm4.93 10.93 1.41 1.41',
  'M2 18h2',
  'M20 18h2',
  'm19.07 10.93-1.41 1.41',
  'M22 22H2',
  'm16 6-4 4-4-4',
  'M16 18a4 4 0 0 0-8 0',
]);

const _unfoldHorizontal = DsIconData([
  'M16 12h6',
  'M8 12H2',
  'M12 2v2',
  'M12 8v2',
  'M12 14v2',
  'M12 20v2',
  'm19 15 3-3-3-3',
  'm5 9-3 3 3 3',
]);

const _unfoldVertical = DsIconData([
  'M12 22v-6',
  'M12 8V2',
  'M4 12H2',
  'M10 12H8',
  'M16 12h-2',
  'M22 12h-2',
  'm15 19-3 3-3-3',
  'm15 5-3-3-3 3',
]);

const _upload = DsIconData([
  'M12 3v12',
  'm17 8-5-5-5 5',
  'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4',
]);
