// GENERATED by tool/gen_icons.py from tool/icons/. Do not edit by hand.

part of '../icons.dart';

const _chartArea = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M7 11.207a.5.5 0 0 1 .146-.353l2-2a.5.5 0 0 1 .708 0l3.292 3.292a.5.5 0 0 0 .708 0l4.292-4.292a.5.5 0 0 1 .854.353V16a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1z',
]);

const _chartBarBig = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M8 13h7a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-7a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M8 5h10a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-10a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
]);

const _chartBarDecreasing = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M7 11h8',
  'M7 16h3',
  'M7 6h12',
]);

const _chartBarIncreasing = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M7 11h8',
  'M7 16h12',
  'M7 6h3',
]);

const _chartBarStacked = DsIconData([
  'M11 13v4',
  'M15 5v4',
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M8 13h7a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-7a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M8 5h10a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-10a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
]);

const _chartBar = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M7 16h8',
  'M7 11h12',
  'M7 6h3',
]);

const _chartCandlestick = DsIconData([
  'M9 5v4',
  'M8 9h2a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1z',
  'M9 15v2',
  'M17 3v2',
  'M16 5h2a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1z',
  'M17 13v3',
  'M3 3v16a2 2 0 0 0 2 2h16',
]);

const _chartColumnBig = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M16 5h2a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-10a1 1 0 0 1 1 -1z',
  'M8 8h2a1 1 0 0 1 1 1v7a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-7a1 1 0 0 1 1 -1z',
]);

const _chartColumnDecreasing = DsIconData([
  'M13 17V9',
  'M18 17v-3',
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M8 17V5',
]);

const _chartColumnIncreasing = DsIconData([
  'M13 17V9',
  'M18 17V5',
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M8 17v-3',
]);

const _chartColumnStacked = DsIconData([
  'M11 13H7',
  'M19 9h-4',
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M16 5h2a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-10a1 1 0 0 1 1 -1z',
  'M8 8h2a1 1 0 0 1 1 1v7a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-7a1 1 0 0 1 1 -1z',
]);

const _chartColumn = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M18 17V9',
  'M13 17V5',
  'M8 17v-3',
]);

const _chartGantt = DsIconData([
  'M10 6h8',
  'M12 16h6',
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M8 11h7',
]);

const _chartLine = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'm19 9-5 5-4-4-3 3',
]);

const _chartNetwork = DsIconData([
  'm13.11 7.664 1.78 2.672',
  'm14.162 12.788-3.324 1.424',
  'm20 4-6.06 1.515',
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M10 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
  'M14 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
  'M7 15a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
]);

const _chartNoAxesColumnDecreasing = DsIconData([
  'M5 21V3',
  'M12 21V9',
  'M19 21v-6',
]);

const _chartNoAxesColumnIncreasing = DsIconData([
  'M5 21v-6',
  'M12 21V9',
  'M19 21V3',
]);

const _chartNoAxesColumn = DsIconData(['M5 21v-6', 'M12 21V3', 'M19 21V9']);

const _chartNoAxesCombined = DsIconData([
  'M12 16v5',
  'M16 14.639V21',
  'M20 10.656V21',
  'm22 3-8.646 8.646a.5.5 0 0 1-.708 0L9.354 8.354a.5.5 0 0 0-.707 0L2 15',
  'M4 18.463V21',
  'M8 14.656V21',
]);

const _chartNoAxesGantt = DsIconData(['M6 5h12', 'M4 12h10', 'M12 19h8']);

const _chartPie = DsIconData([
  'M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z',
  'M21.21 15.89A10 10 0 1 1 8 2.83',
]);

const _chartScatter = DsIconData([
  'M7 7.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0',
  'M18 5.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0',
  'M11 11.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0',
  'M7 16.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0',
  'M17 14.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0',
  'M3 3v16a2 2 0 0 0 2 2h16',
]);

const _chartSpline = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M7 16c.5-2 1.5-7 4-7 2 0 2 3 4 3 2.5 0 4.5-5 5-7',
]);

const _folderKanban = DsIconData([
  'M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.93a2 2 0 0 1-1.66-.9l-.82-1.2A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2Z',
  'M8 10v4',
  'M12 10v2',
  'M16 10v6',
]);

const _kanban = DsIconData(['M5 3v14', 'M12 3v8', 'M19 3v18']);

const _squareChartGantt = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M9 8h7',
  'M8 12h6',
  'M11 16h5',
]);

const _squareDashedKanban = DsIconData([
  'M8 7v7',
  'M12 7v4',
  'M16 7v9',
  'M5 3a2 2 0 0 0-2 2',
  'M9 3h1',
  'M14 3h1',
  'M19 3a2 2 0 0 1 2 2',
  'M21 9v1',
  'M21 14v1',
  'M21 19a2 2 0 0 1-2 2',
  'M14 21h1',
  'M9 21h1',
  'M5 21a2 2 0 0 1-2-2',
  'M3 14v1',
  'M3 9v1',
]);

const _squareKanban = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M8 7v7',
  'M12 7v4',
  'M16 7v9',
]);

const _trendingDown = DsIconData(['M16 17h6v-6', 'm22 17-8.5-8.5-5 5L2 7']);

const _trendingUpDown = DsIconData([
  'M14.828 14.828 21 21',
  'M21 16v5h-5',
  'm21 3-9 9-4-4-6 6',
  'M21 8V3h-5',
]);

const _trendingUp = DsIconData(['M16 7h6v6', 'm22 7-8.5 8.5-5-5L2 17']);
