// GENERATED by tool/gen_icons.py from tool/icons/. Do not edit by hand.

part of '../icons.dart';

const _angle = DsIconData([
  'M3 3v16a2 2 0 0 0 2 2h16',
  'M3 11a10 10 0 0 1 10 10',
]);

const _calculator = DsIconData([
  'M6 2h12a2 2 0 0 1 2 2v16a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-16a2 2 0 0 1 2 -2z',
  'M8 6L16 6',
  'M16 14L16 18',
  'M16 10h.01',
  'M12 10h.01',
  'M8 10h.01',
  'M12 14h.01',
  'M8 14h.01',
  'M12 18h.01',
  'M8 18h.01',
]);

const _circleDivide = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M8 12L16 12',
  'M12 16L12 16',
  'M12 8L12 8',
]);

const _circleEqual = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M7 10h10',
  'M7 14h10',
]);

const _circleMinus = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M8 12h8',
]);

const _circlePlus = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M8 12h8',
  'M12 8v8',
]);

const _circleX = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'm15 9-6 6',
  'm9 9 6 6',
]);

const _divide = DsIconData([
  'M11 6a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
  'M5 12L19 12',
  'M11 18a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
]);

const _draftingCompass = DsIconData([
  'm12.99 6.74 1.93 3.44',
  'M19.136 12a10 10 0 0 1-14.271 0',
  'm21 21-2.16-3.84',
  'm3 21 8.02-14.26',
  'M10 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
]);

const _equalApproximatelyNot = DsIconData([
  'M5 15a6.5 6.5 0 0 1 7 0 6.5 6.5 0 0 0 7 0',
  'M5 9a6.5 6.5 0 0 1 7 0 6.5 6.5 0 0 0 7 0',
  'M19 5L5 19',
]);

const _equalApproximately = DsIconData([
  'M5 15a6.5 6.5 0 0 1 7 0 6.5 6.5 0 0 0 7 0',
  'M5 9a6.5 6.5 0 0 1 7 0 6.5 6.5 0 0 0 7 0',
]);

const _equalNot = DsIconData(['M5 9L19 9', 'M5 15L19 15', 'M19 5L5 19']);

const _equal = DsIconData(['M5 9L19 9', 'M5 15L19 15']);

const _minus = DsIconData(['M5 12h14']);

const _octagonX = DsIconData([
  'm15 9-6 6',
  'M2.586 16.726A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2h6.624a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586z',
  'm9 9 6 6',
]);

const _omega = DsIconData([
  'M3 20h4.5a.5.5 0 0 0 .5-.5v-.282a.52.52 0 0 0-.247-.437 8 8 0 1 1 8.494-.001.52.52 0 0 0-.247.438v.282a.5.5 0 0 0 .5.5H21',
]);

const _percent = DsIconData([
  'M19 5L5 19',
  'M4 6.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0',
  'M15 17.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0',
]);

const _phi = DsIconData(['M12 2v20', 'M5 12a7 7 0 1 0 14 0a7 7 0 1 0 -14 0']);

const _plus = DsIconData(['M5 12h14', 'M12 5v14']);

const _squareDivide = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M8 12L16 12',
  'M12 16L12 16',
  'M12 8L12 8',
]);

const _squareEqual = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M7 10h10',
  'M7 14h10',
]);

const _squareMinus = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M8 12h8',
]);

const _squarePlus = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M8 12h8',
  'M12 8v8',
]);

const _squareX = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'm15 9-6 6',
  'm9 9 6 6',
]);

const _tally1 = DsIconData(['M4 4v16']);

const _tally2 = DsIconData(['M4 4v16', 'M9 4v16']);

const _tally3 = DsIconData(['M4 4v16', 'M9 4v16', 'M14 4v16']);

const _tally4 = DsIconData(['M4 4v16', 'M9 4v16', 'M14 4v16', 'M19 4v16']);

const _tally5 = DsIconData([
  'M4 4v16',
  'M9 4v16',
  'M14 4v16',
  'M19 4v16',
  'M22 6 2 18',
]);

const _weightTilde = DsIconData([
  'M6.5 8a2 2 0 0 0-1.906 1.46L2.1 18.5A2 2 0 0 0 4 21h16a2 2 0 0 0 1.925-2.54L19.4 9.5A2 2 0 0 0 17.48 8z',
  'M7.999 15a2.5 2.5 0 0 1 4 0 2.5 2.5 0 0 0 4 0',
  'M9 5a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
]);

const _weight = DsIconData([
  'M9 5a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  'M6.5 8a2 2 0 0 0-1.905 1.46L2.1 18.5A2 2 0 0 0 4 21h16a2 2 0 0 0 1.925-2.54L19.4 9.5A2 2 0 0 0 17.48 8Z',
]);
