// GENERATED by tool/gen_icons.py from tool/icons/. Do not edit by hand.

part of '../icons.dart';

const _bellMinus = DsIconData([
  'M10.268 21a2 2 0 0 0 3.464 0',
  'M15 8h6',
  'M16.243 3.757A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673A9.4 9.4 0 0 1 18.667 12',
]);

const _bellOff = DsIconData([
  'M10.268 21a2 2 0 0 0 3.464 0',
  'M17 17H4a1 1 0 0 1-.74-1.673C4.59 13.956 6 12.499 6 8a6 6 0 0 1 .258-1.742',
  'm2 2 20 20',
  'M8.668 3.01A6 6 0 0 1 18 8c0 2.687.77 4.653 1.707 6.05',
]);

const _bellPlus = DsIconData([
  'M10.268 21a2 2 0 0 0 3.464 0',
  'M15 8h6',
  'M18 5v6',
  'M20.002 14.464a9 9 0 0 0 .738.863A1 1 0 0 1 20 17H4a1 1 0 0 1-.74-1.673C4.59 13.956 6 12.499 6 8a6 6 0 0 1 8.75-5.332',
]);

const _bellRing = DsIconData([
  'M10.268 21a2 2 0 0 0 3.464 0',
  'M22 8c0-2.3-.8-4.3-2-6',
  'M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326',
  'M4 2C2.8 3.7 2 5.7 2 8',
]);

const _checkCheck = DsIconData(['M18 6 7 17l-5-5', 'm22 10-7.5 7.5L13 16']);

const _checkLine = DsIconData(['M20 4L9 15', 'M21 19L3 19', 'M9 15L4 10']);

const _check = DsIconData(['M20 6 9 17l-5-5']);

const _circleAlert = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M12 8L12 12',
  'M12 16L12.01 16',
]);

const _circleCheckBig = DsIconData([
  'M21.801 10A10 10 0 1 1 17 3.335',
  'm9 11 3 3L22 4',
]);

const _circleCheck = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'm16 9-5.5 5.5L8 12',
]);

const _copyX = DsIconData([
  'M4 16a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2',
  'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
  'm12.5 12.5 5 5',
  'm12.5 17.5 5-5',
]);

const _octagonAlert = DsIconData([
  'M12 16h.01',
  'M12 8v4',
  'M15.312 2a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586l-4.688-4.688A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2z',
]);

const _squareCheckBig = DsIconData([
  'M21 10.656V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h12.344',
  'm9 11 3 3L22 4',
]);

const _squareCheck = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'm16 9-5.5 5.5L8 12',
]);

const _squareExclamationPoint = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M12 8L12 12',
  'M12 16L12.01 16',
]);

const _triangleAlert = DsIconData([
  'm21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3',
  'M12 9v4',
  'M12 17h.01',
]);

const _xLineTop = DsIconData(['M18 4H6', 'M18 8 6 20', 'm6 8 12 12']);

const _x = DsIconData(['M18 6 6 18', 'm6 6 12 12']);
