// GENERATED by tool/gen_icons.py from tool/icons/. Do not edit by hand.

part of '../icons.dart';

const _aArrowDown = DsIconData([
  'm14 12 4 4 4-4',
  'M18 16V7',
  'm2 16 4.039-9.69a.5.5 0 0 1 .923 0L11 16',
  'M3.304 13h6.392',
]);

const _aArrowUp = DsIconData([
  'm14 11 4-4 4 4',
  'M18 16V7',
  'm2 16 4.039-9.69a.5.5 0 0 1 .923 0L11 16',
  'M3.304 13h6.392',
]);

const _aLargeSmall = DsIconData([
  'm15 16 2.536-7.328a1.02 1.02 1 0 1 1.928 0L22 16',
  'M15.697 14h5.606',
  'm2 16 4.039-9.69a.5.5 0 0 1 .923 0L11 16',
  'M3.304 13h6.392',
]);

const _ampersandSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M16 17c-4-2-7-6-7-8a2 2 0 0 1 4 0c0 3-5 1.5-5 5 0 1.7 1.3 3 3 3 3 0 5-2 5-4',
]);

const _ampersand = DsIconData([
  'M16 12h3',
  'M17.5 12a8 8 0 0 1-8 8A4.5 4.5 0 0 1 5 15.5c0-6 8-4 8-8.5a3 3 0 1 0-6 0c0 3 2.5 8.5 12 13',
]);

const _ampersands = DsIconData([
  'M10 17c-5-3-7-7-7-9a2 2 0 0 1 4 0c0 2.5-5 2.5-5 6 0 1.7 1.3 3 3 3 2.8 0 5-2.2 5-5',
  'M22 17c-5-3-7-7-7-9a2 2 0 0 1 4 0c0 2.5-5 2.5-5 6 0 1.7 1.3 3 3 3 2.8 0 5-2.2 5-5',
]);

const _arrowDown01 = DsIconData([
  'm3 16 4 4 4-4',
  'M7 20V4',
  'M17 4h0a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h0a2 2 0 0 1 -2 -2v-2a2 2 0 0 1 2 -2z',
  'M17 20v-6h-2',
  'M15 20h4',
]);

const _arrowDown10 = DsIconData([
  'm3 16 4 4 4-4',
  'M7 20V4',
  'M17 10V4h-2',
  'M15 10h4',
  'M17 14h0a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h0a2 2 0 0 1 -2 -2v-2a2 2 0 0 1 2 -2z',
]);

const _arrowDownAZ = DsIconData([
  'm3 16 4 4 4-4',
  'M7 20V4',
  'M20 8h-5',
  'M15 10V6.5a2.5 2.5 0 0 1 5 0V10',
  'M15 14h5l-5 6h5',
]);

const _arrowDownNarrowWide = DsIconData([
  'm3 16 4 4 4-4',
  'M7 20V4',
  'M11 4h4',
  'M11 8h7',
  'M11 12h10',
]);

const _arrowDownWideNarrow = DsIconData([
  'm3 16 4 4 4-4',
  'M7 20V4',
  'M11 4h10',
  'M11 8h7',
  'M11 12h4',
]);

const _arrowDownZA = DsIconData([
  'm3 16 4 4 4-4',
  'M7 4v16',
  'M15 4h5l-5 6h5',
  'M15 20v-3.5a2.5 2.5 0 0 1 5 0V20',
  'M20 18h-5',
]);

const _arrowUp01 = DsIconData([
  'm3 8 4-4 4 4',
  'M7 4v16',
  'M17 4h0a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h0a2 2 0 0 1 -2 -2v-2a2 2 0 0 1 2 -2z',
  'M17 20v-6h-2',
  'M15 20h4',
]);

const _arrowUp10 = DsIconData([
  'm3 8 4-4 4 4',
  'M7 4v16',
  'M17 10V4h-2',
  'M15 10h4',
  'M17 14h0a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h0a2 2 0 0 1 -2 -2v-2a2 2 0 0 1 2 -2z',
]);

const _arrowUpAZ = DsIconData([
  'm3 8 4-4 4 4',
  'M7 4v16',
  'M20 8h-5',
  'M15 10V6.5a2.5 2.5 0 0 1 5 0V10',
  'M15 14h5l-5 6h5',
]);

const _arrowUpNarrowWide = DsIconData([
  'm3 8 4-4 4 4',
  'M7 4v16',
  'M11 12h4',
  'M11 16h7',
  'M11 20h10',
]);

const _arrowUpWideNarrow = DsIconData([
  'm3 8 4-4 4 4',
  'M7 4v16',
  'M11 12h10',
  'M11 16h7',
  'M11 20h4',
]);

const _arrowUpZA = DsIconData([
  'm3 8 4-4 4 4',
  'M7 4v16',
  'M15 4h5l-5 6h5',
  'M15 20v-3.5a2.5 2.5 0 0 1 5 0V20',
  'M20 18h-5',
]);

const _asterisk = DsIconData([
  'M12 5v14',
  'm18.065 8.496-12.125 7',
  'm5.94 8.504 12.125 7',
]);

const _atSignCircle = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M14 17.7a6 6 0 1 1 4-5.7 2 2 0 0 1-4 0',
  'M10 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
]);

const _atSignSquare = DsIconData([
  'M4 2h16a2 2 0 0 1 2 2v16a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-16a2 2 0 0 1 2 -2z',
  'M14 17.7a6 6 0 1 1 4-5.7 2 2 0 0 1-4 0',
  'M10 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
]);

const _atSign = DsIconData([
  'M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0',
  'M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8',
]);

const _baselineSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M9.5 12h5',
  'm9 13 3-6 3 6',
  'M7 17h10',
]);

const _baseline = DsIconData(['M4 20h16', 'm6 16 6-12 6 12', 'M8 12h8']);

const _binary = DsIconData([
  'M16 14h0a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h0a2 2 0 0 1 -2 -2v-2a2 2 0 0 1 2 -2z',
  'M8 4h0a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h0a2 2 0 0 1 -2 -2v-2a2 2 0 0 1 2 -2z',
  'M6 20h4',
  'M14 10h4',
  'M6 14h2v6',
  'M14 4h2v6',
]);

const _boldSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M8 12h5.5a2.5 2.5 0 0 1 0 5H8V7h5a2.5 2.5 0 0 1 0 5',
]);

const _bold = DsIconData([
  'M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8',
]);

const _bookA = DsIconData([
  'M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20',
  'm8 13 4-7 4 7',
  'M9.1 11h5.7',
]);

const _bookAlert = DsIconData([
  'M12 13h.01',
  'M12 6v3',
  'M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20',
]);

const _bookBookmark = DsIconData([
  'M10 2v7.751a.25.25 0 00.407.195l2.28-1.834a.5.5 0 01.627 0l2.28 1.834A.25.25 0 0016 9.751V2',
  'M4 19.5v-15A2.5 2.5 0 016.5 2H19a1 1 0 011 1v18a1 1 0 01-1 1H6.5a1 1 0 010-5H20',
]);

const _bookCheck = DsIconData([
  'M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20',
  'm9 9.5 2 2 4-4',
]);

const _bookOpenCheck = DsIconData([
  'M12 5v16',
  'm16 12 2 2 4-4',
  'M22 6V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2h4.001A2 2 0 0022 17v-1.344',
]);

const _bookOpenText = DsIconData([
  'M12 5v16',
  'M16 13h2',
  'M16 9h2',
  'M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z',
  'M6 13h2',
  'M6 9h2',
]);

const _bookOpen = DsIconData([
  'M12 5v16',
  'M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z',
]);

const _bookSearch = DsIconData([
  'M11 22H5.5a1 1 0 0 1 0-5h4.501',
  'm21 22-1.879-1.878',
  'M3 19.5v-15A2.5 2.5 0 0 1 5.5 2H18a1 1 0 0 1 1 1v8',
  'M14 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
]);

const _bookText = DsIconData([
  'M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20',
  'M8 11h8',
  'M8 7h6',
]);

const _bookType = DsIconData([
  'M10 13h4',
  'M12 6v7',
  'M16 8V6H8v2',
  'M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20',
]);

const _bookX = DsIconData([
  'm14.5 7.5-5 5',
  'M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20',
  'm9.5 7.5 5 5',
]);

const _book = DsIconData([
  'M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20',
]);

const _brush = DsIconData([
  'm11 10 3 3',
  'M6.5 21A3.5 3.5 0 1 0 3 17.5a2.62 2.62 0 0 1-.708 1.792A1 1 0 0 0 3 21z',
  'M9.969 17.031 21.378 5.624a1 1 0 0 0-3.002-3.002L6.967 14.031',
]);

const _caseCamel = DsIconData([
  'M4 13a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  'M10 10v6',
  'M14 12h4.5a2 2 0 0 1 0 4H14V8h4a2 2 0 0 1 0 4',
]);

const _caseKebab = DsIconData([
  'M2 13.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0',
  'M7 11v5',
  'M11 13h2',
  'M17 13.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0',
  'M17 9v7',
]);

const _caseLower = DsIconData([
  'M10 9v7',
  'M14 6v10',
  'M14 12.5a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0',
  'M3 12.5a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0',
]);

const _caseSensitive = DsIconData([
  'm2 16 4.039-9.69a.5.5 0 0 1 .923 0L11 16',
  'M22 9v7',
  'M3.304 13h6.392',
  'M15 12.5a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0',
]);

const _caseSnakeUpper = DsIconData([
  'M2 16v-5.5a2.5 2.5 0 0 1 5 0V16',
  'M7 13H2',
  'M11 16h2',
  'M17 12h3a2 2 0 1 1 0 4h-3V8h2.5a2 2 0 0 1 .1 4',
]);

const _caseSnake = DsIconData([
  'M7 11v5',
  'M2 13.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0',
  'M11 16h2',
  'M17 13.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0',
  'M17 9v7',
]);

const _caseUpper = DsIconData([
  'M15 11h4.5a1 1 0 0 1 0 5h-4a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h3a1 1 0 0 1 0 5',
  'm2 16 4.039-9.69a.5.5 0 0 1 .923 0L11 16',
  'M3.304 13h6.392',
]);

const _chevronsLeftRightSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'm10 15-3-3 3-3',
  'm14 9 3 3-3 3',
]);

const _clipboardCheck = DsIconData([
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
  'm9 14 2 2 4-4',
]);

const _clipboardCopy = DsIconData([
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M8 4H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2',
  'M16 4h2a2 2 0 0 1 2 2v4',
  'M21 14H11',
  'm15 10-4 4 4 4',
]);

const _clipboardList = DsIconData([
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
  'M12 11h4',
  'M12 16h4',
  'M8 11h.01',
  'M8 16h.01',
]);

const _clipboardMinus = DsIconData([
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
  'M9 14h6',
]);

const _clipboardPaste = DsIconData([
  'M11 14h10',
  'M16 4h2a2 2 0 0 1 2 2v1.344',
  'm17 18 4-4-4-4',
  'M8 4H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 1.793-1.113',
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
]);

const _clipboardPenLine = DsIconData([
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M8 4H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-.5',
  'M16 4h2a2 2 0 0 1 1.73 1',
  'M8 18h1',
  'M21.378 12.626a1 1 0 0 0-3.004-3.004l-4.01 4.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z',
]);

const _clipboardPen = DsIconData([
  'M16 4h2a2 2 0 0 1 2 2v2',
  'M21.34 15.664a1 1 0 1 0-3.004-3.004l-5.01 5.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z',
  'M8 22H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
]);

const _clipboardPlus = DsIconData([
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
  'M9 14h6',
  'M12 17v-6',
]);

const _clipboardType = DsIconData([
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
  'M9 12v-1h6v1',
  'M11 17h2',
  'M12 11v6',
]);

const _clipboardX = DsIconData([
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
  'm14.5 11.5-5 5',
  'm9.5 11.5 5 5',
]);

const _clipboard = DsIconData([
  'M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1z',
  'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
]);

const _codeXml = DsIconData(['m18 16 4-4-4-4', 'm6 8-4 4 4 4', 'm14.5 4-5 16']);

const _code = DsIconData(['m16 18 6-6-6-6', 'm8 6-6 6 6 6']);

const _copyCheck = DsIconData([
  'm12 15 2 2 4-4',
  'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
  'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
]);

const _copyCode = DsIconData([
  'M4 16a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2',
  'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
  'm13 13-1 2 1 2',
  'm17 13 1 2-1 2',
]);

const _copyMinus = DsIconData([
  'M12 15L18 15',
  'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
  'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
]);

const _copyPlus = DsIconData([
  'M15 12L15 18',
  'M12 15L18 15',
  'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
  'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
]);

const _copySlash = DsIconData([
  'M12 18L18 12',
  'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
  'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
]);

const _copyText = DsIconData([
  'M4 16a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2',
  'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
  'M12 13h6',
  'M12 17h6',
]);

const _copyType = DsIconData([
  'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
  'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
  'M12 13v-1h6v1',
  'M15 12v6',
  'M14 18h2',
]);

const _copy = DsIconData([
  'M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z',
  'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
]);

const _copyleft = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M9.17 14.83a4 4 0 1 0 0-5.66',
]);

const _copyright = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M14.83 14.83a4 4 0 1 1 0-5.66',
]);

const _creativeCommons = DsIconData([
  'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0',
  'M10 9.3a2.8 2.8 0 0 0-3.5 1 3.1 3.1 0 0 0 0 3.4 2.7 2.7 0 0 0 3.5 1',
  'M17 9.3a2.8 2.8 0 0 0-3.5 1 3.1 3.1 0 0 0 0 3.4 2.7 2.7 0 0 0 3.5 1',
]);

const _delete = DsIconData([
  'M10 5a2 2 0 0 0-1.344.519l-6.328 5.74a1 1 0 0 0 0 1.481l6.328 5.741A2 2 0 0 0 10 19h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2z',
  'm12 9 6 6',
  'm18 9-6 6',
]);

const _eraser = DsIconData([
  'M21 21H8a2 2 0 0 1-1.42-.587l-3.994-3.999a2 2 0 0 1 0-2.828l10-10a2 2 0 0 1 2.829 0l5.999 6a2 2 0 0 1 0 2.828L12.834 21',
  'm5.082 11.09 8.828 8.828',
]);

const _expand = DsIconData([
  'm15 15 6 6',
  'm15 9 6-6',
  'M21 16v5h-5',
  'M21 8V3h-5',
  'M3 16v5h5',
  'm3 21 6-6',
  'M3 8V3h5',
  'M9 9 3 3',
]);

const _featherPlus = DsIconData([
  'M2 7h6',
  'M5 4v6',
  'M5.1 17H14l8-8.2c-2.3-2.3-6.1-2.3-8.5 0L2.1 20',
  'M18 13H9.2',
]);

const _featherSquare = DsIconData([
  'M10.3 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-8.8',
  'M7 12l8.5-8.5c2-2 4.5-2 6.5 0L16.5 9H10',
]);

const _featherText = DsIconData([
  'M17.9 8H9.2',
  'M5.1 12H14l8-8.2c-2.3-2.3-6.1-2.3-8.5 0L2 15',
  'M2 19h8',
  'M21 17v1c0 1 1 1.5 1 2.5 0 .8-.7 1.5-1.5 1.5h-5c-.8 0-1.5-.7-1.5-1.5 0-1 1-1.5 1-2.5v-1',
  'M14 17h8',
]);

const _grid2x2Check = DsIconData([
  'M12 3v17a1 1 0 0 1-1 1H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v6a1 1 0 0 1-1 1H3',
  'm16 19 2 2 4-4',
]);

const _grid2x2Plus = DsIconData([
  'M12 3v17a1 1 0 0 1-1 1H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v6a1 1 0 0 1-1 1H3',
  'M16 19h6',
  'M19 22v-6',
]);

const _grid2x2X = DsIconData([
  'M12 3v17a1 1 0 0 1-1 1H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v6a1 1 0 0 1-1 1H3',
  'm16.5 16.5 5 5',
  'm16.5 21.5 5-5',
]);

const _grid2x2 = DsIconData([
  'M12 3v18',
  'M3 12h18',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _grid3x2 = DsIconData([
  'M15 3v18',
  'M3 12h18',
  'M9 3v18',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _grid3x3 = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M3 9h18',
  'M3 15h18',
  'M9 3v18',
  'M15 3v18',
]);

const _hash = DsIconData([
  'M4 9L20 9',
  'M4 15L20 15',
  'M10 3L8 21',
  'M16 3L14 21',
]);

const _heading1 = DsIconData([
  'M4 12h8',
  'M4 18V6',
  'M12 18V6',
  'm17 12 3-2v8',
]);

const _heading2 = DsIconData([
  'M4 12h8',
  'M4 18V6',
  'M12 18V6',
  'M21 18h-4c0-4 4-3 4-6 0-1.5-2-2.5-4-1',
]);

const _heading3 = DsIconData([
  'M4 12h8',
  'M4 18V6',
  'M12 18V6',
  'M17.5 10.5c1.7-1 3.5 0 3.5 1.5a2 2 0 0 1-2 2',
  'M17 17.5c2 1.5 4 .3 4-1.5a2 2 0 0 0-2-2',
]);

const _heading4 = DsIconData([
  'M12 18V6',
  'M17 10v3a1 1 0 0 0 1 1h3',
  'M21 10v8',
  'M4 12h8',
  'M4 18V6',
]);

const _heading5 = DsIconData([
  'M4 12h8',
  'M4 18V6',
  'M12 18V6',
  'M17 13v-3h4',
  'M17 17.7c.4.2.8.3 1.3.3 1.5 0 2.7-1.1 2.7-2.5S19.8 13 18.3 13H17',
]);

const _heading6 = DsIconData([
  'M4 12h8',
  'M4 18V6',
  'M12 18V6',
  'M17 16a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
  'M20 10c-2 2-3 3.5-3 6',
]);

const _headingSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M8 17V7',
  'M8 12h8',
  'M16 17V7',
]);

const _heading = DsIconData(['M6 12h12', 'M6 20V4', 'M18 20V4']);

const _highlighter = DsIconData([
  'm9 11-6 6v3h9l3-3',
  'm22 12-4.6 4.6a2 2 0 0 1-2.8 0l-5.2-5.2a2 2 0 0 1 0-2.8L14 4',
]);

const _italicSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M16 7h-6',
  'm13.5 7-4 10',
  'M13 17H7',
]);

const _italic = DsIconData(['M19 4L10 4', 'M14 20L5 20', 'M15 4L9 20']);

const _keyboard = DsIconData([
  'M10 8h.01',
  'M12 12h.01',
  'M14 8h.01',
  'M16 12h.01',
  'M18 8h.01',
  'M6 8h.01',
  'M7 16h10',
  'M8 12h.01',
  'M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2z',
]);

const _languages = DsIconData([
  'm5 8 6 6',
  'm4 14 6-6 2-3',
  'M2 5h12',
  'M7 2h1',
  'm22 22-5-10-5 10',
  'M14 18h6',
]);

const _letters = DsIconData([
  'M15 8H9',
  'M21 15.354a4 4 0 100 5.292',
  'M3 18h4a2 2 0 010 4H3.5a.5.5 0 01-.5-.5v-7a.5.5 0 01.5-.5H6a2 2 0 010 4',
  'm8 10 3.453-7.648a.6.6 0 011.094 0L16 10',
]);

const _libraryBig = DsIconData([
  'M4 3h6a1 1 0 0 1 1 1v16a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-16a1 1 0 0 1 1 -1z',
  'M7 3v18',
  'M20.4 18.9c.2.5-.1 1.1-.6 1.3l-1.9.7c-.5.2-1.1-.1-1.3-.6L11.1 5.1c-.2-.5.1-1.1.6-1.3l1.9-.7c.5-.2 1.1.1 1.3.6Z',
]);

const _library = DsIconData(['m16 6 4 14', 'M12 6v14', 'M8 8v12', 'M4 4v16']);

const _ligatureSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M7 12h3',
  'M14.4 8a3.5 3.5 0 0 0-5.9 2.5V17',
  'M10 17H7',
  'M14 12h1.5v5',
  'M17 17h-3',
]);

const _ligature = DsIconData([
  'M14 12h2v8',
  'M14 20h4',
  'M6 12h4',
  'M6 20h4',
  'M8 20V8a4 4 0 0 1 7.464-2',
]);

const _link2Off = DsIconData([
  'M9 17H7A5 5 0 0 1 7 7',
  'M15 7h2a5 5 0 0 1 4 8',
  'M8 12L12 12',
  'M2 2L22 22',
]);

const _link2 = DsIconData([
  'M9 17H7A5 5 0 0 1 7 7h2',
  'M15 7h2a5 5 0 1 1 0 10h-2',
  'M8 12L16 12',
]);

const _link = DsIconData([
  'M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71',
  'M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71',
]);

const _listCheck = DsIconData([
  'M16 5H3',
  'M16 12H3',
  'M11 19H3',
  'm15 18 2 2 4-4',
]);

const _listChecks = DsIconData([
  'M13 5h8',
  'M13 12h8',
  'M13 19h8',
  'm3 17 2 2 4-4',
  'm3 7 2 2 4-4',
], matchTextDirection: true);

const _listChevronsDownUp = DsIconData([
  'M3 5h8',
  'M3 12h8',
  'M3 19h8',
  'm15 5 3 3 3-3',
  'm15 19 3-3 3 3',
]);

const _listChevronsUpDown = DsIconData([
  'M3 5h8',
  'M3 12h8',
  'M3 19h8',
  'm15 8 3-3 3 3',
  'm15 16 3 3 3-3',
]);

const _listClock = DsIconData([
  'M16 13v2.2l1.6 1',
  'M3 12h3.458',
  'M3 19h3.832',
  'M3 5h18',
  'M10 15a6 6 0 1 0 12 0a6 6 0 1 0 -12 0',
], matchTextDirection: true);

const _listCollapse = DsIconData([
  'M10 5h11',
  'M10 12h11',
  'M10 19h11',
  'm3 10 3-3-3-3',
  'm3 20 3-3-3-3',
]);

const _listFilterPlus = DsIconData([
  'M12 5H2',
  'M6 12h12',
  'M9 19h6',
  'M16 5h6',
  'M19 8V2',
], matchTextDirection: true);

const _listFilter = DsIconData([
  'M2 5h20',
  'M6 12h12',
  'M9 19h6',
], matchTextDirection: true);

const _listIndentDecrease = DsIconData([
  'M21 5H11',
  'M21 12H11',
  'M21 19H11',
  'm7 8-4 4 4 4',
], matchTextDirection: true);

const _listIndentIncrease = DsIconData([
  'M21 5H11',
  'M21 12H11',
  'M21 19H11',
  'm3 8 4 4-4 4',
], matchTextDirection: true);

const _listOrdered = DsIconData([
  'M11 5h10',
  'M11 12h10',
  'M11 19h10',
  'M4 4h1v5',
  'M4 9h2',
  'M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02',
], matchTextDirection: true);

const _listSortAscending = DsIconData(['M3 19h18', 'M15 12H3', 'M9 5H3']);

const _listSortDescending = DsIconData(['M15 12H3', 'M3 5h18', 'M9 19H3']);

const _listTodo = DsIconData([
  'M13 5h8',
  'M13 12h8',
  'M13 19h8',
  'm3 17 2 2 4-4',
  'M4 4h4a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1z',
], matchTextDirection: true);

const _list = DsIconData([
  'M3 5h.01',
  'M3 12h.01',
  'M3 19h.01',
  'M8 5h13',
  'M8 12h13',
  'M8 19h13',
], matchTextDirection: true);

const _logs = DsIconData([
  'M3 5h1',
  'M3 12h1',
  'M3 19h1',
  'M8 5h1',
  'M8 12h1',
  'M8 19h1',
  'M13 5h8',
  'M13 12h8',
  'M13 19h8',
]);

const _mailClock = DsIconData([
  'M16 14v2.2l1.6 1',
  'm22 7-.759.484',
  'M6.835 20H4a2 2 0 01-2-2V6a2 2 0 012-2h16a2 2 0 012 2v2',
  'M7.605 10.567 2 7',
  'M10 16a6 6 0 1 0 12 0a6 6 0 1 0 -12 0',
]);

const _mail = DsIconData([
  'm22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7',
  'M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2z',
]);

const _mapPinSearch = DsIconData([
  'M 12.248 21.969 a 1 1 0 0 1 -0.849 -0.17 C 9.539 20.193 4 14.993 4 10 a 8 8 0 0 1 16 0 C 20 10.42 19.961 10.841 19.888 11.262',
  'm22 22-1.88-1.88',
  'M9 10a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  'M15 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
]);

const _map = DsIconData([
  'M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z',
  'M15 5.764v15',
  'M9 3.236v15',
]);

const _notebookPen = DsIconData([
  'M13.4 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7.4',
  'M2 6h4',
  'M2 10h4',
  'M2 14h4',
  'M2 18h4',
  'M21.378 5.626a1 1 0 1 0-3.004-3.004l-5.01 5.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z',
]);

const _notebookText = DsIconData([
  'M2 6h4',
  'M2 10h4',
  'M2 14h4',
  'M2 18h4',
  'M6 2h12a2 2 0 0 1 2 2v16a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-16a2 2 0 0 1 2 -2z',
  'M9.5 8h5',
  'M9.5 12H16',
  'M9.5 16H14',
]);

const _notebook = DsIconData([
  'M2 6h4',
  'M2 10h4',
  'M2 14h4',
  'M2 18h4',
  'M6 2h12a2 2 0 0 1 2 2v16a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-16a2 2 0 0 1 2 -2z',
  'M16 2v20',
]);

const _notepadTextDashed = DsIconData([
  'M8 2v4',
  'M12 2v4',
  'M16 2v4',
  'M16 4h2a2 2 0 0 1 2 2v2',
  'M20 12v2',
  'M20 18v2a2 2 0 0 1-2 2h-1',
  'M13 22h-2',
  'M7 22H6a2 2 0 0 1-2-2v-2',
  'M4 14v-2',
  'M4 8V6a2 2 0 0 1 2-2h2',
  'M8 10h6',
  'M8 14h8',
  'M8 18h5',
]);

const _notepadText = DsIconData([
  'M8 2v4',
  'M12 2v4',
  'M16 2v4',
  'M6 4h12a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M8 10h6',
  'M8 14h8',
  'M8 18h5',
]);

const _paintRoller = DsIconData([
  'M4 2h12a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-2a2 2 0 0 1 2 -2z',
  'M10 16v-2a2 2 0 0 1 2-2h8a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2',
  'M9 16h2a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1z',
]);

const _paintbrushVertical = DsIconData([
  'M10 2v2',
  'M14 2v4',
  'M17 2a1 1 0 0 1 1 1v9H6V3a1 1 0 0 1 1-1z',
  'M6 12a1 1 0 0 0-1 1v1a2 2 0 0 0 2 2h2a1 1 0 0 1 1 1v2.9a2 2 0 1 0 4 0V17a1 1 0 0 1 1-1h2a2 2 0 0 0 2-2v-1a1 1 0 0 0-1-1',
]);

const _paintbrush = DsIconData([
  'm14.622 17.897-10.68-2.913',
  'M18.376 2.622a1 1 0 1 1 3.002 3.002L17.36 9.643a.5.5 0 0 0 0 .707l.944.944a2.41 2.41 0 0 1 0 3.408l-.944.944a.5.5 0 0 1-.707 0L8.354 7.348a.5.5 0 0 1 0-.707l.944-.944a2.41 2.41 0 0 1 3.408 0l.944.944a.5.5 0 0 0 .707 0z',
  'M9 8c-1.804 2.71-3.97 3.46-6.583 3.948a.507.507 0 0 0-.302.819l7.32 8.883a1 1 0 0 0 1.185.204C12.735 20.405 16 16.792 16 15',
]);

const _palette = DsIconData([
  'M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z',
  'M13 6.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0',
  'M17 10.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0',
  'M6 12.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0',
  'M8 7.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0',
]);

const _paperclip = DsIconData([
  'm16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551',
]);

const _penLine = DsIconData([
  'M13 21h8',
  'M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z',
]);

const _penOff = DsIconData([
  'm10 10-6.157 6.162a2 2 0 0 0-.5.833l-1.322 4.36a.5.5 0 0 0 .622.624l4.358-1.323a2 2 0 0 0 .83-.5L14 13.982',
  'm12.829 7.172 4.359-4.346a1 1 0 1 1 3.986 3.986l-4.353 4.353',
  'm2 2 20 20',
]);

const _penTool = DsIconData([
  'M15.707 21.293a1 1 0 0 1-1.414 0l-1.586-1.586a1 1 0 0 1 0-1.414l5.586-5.586a1 1 0 0 1 1.414 0l1.586 1.586a1 1 0 0 1 0 1.414z',
  'm18 13-1.375-6.874a1 1 0 0 0-.746-.776L3.235 2.028a1 1 0 0 0-1.207 1.207L5.35 15.879a1 1 0 0 0 .776.746L13 18',
  'm2.3 2.3 7.286 7.286',
  'M9 11a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
]);

const _pen = DsIconData([
  'M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z',
]);

const _pencilLine = DsIconData([
  'M13 21h8',
  'm15 5 4 4',
  'M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z',
]);

const _phone = DsIconData([
  'M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384',
]);

const _pilcrowLeft = DsIconData([
  'M14 3v11',
  'M14 9h-3a3 3 0 0 1 0-6h9',
  'M18 3v11',
  'M22 18H2l4-4',
  'm6 22-4-4',
]);

const _pilcrowRight = DsIconData([
  'M10 3v11',
  'M10 9H7a1 1 0 0 1 0-6h8',
  'M14 3v11',
  'm18 14 4 4H2',
  'm22 18-4 4',
]);

const _pilcrow = DsIconData([
  'M13 4v16',
  'M17 4v16',
  'M19 4H9.5a4.5 4.5 0 0 0 0 9H13',
]);

const _pipette = DsIconData([
  'm12 9-8.414 8.414A2 2 0 0 0 3 18.828v1.344a2 2 0 0 1-.586 1.414A2 2 0 0 1 3.828 21h1.344a2 2 0 0 0 1.414-.586L15 12',
  'm18 9 .4.4a1 1 0 1 1-3 3l-3.8-3.8a1 1 0 1 1 3-3l.4.4 3.4-3.4a1 1 0 1 1 3 3z',
  'm2 22 .414-.414',
]);

const _quote = DsIconData([
  'M16 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z',
  'M5 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z',
]);

const _rectangleEllipsis = DsIconData([
  'M4 6h16a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-8a2 2 0 0 1 2 -2z',
  'M12 12h.01',
  'M17 12h.01',
  'M7 12h.01',
]);

const _redo2 = DsIconData([
  'm15 14 5-5-5-5',
  'M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13',
], matchTextDirection: true);

const _redoDot = DsIconData([
  'M11 17a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
  'M21 7v6h-6',
  'M3 17a9 9 0 0 1 9-9 9 9 0 0 1 6 2.3l3 2.7',
], matchTextDirection: true);

const _redo = DsIconData([
  'M21 7v6h-6',
  'M3 17a9 9 0 0 1 9-9 9 9 0 0 1 6 2.3l3 2.7',
], matchTextDirection: true);

const _regex = DsIconData([
  'M17 3v10',
  'm12.67 5.5 8.66 5',
  'm12.67 10.5 8.66-5',
  'M9 17a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-2z',
]);

const _removeFormattingSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M7 9V7h10v2',
  'M13 7 8 17',
  'M7 17h3',
  'm17 14-3 3',
  'm14 14 3 3',
]);

const _removeFormatting = DsIconData([
  'M4 7V4h16v3',
  'M5 20h6',
  'M13 4 8 20',
  'm15 15 5 5',
  'm20 15-5 5',
]);

const _replaceAll = DsIconData([
  'M14 14a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1',
  'M14 4a1 1 0 0 1 1-1',
  'M15 10a1 1 0 0 1-1-1',
  'M19 14a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1',
  'M21 4a1 1 0 0 0-1-1',
  'M21 9a1 1 0 0 1-1 1',
  'm3 7 3 3 3-3',
  'M6 10V5a2 2 0 0 1 2-2h2',
  'M4 14h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z',
]);

const _replace = DsIconData([
  'M14 4a1 1 0 0 1 1-1',
  'M15 10a1 1 0 0 1-1-1',
  'M21 4a1 1 0 0 0-1-1',
  'M21 9a1 1 0 0 1-1 1',
  'm3 7 3 3 3-3',
  'M6 10V5a2 2 0 0 1 2-2h2',
  'M4 14h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z',
]);

const _saveAll = DsIconData([
  'M10 2v3a1 1 0 0 0 1 1h5',
  'M18 18v-6a1 1 0 0 0-1-1h-6a1 1 0 0 0-1 1v6',
  'M18 22H4a2 2 0 0 1-2-2V6',
  'M8 18a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9.172a2 2 0 0 1 1.414.586l2.828 2.828A2 2 0 0 1 22 6.828V16a2 2 0 0 1-2.01 2z',
]);

const _saveCheck = DsIconData([
  'M12.5 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h10.2a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4v4.35',
  'm16 19 2 2 4-4',
  'M17 15.13V14a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7',
  'M7 3v4a1 1 0 0 0 1 1h7',
]);

const _saveOff = DsIconData([
  'M13 13H8a1 1 0 0 0-1 1v7',
  'M14 8h1',
  'M17 21v-4',
  'm2 2 20 20',
  'M20.41 20.41A2 2 0 0 1 19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 .59-1.41',
  'M9 3h6.2a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V15',
]);

const _savePen = DsIconData([
  'M13.33 13H8a1 1 0 00-1 1v7',
  'M14.363 17.634a2 2 0 00-.506.854l-.837 2.87a.5.5 0 00.62.62l2.87-.837a2 2 0 00.854-.506l4.013-4.009a1 1 0 10-3.004-3.004z',
  'M7 3v4a1 1 0 001 1h7',
  'M9 21H5a2 2 0 01-2-2V5a2 2 0 012-2h10.2a2 2 0 011.4.6l3.8 3.8a2 2 0 01.6 1.4v.3',
]);

const _savePlus = DsIconData([
  'M12.5 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h10.2a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V12',
  'M16 13H8a1 1 0 0 0-1 1v7',
  'M19 22v-6',
  'M22 19h-6',
  'M7 3v4a1 1 0 0 0 1 1h7',
]);

const _save = DsIconData([
  'M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z',
  'M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7',
  'M7 3v4a1 1 0 0 0 1 1h7',
]);

const _scanText = DsIconData([
  'M3 7V5a2 2 0 0 1 2-2h2',
  'M17 3h2a2 2 0 0 1 2 2v2',
  'M21 17v2a2 2 0 0 1-2 2h-2',
  'M7 21H5a2 2 0 0 1-2-2v-2',
  'M7 8h8',
  'M7 12h10',
  'M7 16h6',
]);

const _scissors = DsIconData([
  'M3 6a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  'M8.12 8.12 12 12',
  'M20 4 8.12 15.88',
  'M3 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  'M14.8 14.8 20 20',
]);

const _searchAlert = DsIconData([
  'M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0',
  'm21 21-4.3-4.3',
  'M11 7v4',
  'M11 15h.01',
]);

const _searchCheck = DsIconData([
  'm8 11 2 2 4-4',
  'M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0',
  'm21 21-4.3-4.3',
]);

const _searchCode = DsIconData([
  'm13 13.5 2-2.5-2-2.5',
  'm21 21-4.3-4.3',
  'M9 8.5 7 11l2 2.5',
  'M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0',
]);

const _searchSlash = DsIconData([
  'm13.5 8.5-5 5',
  'M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0',
  'm21 21-4.3-4.3',
]);

const _searchX = DsIconData([
  'm13.5 8.5-5 5',
  'm8.5 8.5 5 5',
  'M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0',
  'm21 21-4.3-4.3',
]);

const _search = DsIconData([
  'm21 21-4.34-4.34',
  'M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0',
]);

const _section = DsIconData([
  'M16 5a4 3 0 0 0-8 0c0 4 8 3 8 7a4 3 0 0 1-8 0',
  'M8 19a4 3 0 0 0 8 0c0-4-8-3-8-7a4 3 0 0 1 8 0',
]);

const _separatorHorizontal = DsIconData([
  'm16 16-4 4-4-4',
  'M3 12h18',
  'm8 8 4-4 4 4',
]);

const _separatorVertical = DsIconData([
  'M12 3v18',
  'm16 16 4-4-4-4',
  'm8 8-4 4 4 4',
]);

const _sheet = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M3 9L21 9',
  'M3 15L21 15',
  'M9 9L9 21',
  'M15 9L15 21',
]);

const _sigma = DsIconData([
  'M18 7V5a1 1 0 0 0-1-1H6.5a.5.5 0 0 0-.4.8l4.5 6a2 2 0 0 1 0 2.4l-4.5 6a.5.5 0 0 0 .4.8H17a1 1 0 0 0 1-1v-2',
]);

const _signature = DsIconData([
  'm21 17-2.156-1.868A.5.5 0 0 0 18 15.5v.5a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1c0-2.545-3.991-3.97-8.5-4a1 1 0 0 0 0 5c4.153 0 4.745-11.295 5.708-13.5a2.5 2.5 0 1 1 3.31 3.284',
  'M3 21h18',
]);

const _space = DsIconData(['M22 17v1c0 .5-.5 1-1 1H3c-.5 0-1-.5-1-1v-1']);

const _spellCheck2 = DsIconData([
  'm6 16 6-12 6 12',
  'M8 12h8',
  'M4 21c1.1 0 1.1-1 2.3-1s1.1 1 2.3 1c1.1 0 1.1-1 2.3-1 1.1 0 1.1 1 2.3 1 1.1 0 1.1-1 2.3-1 1.1 0 1.1 1 2.3 1 1.1 0 1.1-1 2.3-1',
]);

const _spellCheck = DsIconData([
  'm20 15-5.5 5.5L12 18',
  'm4 16 6-12 5.115 10.23',
  'M6 12h8',
]);

const _squareAsterisk = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M12 8v8',
  'm8.5 14 7-4',
  'm8.5 10 7 4',
]);

const _squareBottomDashedScissors = DsIconData([
  'M14 21h1',
  'm17 17-2.18-2.18',
  'M5 21a2 2 0 01-2-2V5a2 2 0 012-2h14a2 2 0 012 2v14a2 2 0 01-2 2',
  'M9 21h1',
  'M9.56 14.44 17 7',
  'M9.56 9.56 12 12',
  'M7 15.5a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0',
  'M7 8.5a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0',
]);

const _squareCode = DsIconData([
  'm10 9-3 3 3 3',
  'm14 15 3-3-3-3',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _squareDashedText = DsIconData([
  'M14 21h1',
  'M14 3h1',
  'M19 3a2 2 0 0 1 2 2',
  'M21 14v1',
  'M21 19a2 2 0 0 1-2 2',
  'M21 9v1',
  'M3 14v1',
  'M3 9v1',
  'M5 21a2 2 0 0 1-2-2',
  'M5 3a2 2 0 0 0-2 2',
  'M7 12h10',
  'M7 16h6',
  'M7 8h8',
  'M9 21h1',
  'M9 3h1',
]);

const _squareDashed = DsIconData([
  'M5 3a2 2 0 0 0-2 2',
  'M19 3a2 2 0 0 1 2 2',
  'M21 19a2 2 0 0 1-2 2',
  'M5 21a2 2 0 0 1-2-2',
  'M9 3h1',
  'M9 21h1',
  'M14 3h1',
  'M14 21h1',
  'M3 9v1',
  'M21 9v1',
  'M3 14v1',
  'M21 14v1',
]);

const _squareLibrary = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M7 7v10',
  'M11 7v10',
  'm15 7 2 10',
]);

const _squarePen = DsIconData([
  'M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7',
  'M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z',
]);

const _squarePilcrow = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M12 12H9.5a2.5 2.5 0 0 1 0-5H17',
  'M12 7v10',
  'M16 7v10',
]);

const _squareScissors = DsIconData([
  'm17 17-2.18-2.18',
  'M9.56 14.44 17 7',
  'M9.56 9.56 12 12',
  'M7 15.5a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0',
  'M7 8.5a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _squareSigma = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M16 8.9V7H8l4 5-4 5h8v-1.9',
]);

const _squareStack = DsIconData([
  'M4 10c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h4c1.1 0 2 .9 2 2',
  'M10 16c-1.1 0-2-.9-2-2v-4c0-1.1.9-2 2-2h4c1.1 0 2 .9 2 2',
  'M16 14h4a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2z',
]);

const _squareText = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M7 8h8',
  'M7 12h10',
  'M7 16h6',
]);

const _stickyNoteCheck = DsIconData([
  'm15 19 2 2 4-4',
  'M15 3v5a1 1 0 0 0 1 1h5',
  'M21 13V9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h6.5',
]);

const _stickyNoteMinus = DsIconData([
  'M15 3v5a1 1 0 0 0 1 1h5',
  'M21 14V9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h7.35',
  'M21 18h-6',
]);

const _stickyNoteOff = DsIconData([
  'M15 3v5a1 1 0 0 0 1 1h5',
  'm2 2 20 20',
  'M3.586 3.586A2 2 0 0 0 3 5v14a2 2 0 0 0 2 2h14a2 2 0 0 0 1.414-.586',
  'M8.656 3H15a2.4 2.4 0 0 1 1.706.706l3.588 3.588A2.4 2.4 0 0 1 21 9v6.344',
]);

const _stickyNotePlus = DsIconData([
  'M15 3v5a1 1 0 0 0 1 1h5',
  'M18 15v6',
  'M21 12.356V9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h7.355',
  'M21 18h-6',
]);

const _stickyNoteX = DsIconData([
  'M15 3v5a1 1 0 0 0 1 1h5',
  'm16 16 5 5',
  'M21 12V9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h7',
  'm21 16-5 5',
]);

const _stickyNote = DsIconData([
  'M21 9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2z',
  'M15 3v5a1 1 0 0 0 1 1h5',
]);

const _stickyNotes = DsIconData([
  'M10 8a2.4 2.4 0 0 1 1.706.706l3.588 3.588A2.4 2.4 0 0 1 16 14v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V10a2 2 0 0 1 2-2z',
  'M10 8v5a1 1 0 0 0 1 1h5',
  'M8 4a2 2 0 0 1 2-2h6a2.4 2.4 0 0 1 1.706.706l3.588 3.588A2.4 2.4 0 0 1 22 8v6a2 2 0 0 1-2 2',
  'M16 2v5a1 1 0 0 0 1 1h5',
]);

const _strikethroughSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M10.5 12a2.5 2.5 0 0 1 0-5H15',
  'M7 12h10',
  'M8 17h5.5a2.5 2.5 0 0 0 0-5',
]);

const _strikethrough = DsIconData([
  'M16 4H9a3 3 0 0 0-2.83 4',
  'M14 12a4 4 0 0 1 0 8H6',
  'M4 12L20 12',
]);

const _subscript = DsIconData([
  'm4 5 8 8',
  'm12 5-8 8',
  'M20 19h-4c0-1.5.44-2 1.5-2.5S20 15.33 20 14c0-.47-.17-.93-.48-1.29a2.11 2.11 0 0 0-2.62-.44c-.42.24-.74.62-.9 1.07',
]);

const _summary = DsIconData([
  'M15 4H7',
  'm18 16 3 3-3 3',
  'M3 4v13a2 2 0 0 0 2 2h16',
  'M7 14h7',
  'M7 9h12',
]);

const _superscript = DsIconData([
  'm4 19 8-8',
  'm12 19-8-8',
  'M20 12h-4c0-1.5.442-2 1.5-2.5S20 8.334 20 7.002c0-.472-.17-.93-.484-1.29a2.105 2.105 0 0 0-2.617-.436c-.42.239-.738.614-.899 1.06',
]);

const _table2 = DsIconData([
  'M3 9h18',
  'M9 3v18',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _tableCellsMerge = DsIconData([
  'M12 21v-6',
  'M12 9V3',
  'M3 15h18',
  'M3 9h18',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _tableCellsSplit = DsIconData([
  'M12 15V9',
  'M3 15h18',
  'M3 9h18',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
]);

const _tableColumnsSplit = DsIconData([
  'M14 14v2',
  'M14 20v2',
  'M14 2v2',
  'M14 8v2',
  'M2 15h8',
  'M2 3h6a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H2',
  'M2 9h8',
  'M22 15h-4',
  'M22 3h-2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h2',
  'M22 9h-4',
  'M5 3v18',
]);

const _tableOfContents = DsIconData([
  'M16 5H3',
  'M16 12H3',
  'M16 19H3',
  'M21 5h.01',
  'M21 12h.01',
  'M21 19h.01',
], matchTextDirection: true);

const _tableProperties = DsIconData([
  'M15 3v18',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M21 9H3',
  'M21 15H3',
]);

const _tableRowsSplit = DsIconData([
  'M14 10h2',
  'M15 22v-8',
  'M15 2v4',
  'M2 10h2',
  'M20 10h2',
  'M3 19h18',
  'M3 22v-6a2 2 135 0 1 2-2h14a2 2 45 0 1 2 2v6',
  'M3 2v2a2 2 45 0 0 2 2h14a2 2 135 0 0 2-2V2',
  'M8 10h2',
  'M9 22v-8',
  'M9 2v4',
]);

const _table = DsIconData([
  'M12 3v18',
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M3 9h18',
  'M3 15h18',
]);

const _textAlignCenter = DsIconData(['M21 5H3', 'M17 12H7', 'M19 19H5']);

const _textAlignEnd = DsIconData(['M21 5H3', 'M21 12H9', 'M21 19H7']);

const _textAlignJustifyCenter = DsIconData(['M3 5h18', 'M3 12h18', 'M7 19h10']);

const _textAlignJustifyEnd = DsIconData(['M3 5h18', 'M3 12h18', 'M11 19h10']);

const _textAlignJustifyStart = DsIconData(['M3 5h18', 'M3 12h18', 'M3 19h10']);

const _textAlignJustify = DsIconData(['M3 5h18', 'M3 12h18', 'M3 19h18']);

const _textAlignStart = DsIconData(['M21 5H3', 'M15 12H3', 'M17 19H3']);

const _textCursorInput = DsIconData([
  'M12 20h-1a2 2 0 0 1-2-2 2 2 0 0 1-2 2H6',
  'M13 8h7a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-7',
  'M5 16H4a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h1',
  'M6 4h1a2 2 0 0 1 2 2 2 2 0 0 1 2-2h1',
  'M9 6v12',
]);

const _textCursor = DsIconData([
  'M17 22h-1a4 4 0 0 1-4-4V6a4 4 0 0 1 4-4h1',
  'M7 22h1a4 4 0 0 0 4-4',
  'M7 2h1a4 4 0 0 1 4 4',
]);

const _textInitial = DsIconData([
  'M15 5h6',
  'M15 12h6',
  'M3 19h18',
  'm3 12 3.553-7.724a.5.5 0 0 1 .894 0L11 12',
  'M3.92 10h6.16',
]);

const _textQuote = DsIconData([
  'M17 5H3',
  'M21 12H8',
  'M21 19H8',
  'M3 12v7',
], matchTextDirection: true);

const _textSearch = DsIconData([
  'M21 5H3',
  'M10 12H3',
  'M10 19H3',
  'M14 15a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  'm21 19-1.9-1.9',
]);

const _textSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M7 12h10',
  'M7 16h6',
  'M7 8h8',
]);

const _textWrap = DsIconData([
  'm16 16-3 3 3 3',
  'M3 12h14.5a1 1 0 0 1 0 7H13',
  'M3 19h6',
  'M3 5h18',
]);

const _typeOutline = DsIconData([
  'M14 16.5a.5.5 0 0 0 .5.5h.5a2 2 0 0 1 0 4H9a2 2 0 0 1 0-4h.5a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5V8a2 2 0 0 1-4 0V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v3a2 2 0 0 1-4 0v-.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5Z',
]);

const _typeSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M7 9V7h10v2',
  'M12 7v10',
  'M10 17h4',
]);

const _type = DsIconData([
  'M12 4v16',
  'M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2',
  'M9 20h6',
]);

const _underlineSquare = DsIconData([
  'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
  'M15 7v3a3 3 0 1 1-6 0V7',
  'M7 17h10',
]);

const _underline = DsIconData(['M6 4v6a6 6 0 0 0 12 0V4', 'M4 20L20 20']);

const _undo2 = DsIconData([
  'M9 14 4 9l5-5',
  'M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11',
], matchTextDirection: true);

const _undoDot = DsIconData([
  'M21 17a9 9 0 0 0-15-6.7L3 13',
  'M3 7v6h6',
  'M11 17a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
], matchTextDirection: true);

const _undo = DsIconData([
  'M3 7v6h6',
  'M21 17a9 9 0 0 0-9-9 9 9 0 0 0-6 2.3L3 13',
], matchTextDirection: true);

const _unlink2 = DsIconData([
  'M15 7h2a5 5 0 0 1 0 10h-2m-6 0H7A5 5 0 0 1 7 7h2',
]);

const _unlink = DsIconData([
  'm18.84 12.25 1.72-1.71h-.02a5.004 5.004 0 0 0-.12-7.07 5.006 5.006 0 0 0-6.95 0l-1.72 1.71',
  'm5.17 11.75-1.71 1.71a5.004 5.004 0 0 0 .12 7.07 5.006 5.006 0 0 0 6.95 0l1.71-1.71',
  'M8 2L8 5',
  'M2 8L5 8',
  'M16 19L16 22',
  'M19 16L22 16',
]);

const _wholeWord = DsIconData([
  'M4 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  'M10 9v6',
  'M14 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
  'M14 7v8',
  'M22 17v1c0 .5-.5 1-1 1H3c-.5 0-1-.5-1-1v-1',
]);
