// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';
import '../button/button_style.dart';

/// The look of a `DsCalendar` or `DsRangeCalendar`: the month header, the weekday row and the days. States resolve per day; `selected` is a chosen day or an end of a chosen range (Desen draws it as a solid accent fill whatever the selection style), `disabled` a day that cannot be chosen. Header and grid fields are read unresolved.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsCalendarStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsCalendarStyle with Diagnosticable {
  /// Creates a style.
  const DsCalendarStyle({
    this.daySize,
    this.dayRadius,
    this.dayBackground,
    this.dayForeground,
    this.dayBorderColor,
    this.dayTextStyle,
    this.todayForeground,
    this.todayTextStyle,
    this.todayBorderColor,
    this.outsideForeground,
    this.rangeColor,
    this.rangeEdgeColor,
    this.columnGap,
    this.rowGap,
    this.headerStyle,
    this.headerPadding,
    this.weekdayStyle,
    this.gap,
    this.monthGap,
    this.navButtonStyle,
    this.slideOffset,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
    this.disabled,
  });

  /// Drawn width and height of a day; grows with large text.
  final double? daySize;

  /// Corners of a day. When no layer sets them, rounded as a control of `daySize` (`DsRadii.controlCorners`), so a style that changes only the size keeps them in proportion.
  final BorderRadiusGeometry? dayRadius;

  /// Fill of a day; under `selected`, the solid fill of the chosen day and of both range ends.
  final Color? dayBackground;

  /// Number color of a day.
  final Color? dayForeground;

  /// Inner 1px outline of a day, e.g. the edge of a bright accent fill that melts into the card.
  final Color? dayBorderColor;

  /// Number style, merged (tabular figures).
  final TextStyle? dayTextStyle;

  /// Today's number while it is not selected: the accent text color.
  final Color? todayForeground;

  /// Laid over the number style for today: bold.
  final TextStyle? todayTextStyle;

  /// Inner 1px ring of today while it is not selected, so today is not marked by color alone; Desen uses the accent text color (3:1 off the card, the popup and the range band). A selected today drops it: the fill marks the day.
  final Color? todayBorderColor;

  /// Number color of a shown day of the month before or after.
  final Color? outsideForeground;

  /// Band behind the days of a chosen range, joined from end to end.
  final Color? rangeColor;

  /// Inner 1px line along the top and bottom of the range band, following its rounded ends, and around the filled range ends the band joins, so the outline runs unbroken; none by default.
  final Color? rangeEdgeColor;

  /// Space between days in a week; the tap areas fill it.
  final double? columnGap;

  /// Space between weeks; the tap areas fill it.
  final double? rowGap;

  /// Month and year title style, merged.
  final TextStyle? headerStyle;

  /// Padding around the month header.
  final EdgeInsetsGeometry? headerPadding;

  /// Weekday column header style, merged.
  final TextStyle? weekdayStyle;

  /// Space between the header, the weekday row and the days.
  final double? gap;

  /// Space between two months shown side by side.
  final double? monthGap;

  /// The previous and next month buttons, laid over a ghost small icon button.
  final DsButtonStyle? navButtonStyle;

  /// How far a month slides in when it changes (not under reduced motion).
  final double? slideOffset;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsCalendarStyle? focused;

  /// Laid over the base while hovered.
  final DsCalendarStyle? hovered;

  /// Laid over the base while pressed.
  final DsCalendarStyle? pressed;

  /// Laid over the base while selected.
  final DsCalendarStyle? selected;

  /// Laid over the base while disabled.
  final DsCalendarStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsCalendarStyle merge(DsCalendarStyle? other) {
    if (other == null) return this;
    return DsCalendarStyle(
      daySize: other.daySize ?? daySize,
      dayRadius: other.dayRadius ?? dayRadius,
      dayBackground: other.dayBackground ?? dayBackground,
      dayForeground: other.dayForeground ?? dayForeground,
      dayBorderColor: other.dayBorderColor ?? dayBorderColor,
      dayTextStyle:
          dayTextStyle?.merge(other.dayTextStyle) ?? other.dayTextStyle,
      todayForeground: other.todayForeground ?? todayForeground,
      todayTextStyle:
          todayTextStyle?.merge(other.todayTextStyle) ?? other.todayTextStyle,
      todayBorderColor: other.todayBorderColor ?? todayBorderColor,
      outsideForeground: other.outsideForeground ?? outsideForeground,
      rangeColor: other.rangeColor ?? rangeColor,
      rangeEdgeColor: other.rangeEdgeColor ?? rangeEdgeColor,
      columnGap: other.columnGap ?? columnGap,
      rowGap: other.rowGap ?? rowGap,
      headerStyle: headerStyle?.merge(other.headerStyle) ?? other.headerStyle,
      headerPadding: other.headerPadding ?? headerPadding,
      weekdayStyle:
          weekdayStyle?.merge(other.weekdayStyle) ?? other.weekdayStyle,
      gap: other.gap ?? gap,
      monthGap: other.monthGap ?? monthGap,
      navButtonStyle:
          navButtonStyle?.merge(other.navButtonStyle) ?? other.navButtonStyle,
      slideOffset: other.slideOffset ?? slideOffset,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsCalendarStyle get _base => DsCalendarStyle(
    daySize: daySize,
    dayRadius: dayRadius,
    dayBackground: dayBackground,
    dayForeground: dayForeground,
    dayBorderColor: dayBorderColor,
    dayTextStyle: dayTextStyle,
    todayForeground: todayForeground,
    todayTextStyle: todayTextStyle,
    todayBorderColor: todayBorderColor,
    outsideForeground: outsideForeground,
    rangeColor: rangeColor,
    rangeEdgeColor: rangeEdgeColor,
    columnGap: columnGap,
    rowGap: rowGap,
    headerStyle: headerStyle,
    headerPadding: headerPadding,
    weekdayStyle: weekdayStyle,
    gap: gap,
    monthGap: monthGap,
    navButtonStyle: navButtonStyle,
    slideOffset: slideOffset,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsCalendarStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsCalendarStyle resolveLayers(
    Iterable<DsCalendarStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsCalendarStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    daySize,
    dayRadius,
    dayBackground,
    dayForeground,
    dayBorderColor,
    dayTextStyle,
    todayForeground,
    todayTextStyle,
    todayBorderColor,
    outsideForeground,
    rangeColor,
    rangeEdgeColor,
    columnGap,
    rowGap,
    headerStyle,
    headerPadding,
    weekdayStyle,
    gap,
    monthGap,
    navButtonStyle,
    slideOffset,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsCalendarStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('daySize', daySize, defaultValue: null));
    properties.add(
      DiagnosticsProperty('dayRadius', dayRadius, defaultValue: null),
    );
    properties.add(
      ColorProperty('dayBackground', dayBackground, defaultValue: null),
    );
    properties.add(
      ColorProperty('dayForeground', dayForeground, defaultValue: null),
    );
    properties.add(
      ColorProperty('dayBorderColor', dayBorderColor, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('dayTextStyle', dayTextStyle, defaultValue: null),
    );
    properties.add(
      ColorProperty('todayForeground', todayForeground, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('todayTextStyle', todayTextStyle, defaultValue: null),
    );
    properties.add(
      ColorProperty('todayBorderColor', todayBorderColor, defaultValue: null),
    );
    properties.add(
      ColorProperty('outsideForeground', outsideForeground, defaultValue: null),
    );
    properties.add(ColorProperty('rangeColor', rangeColor, defaultValue: null));
    properties.add(
      ColorProperty('rangeEdgeColor', rangeEdgeColor, defaultValue: null),
    );
    properties.add(DoubleProperty('columnGap', columnGap, defaultValue: null));
    properties.add(DoubleProperty('rowGap', rowGap, defaultValue: null));
    properties.add(
      DiagnosticsProperty('headerStyle', headerStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('headerPadding', headerPadding, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('weekdayStyle', weekdayStyle, defaultValue: null),
    );
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
    properties.add(DoubleProperty('monthGap', monthGap, defaultValue: null));
    properties.add(
      DiagnosticsProperty('navButtonStyle', navButtonStyle, defaultValue: null),
    );
    properties.add(
      DoubleProperty('slideOffset', slideOffset, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsCalendar` in a subtree; see [DsCalendarTheme].
class DsCalendarThemeData extends DsComponentThemeData<DsCalendarThemeData> {
  /// Creates defaults.
  const DsCalendarThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsCalendarStyle? style;

  @override
  DsCalendarThemeData merge(DsCalendarThemeData? other) {
    if (other == null) return this;
    return DsCalendarThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsCalendarThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsCalendarThemeData] to a subtree, merged over any outer one.
class DsCalendarTheme extends DsComponentTheme<DsCalendarThemeData> {
  /// Applies [data] to [child].
  const DsCalendarTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsCalendarThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsCalendarThemeData>(context) ??
      const DsCalendarThemeData();
}
