// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'dart:ui' show ImageFilter;

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsPanel` (side panel or bottom sheet).
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsPanelStyle with Diagnosticable {
  /// Creates a style.
  const DsPanelStyle({
    this.background,
    this.backdropFilter,
    this.shadows,
    this.borderRadius,
    this.padding,
    this.margin,
    this.width,
    this.gap,
    this.titleStyle,
    this.grabberColor,
    this.grabberSize,
    this.sheetMaxWidth,
  });

  /// Fill.
  final Color? background;

  /// Filter for what shows through a translucent fill, e.g. `ImageFilter.blur` for a frosted layer; null filters nothing. Opaque by default.
  final ImageFilter? backdropFilter;

  /// Floating edge and shadow.
  final List<DsShadow>? shadows;

  /// Corners.
  final BorderRadiusGeometry? borderRadius;

  /// Inner padding.
  final EdgeInsetsGeometry? padding;

  /// Space between the panel and the screen edges.
  final EdgeInsetsGeometry? margin;

  /// Side panel width.
  final double? width;

  /// Space between header, body and footer.
  final double? gap;

  /// Title style, merged.
  final TextStyle? titleStyle;

  /// Drag handle of a bottom sheet.
  final Color? grabberColor;

  /// Drag handle size.
  final Size? grabberSize;

  /// Largest width of a bottom sheet.
  final double? sheetMaxWidth;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsPanelStyle merge(DsPanelStyle? other) {
    if (other == null) return this;
    return DsPanelStyle(
      background: other.background ?? background,
      backdropFilter: other.backdropFilter ?? backdropFilter,
      shadows: other.shadows ?? shadows,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      margin: other.margin ?? margin,
      width: other.width ?? width,
      gap: other.gap ?? gap,
      titleStyle: titleStyle?.merge(other.titleStyle) ?? other.titleStyle,
      grabberColor: other.grabberColor ?? grabberColor,
      grabberSize: other.grabberSize ?? grabberSize,
      sheetMaxWidth: other.sheetMaxWidth ?? sheetMaxWidth,
    );
  }

  /// This style; it has no state styles.
  DsPanelStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsPanelStyle resolveLayers(
    Iterable<DsPanelStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsPanelStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    background,
    backdropFilter,
    shadows,
    borderRadius,
    padding,
    margin,
    width,
    gap,
    titleStyle,
    grabberColor,
    grabberSize,
    sheetMaxWidth,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsPanelStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(
      DiagnosticsProperty('backdropFilter', backdropFilter, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('shadows', shadows, defaultValue: null));
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(DiagnosticsProperty('margin', margin, defaultValue: null));
    properties.add(DoubleProperty('width', width, defaultValue: null));
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
    properties.add(
      DiagnosticsProperty('titleStyle', titleStyle, defaultValue: null),
    );
    properties.add(
      ColorProperty('grabberColor', grabberColor, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('grabberSize', grabberSize, defaultValue: null),
    );
    properties.add(
      DoubleProperty('sheetMaxWidth', sheetMaxWidth, defaultValue: null),
    );
  }
}

/// Defaults for every `DsPanel` in a subtree; see [DsPanelTheme].
class DsPanelThemeData extends DsComponentThemeData<DsPanelThemeData> {
  /// Creates defaults.
  const DsPanelThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsPanelStyle? style;

  @override
  DsPanelThemeData merge(DsPanelThemeData? other) {
    if (other == null) return this;
    return DsPanelThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsPanelThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsPanelThemeData] to a subtree, merged over any outer one.
class DsPanelTheme extends DsComponentTheme<DsPanelThemeData> {
  /// Applies [data] to [child].
  const DsPanelTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsPanelThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsPanelThemeData>(context) ??
      const DsPanelThemeData();
}
