// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsChip`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsChipStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsChipStyle with Diagnosticable {
  /// Creates a style.
  const DsChipStyle({
    this.height,
    this.padding,
    this.background,
    this.foreground,
    this.borderColor,
    this.borderRadius,
    this.textStyle,
    this.gap,
    this.iconSize,
    this.showCheck,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
    this.disabled,
  });

  /// Minimum height; grows with large text.
  final double? height;

  /// Inner padding.
  final EdgeInsetsGeometry? padding;

  /// Fill.
  final Color? background;

  /// Label and icon color.
  final Color? foreground;

  /// Inner 1px outline.
  final Color? borderColor;

  /// Corners. When no layer sets them, rounded as a control of `height` (`DsRadii.controlCorners`), so a style that changes only the height keeps them in proportion.
  final BorderRadiusGeometry? borderRadius;

  /// Label text style, merged.
  final TextStyle? textStyle;

  /// Space between icon and label.
  final double? gap;

  /// Leading icon size.
  final double? iconSize;

  /// Whether a selected chip shows a check before its label, in place of its leading icon, so the selection does not rest on color (WCAG 1.4.1).
  final bool? showCheck;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsChipStyle? focused;

  /// Laid over the base while hovered.
  final DsChipStyle? hovered;

  /// Laid over the base while pressed.
  final DsChipStyle? pressed;

  /// Laid over the base while selected.
  final DsChipStyle? selected;

  /// Laid over the base while disabled.
  final DsChipStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsChipStyle merge(DsChipStyle? other) {
    if (other == null) return this;
    return DsChipStyle(
      height: other.height ?? height,
      padding: other.padding ?? padding,
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      borderColor: other.borderColor ?? borderColor,
      borderRadius: other.borderRadius ?? borderRadius,
      textStyle: textStyle?.merge(other.textStyle) ?? other.textStyle,
      gap: other.gap ?? gap,
      iconSize: other.iconSize ?? iconSize,
      showCheck: other.showCheck ?? showCheck,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsChipStyle get _base => DsChipStyle(
    height: height,
    padding: padding,
    background: background,
    foreground: foreground,
    borderColor: borderColor,
    borderRadius: borderRadius,
    textStyle: textStyle,
    gap: gap,
    iconSize: iconSize,
    showCheck: showCheck,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsChipStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsChipStyle resolveLayers(
    Iterable<DsChipStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsChipStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    height,
    padding,
    background,
    foreground,
    borderColor,
    borderRadius,
    textStyle,
    gap,
    iconSize,
    showCheck,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsChipStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(
      ColorProperty('borderColor', borderColor, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('textStyle', textStyle, defaultValue: null),
    );
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(
      DiagnosticsProperty('showCheck', showCheck, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsChip` in a subtree; see [DsChipTheme].
class DsChipThemeData extends DsComponentThemeData<DsChipThemeData> {
  /// Creates defaults.
  const DsChipThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsChipStyle? style;

  @override
  DsChipThemeData merge(DsChipThemeData? other) {
    if (other == null) return this;
    return DsChipThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsChipThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsChipThemeData] to a subtree, merged over any outer one.
class DsChipTheme extends DsComponentTheme<DsChipThemeData> {
  /// Applies [data] to [child].
  const DsChipTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsChipThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsChipThemeData>(context) ??
      const DsChipThemeData();
}
