// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'en.dart';

/// Arabic strings.
class DsLocalizationsAr extends DsLocalizationsEn {
  /// Creates the Arabic strings.
  const DsLocalizationsAr();

  @override
  String get localeName => 'ar';

  @override
  String get close => 'إغلاق';

  @override
  String get cancel => 'إلغاء';

  @override
  String get confirm => 'تأكيد';

  @override
  String get dismiss => 'إغلاق';

  @override
  String get previousPage => 'الصفحة السابقة';

  @override
  String get nextPage => 'الصفحة التالية';

  @override
  String get selectPlaceholder => 'اختر';

  @override
  String get selectNoResults => 'لا توجد نتائج';

  @override
  String selectResultCount(int count) => 'عدد النتائج: $count';

  @override
  String get loading => 'جارٍ التحميل';

  @override
  String percent(int value) => '$value٪';

  @override
  String moreCount(int count) => '$count أخرى';

  @override
  String page(int page) => 'الصفحة $page';

  @override
  String pageOf(int page, int count) => 'الصفحة $page من $count';

  @override
  String get currentPage => 'الصفحة الحالية';

  @override
  String get pagination => 'ترقيم الصفحات';

  @override
  String get breadcrumb => 'مسار التنقل';

  @override
  String get error => 'خطأ';

  @override
  String get warning => 'تحذير';

  @override
  String get success => 'نجاح';

  @override
  String get info => 'معلومات';

  @override
  String get selected => 'محدد';

  @override
  String get notification => 'إشعار';

  @override
  String get dismissNotification => 'إغلاق الإشعار';

  @override
  String get dialog => 'مربع حوار';

  @override
  String get more => 'المزيد';

  @override
  String get required => 'مطلوب';

  @override
  String get increase => 'زيادة';

  @override
  String get decrease => 'إنقاص';

  @override
  String get clear => 'مسح';

  @override
  String get search => 'بحث';

  @override
  String get cut => 'قص';

  @override
  String get copy => 'نسخ';

  @override
  String get paste => 'لصق';

  @override
  String get selectAll => 'تحديد الكل';

  @override
  String get lookUp => 'بحث عن';

  @override
  String get share => 'مشاركة';

  @override
  String get searchWeb => 'البحث في الويب';

  @override
  String get showPassword => 'إظهار كلمة المرور';

  @override
  String get hidePassword => 'إخفاء كلمة المرور';

  @override
  String characterCountLabel(int count, int max) =>
      'عدد الأحرف: $count من $max';

  @override
  String charactersRemaining(int count) => 'الأحرف المتبقية: $count';

  @override
  String charactersOver(int count) => 'عدد الأحرف الزائدة: $count';

  @override
  String remove(String label) => 'إزالة $label';

  @override
  String removed(String label) => 'تمت إزالة $label';

  @override
  String fileUploadPrompt(String browse) => 'أفلت الملفات هنا أو $browse';

  @override
  String get fileUploadBrowse => 'تصفّح';

  @override
  String get fileUploadDrop => 'أفلت الملفات لرفعها';

  @override
  String get uploading => 'جارٍ الرفع';

  @override
  String uploaded(String name) => 'تم رفع $name';

  @override
  String uploadFailed(String name) => 'تعذّر رفع $name';

  @override
  String get uploadError => 'تعذّر الرفع';

  @override
  String cancelUpload(String name) => 'إلغاء رفع $name';

  @override
  String get retry => 'إعادة المحاولة';

  @override
  String get tableSelectRow => 'تحديد الصف';

  @override
  String get tableSelectAll => 'تحديد كل الصفوف';

  @override
  String get sortedAscending => 'مرتب تصاعديًا';

  @override
  String get sortedDescending => 'مرتب تنازليًا';

  @override
  String get tableNoResults => 'لا توجد نتائج';

  @override
  String rowCount(int count) => 'عدد الصفوف: $count';

  @override
  String selectRowNamed(String name) => 'تحديد $name';

  @override
  String get sortBy => 'ترتيب حسب';

  @override
  String monthName(int month) => const [
    'يناير',
    'فبراير',
    'مارس',
    'أبريل',
    'مايو',
    'يونيو',
    'يوليو',
    'أغسطس',
    'سبتمبر',
    'أكتوبر',
    'نوفمبر',
    'ديسمبر',
  ][month - 1];

  @override
  String monthNameInDate(int month) => const [
    'يناير',
    'فبراير',
    'مارس',
    'أبريل',
    'مايو',
    'يونيو',
    'يوليو',
    'أغسطس',
    'سبتمبر',
    'أكتوبر',
    'نوفمبر',
    'ديسمبر',
  ][month - 1];

  @override
  String monthAbbr(int month) => const [
    'يناير',
    'فبراير',
    'مارس',
    'أبريل',
    'مايو',
    'يونيو',
    'يوليو',
    'أغسطس',
    'سبتمبر',
    'أكتوبر',
    'نوفمبر',
    'ديسمبر',
  ][month - 1];

  @override
  String weekdayName(int weekday) => const [
    'الاثنين',
    'الثلاثاء',
    'الأربعاء',
    'الخميس',
    'الجمعة',
    'السبت',
    'الأحد',
  ][weekday - 1];

  @override
  String weekdayAbbr(int weekday) =>
      const ['ن', 'ث', 'ر', 'خ', 'ج', 'س', 'ح'][weekday - 1];

  @override
  String get datePattern => 'd‏/M‏/y';

  @override
  String get dateMediumPattern => 'd MMM y';

  @override
  String get dateFullPattern => 'EEEE، d MMMM y';

  @override
  String get monthYearPattern => 'LLLL y';

  @override
  String get dateHint => 'يوم/شهر/سنة';

  @override
  String get timePattern12 => 'h:mm a';

  @override
  String get am => 'ص';

  @override
  String get pm => 'م';

  @override
  String get previousMonth => 'الشهر السابق';

  @override
  String get nextMonth => 'الشهر التالي';

  @override
  String get chooseDate => 'اختيار التاريخ';

  @override
  String get chooseTime => 'اختيار الوقت';

  @override
  String get today => 'اليوم';

  @override
  String get hours => 'الساعات';

  @override
  String get minutes => 'الدقائق';

  @override
  String get dayPeriod => 'ص/م';

  @override
  String get rangeStart => 'تاريخ البدء';

  @override
  String get rangeEnd => 'تاريخ الانتهاء';

  @override
  String get inRange => 'ضمن النطاق';

  @override
  String invalidDate(String format) => 'أدخل تاريخًا بالتنسيق $format.';

  @override
  String invalidTime(String example) => 'أدخل وقتًا مثل $example.';

  @override
  String get invalidNumber => 'أدخل رقمًا.';

  @override
  String dateTooEarly(String date) => 'أدخل تاريخ $date أو تاريخًا بعده.';

  @override
  String dateTooLate(String date) => 'أدخل تاريخ $date أو تاريخًا قبله.';

  @override
  String get dateUnavailable => 'لا يمكن اختيار هذا التاريخ.';

  @override
  String numberTooSmall(String min) => 'أدخل $min أو أكثر.';

  @override
  String numberTooLarge(String max) => 'أدخل $max أو أقل.';

  @override
  String get fieldRequired => 'هذا الحقل مطلوب.';

  @override
  String textTooShort(int min) => 'الحد الأدنى لعدد الأحرف: $min.';

  @override
  String textTooLong(int max) => 'الحد الأقصى لعدد الأحرف: $max.';

  @override
  String get invalidEmail => 'أدخل عنوان بريد إلكتروني مثل name@example.com.';

  @override
  String useCustom(String text) => 'استخدام «$text»';

  @override
  String retryUpload(String name) => 'إعادة رفع $name';

  @override
  String get presenceOnline => 'متصل';

  @override
  String get presenceAway => 'بعيد';

  @override
  String get presenceBusy => 'مشغول';

  @override
  String get presenceOffline => 'غير متصل';

  @override
  String get breadcrumbMore => 'مستويات أخرى';

  @override
  String get rowActions => 'الإجراءات';

  @override
  String rowActionsFor(String name) => 'إجراءات $name';

  @override
  String get delete => 'حذف';

  @override
  String get scanText => 'مسح النص ضوئيًا';

  @override
  String get editAction => 'إجراء';

  @override
  String get imageUnavailable => 'الصورة غير متوفرة';

  @override
  String tabOf(int index, int count) => 'علامة التبويب $index من $count';

  @override
  String get navigation => 'التنقل';

  @override
  String numberAmbiguous(String grouped, String decimal) =>
      'أدخل $grouped أو $decimal.';

  @override
  String get keyCommand => 'الأوامر';

  @override
  String get keyOption => 'الخيارات';

  @override
  String get keyShift => 'العالي';

  @override
  String get keyControl => 'التحكم';

  @override
  String get keyBackspace => 'مسافة للخلف';

  @override
  String get keyEnter => 'إدخال';

  @override
  String positionOf(int index, int count) => '$index من $count';

  @override
  String get spellingSuggestions => 'اقتراحات الإملاء';

  @override
  String get noSpellingSuggestions => 'لم يتم العثور على بدائل';
}
