// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'en.dart';

/// German strings.
class DsLocalizationsDe extends DsLocalizationsEn {
  /// Creates the German strings.
  const DsLocalizationsDe();

  @override
  String get localeName => 'de';

  @override
  String get close => 'Schließen';

  @override
  String get cancel => 'Abbrechen';

  @override
  String get confirm => 'Bestätigen';

  @override
  String get dismiss => 'Schließen';

  @override
  String get previousPage => 'Vorherige Seite';

  @override
  String get nextPage => 'Nächste Seite';

  @override
  String get selectPlaceholder => 'Auswählen';

  @override
  String get selectNoResults => 'Keine Ergebnisse';

  @override
  String selectResultCount(int count) =>
      count == 1 ? '1 Ergebnis' : '$count Ergebnisse';

  @override
  String get loading => 'Wird geladen';

  @override
  String percent(int value) => '$value\u00A0%';

  @override
  String moreCount(int count) => '$count weitere';

  @override
  String page(int page) => 'Seite $page';

  @override
  String pageOf(int page, int count) => 'Seite $page von $count';

  @override
  String get currentPage => 'Aktuelle Seite';

  @override
  String get pagination => 'Seitennavigation';

  @override
  String get breadcrumb => 'Brotkrümelnavigation';

  @override
  String get error => 'Fehler';

  @override
  String get warning => 'Warnung';

  @override
  String get success => 'Erfolg';

  @override
  String get info => 'Information';

  @override
  String get selected => 'Ausgewählt';

  @override
  String get notification => 'Benachrichtigung';

  @override
  String get dismissNotification => 'Benachrichtigung schließen';

  @override
  String get dialog => 'Dialogfeld';

  @override
  String get more => 'Mehr';

  @override
  String get required => 'Erforderlich';

  @override
  String get increase => 'Erhöhen';

  @override
  String get decrease => 'Verringern';

  @override
  String get clear => 'Löschen';

  @override
  String get search => 'Suchen';

  @override
  String get cut => 'Ausschneiden';

  @override
  String get copy => 'Kopieren';

  @override
  String get paste => 'Einfügen';

  @override
  String get selectAll => 'Alles auswählen';

  @override
  String get lookUp => 'Nachschlagen';

  @override
  String get share => 'Teilen';

  @override
  String get searchWeb => 'Im Web suchen';

  @override
  String get showPassword => 'Passwort anzeigen';

  @override
  String get hidePassword => 'Passwort ausblenden';

  @override
  String characterCountLabel(int count, int max) => '$count von $max Zeichen';

  @override
  String charactersRemaining(int count) =>
      count == 1 ? 'Noch 1 Zeichen' : 'Noch $count Zeichen';

  @override
  String charactersOver(int count) =>
      count == 1 ? '1 Zeichen zu viel' : '$count Zeichen zu viel';

  @override
  String remove(String label) => '$label entfernen';

  @override
  String removed(String label) => '$label entfernt';

  @override
  String fileUploadPrompt(String browse) =>
      'Dateien hierher ziehen oder $browse';

  @override
  String get fileUploadBrowse => 'auswählen';

  @override
  String get fileUploadDrop => 'Zum Hochladen loslassen';

  @override
  String get uploading => 'Wird hochgeladen';

  @override
  String uploaded(String name) => '$name hochgeladen';

  @override
  String uploadFailed(String name) => '$name konnte nicht hochgeladen werden';

  @override
  String get uploadError => 'Hochladen fehlgeschlagen';

  @override
  String cancelUpload(String name) => 'Hochladen von $name abbrechen';

  @override
  String get retry => 'Erneut versuchen';

  @override
  String get tableSelectRow => 'Zeile auswählen';

  @override
  String get tableSelectAll => 'Alle Zeilen auswählen';

  @override
  String get sortedAscending => 'Aufsteigend sortiert';

  @override
  String get sortedDescending => 'Absteigend sortiert';

  @override
  String get tableNoResults => 'Keine Ergebnisse';

  @override
  String rowCount(int count) => count == 1 ? '1 Zeile' : '$count Zeilen';

  @override
  String selectRowNamed(String name) => '$name auswählen';

  @override
  String get sortBy => 'Sortieren nach';

  @override
  String monthName(int month) => const [
    'Januar',
    'Februar',
    'März',
    'April',
    'Mai',
    'Juni',
    'Juli',
    'August',
    'September',
    'Oktober',
    'November',
    'Dezember',
  ][month - 1];

  @override
  String monthNameInDate(int month) => const [
    'Januar',
    'Februar',
    'März',
    'April',
    'Mai',
    'Juni',
    'Juli',
    'August',
    'September',
    'Oktober',
    'November',
    'Dezember',
  ][month - 1];

  @override
  String monthAbbr(int month) => const [
    'Jan.',
    'Feb.',
    'März',
    'Apr.',
    'Mai',
    'Juni',
    'Juli',
    'Aug.',
    'Sept.',
    'Okt.',
    'Nov.',
    'Dez.',
  ][month - 1];

  @override
  String weekdayName(int weekday) => const [
    'Montag',
    'Dienstag',
    'Mittwoch',
    'Donnerstag',
    'Freitag',
    'Samstag',
    'Sonntag',
  ][weekday - 1];

  @override
  String weekdayAbbr(int weekday) =>
      const ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'][weekday - 1];

  @override
  String get datePattern => 'dd.MM.y';

  @override
  String get dateMediumPattern => 'd. MMM y';

  @override
  String get dateFullPattern => 'EEEE, d. MMMM y';

  @override
  String get monthYearPattern => 'LLLL y';

  @override
  String get dateHint => 'TT.MM.JJJJ';

  @override
  String get timePattern12 => 'h:mm a';

  @override
  String get previousMonth => 'Vorheriger Monat';

  @override
  String get nextMonth => 'Nächster Monat';

  @override
  String get chooseDate => 'Datum auswählen';

  @override
  String get chooseTime => 'Uhrzeit auswählen';

  @override
  String get today => 'Heute';

  @override
  String get hours => 'Stunden';

  @override
  String get minutes => 'Minuten';

  @override
  String get rangeStart => 'Startdatum';

  @override
  String get rangeEnd => 'Enddatum';

  @override
  String get inRange => 'Im Zeitraum';

  @override
  String invalidDate(String format) =>
      'Geben Sie ein Datum im Format $format ein.';

  @override
  String invalidTime(String example) =>
      'Geben Sie eine Uhrzeit wie $example ein.';

  @override
  String get invalidNumber => 'Geben Sie eine Zahl ein.';

  @override
  String dateTooEarly(String date) =>
      'Geben Sie den $date oder ein späteres Datum ein.';

  @override
  String dateTooLate(String date) =>
      'Geben Sie den $date oder ein früheres Datum ein.';

  @override
  String get dateUnavailable => 'Dieses Datum kann nicht gewählt werden.';

  @override
  String numberTooSmall(String min) => 'Geben Sie $min oder mehr ein.';

  @override
  String numberTooLarge(String max) => 'Geben Sie $max oder weniger ein.';

  @override
  String get fieldRequired => 'Dieses Feld ist erforderlich.';

  @override
  String textTooShort(int min) => 'Geben Sie mindestens $min Zeichen ein.';

  @override
  String textTooLong(int max) => 'Geben Sie höchstens $max Zeichen ein.';

  @override
  String get invalidEmail =>
      'Geben Sie eine E-Mail-Adresse wie name@example.com ein.';

  @override
  String useCustom(String text) => '„$text“ verwenden';

  @override
  String retryUpload(String name) => 'Hochladen von $name wiederholen';

  @override
  String get presenceOnline => 'Online';

  @override
  String get presenceAway => 'Abwesend';

  @override
  String get presenceBusy => 'Beschäftigt';

  @override
  String get presenceOffline => 'Offline';

  @override
  String get breadcrumbMore => 'Weitere Ebenen';

  @override
  String get rowActions => 'Aktionen';

  @override
  String rowActionsFor(String name) => 'Aktionen für $name';

  @override
  String get delete => 'Löschen';

  @override
  String get scanText => 'Text scannen';

  @override
  String get editAction => 'Aktion';

  @override
  String get imageUnavailable => 'Bild nicht verfügbar';

  @override
  String tabOf(int index, int count) => 'Tab $index von $count';

  @override
  String get navigation => 'Navigation';

  @override
  String numberAmbiguous(String grouped, String decimal) =>
      'Geben Sie $grouped oder $decimal ein.';
}
