// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'en.dart';

/// French strings.
class DsLocalizationsFr extends DsLocalizationsEn {
  /// Creates the French strings.
  const DsLocalizationsFr();

  @override
  String get localeName => 'fr';

  @override
  String get close => 'Fermer';

  @override
  String get cancel => 'Annuler';

  @override
  String get confirm => 'Confirmer';

  @override
  String get dismiss => 'Fermer';

  @override
  String get previousPage => 'Page précédente';

  @override
  String get nextPage => 'Page suivante';

  @override
  String get selectPlaceholder => 'Sélectionner';

  @override
  String get selectNoResults => 'Aucun résultat';

  @override
  String selectResultCount(int count) =>
      count <= 1 ? '$count résultat' : '$count résultats';

  @override
  String get loading => 'Chargement';

  @override
  String percent(int value) => '$value\u202F%';

  @override
  String moreCount(int count) => '$count de plus';

  @override
  String page(int page) => 'Page $page';

  @override
  String pageOf(int page, int count) => 'Page $page sur $count';

  @override
  String get currentPage => 'Page actuelle';

  @override
  String get pagination => 'Pagination';

  @override
  String get breadcrumb => 'Fil d’Ariane';

  @override
  String get error => 'Erreur';

  @override
  String get warning => 'Avertissement';

  @override
  String get success => 'Succès';

  @override
  String get info => 'Information';

  @override
  String get selected => 'Sélectionné';

  @override
  String get notification => 'Notification';

  @override
  String get dismissNotification => 'Fermer la notification';

  @override
  String get dialog => 'Boîte de dialogue';

  @override
  String get more => 'Plus';

  @override
  String get required => 'Obligatoire';

  @override
  String get increase => 'Augmenter';

  @override
  String get decrease => 'Diminuer';

  @override
  String get clear => 'Effacer';

  @override
  String get search => 'Rechercher';

  @override
  String get cut => 'Couper';

  @override
  String get copy => 'Copier';

  @override
  String get paste => 'Coller';

  @override
  String get selectAll => 'Tout sélectionner';

  @override
  String get lookUp => 'Définir';

  @override
  String get share => 'Partager';

  @override
  String get searchWeb => 'Rechercher sur le Web';

  @override
  String get showPassword => 'Afficher le mot de passe';

  @override
  String get hidePassword => 'Masquer le mot de passe';

  @override
  String characterCountLabel(int count, int max) =>
      '$count caractères sur $max';

  @override
  String charactersRemaining(int count) =>
      count <= 1 ? '$count caractère restant' : '$count caractères restants';

  @override
  String charactersOver(int count) =>
      count <= 1 ? '$count caractère en trop' : '$count caractères en trop';

  @override
  String remove(String label) => 'Retirer $label';

  @override
  String removed(String label) => 'Retiré : $label';

  @override
  String fileUploadPrompt(String browse) =>
      'Déposez des fichiers ici ou $browse';

  @override
  String get fileUploadBrowse => 'parcourez';

  @override
  String get fileUploadDrop => 'Déposez pour importer';

  @override
  String get uploading => 'Importation';

  @override
  String uploaded(String name) => '$name importé';

  @override
  String uploadFailed(String name) => "Impossible d'importer $name";

  @override
  String get uploadError => 'Échec de l\'importation';

  @override
  String cancelUpload(String name) => "Annuler l'importation de $name";

  @override
  String get retry => 'Réessayer';

  @override
  String fileSizeUnit(int power) => const ['o', 'ko', 'Mo', 'Go', 'To'][power];

  @override
  String get tableSelectRow => 'Sélectionner la ligne';

  @override
  String get tableSelectAll => 'Sélectionner toutes les lignes';

  @override
  String get sortedAscending => 'Tri croissant';

  @override
  String get sortedDescending => 'Tri décroissant';

  @override
  String get tableNoResults => 'Aucun résultat';

  @override
  String rowCount(int count) => count <= 1 ? '$count ligne' : '$count lignes';

  @override
  String selectRowNamed(String name) => 'Sélectionner $name';

  @override
  String get sortBy => 'Trier par';

  @override
  String monthName(int month) => const [
    'Janvier',
    'Février',
    'Mars',
    'Avril',
    'Mai',
    'Juin',
    'Juillet',
    'Août',
    'Septembre',
    'Octobre',
    'Novembre',
    'Décembre',
  ][month - 1];

  @override
  String monthNameInDate(int month) => const [
    'janvier',
    'février',
    'mars',
    'avril',
    'mai',
    'juin',
    'juillet',
    'août',
    'septembre',
    'octobre',
    'novembre',
    'décembre',
  ][month - 1];

  @override
  String monthAbbr(int month) => const [
    'janv.',
    'févr.',
    'mars',
    'avr.',
    'mai',
    'juin',
    'juil.',
    'août',
    'sept.',
    'oct.',
    'nov.',
    'déc.',
  ][month - 1];

  @override
  String weekdayName(int weekday) => const [
    'lundi',
    'mardi',
    'mercredi',
    'jeudi',
    'vendredi',
    'samedi',
    'dimanche',
  ][weekday - 1];

  @override
  String weekdayAbbr(int weekday) =>
      const ['lu', 'ma', 'me', 'je', 've', 'sa', 'di'][weekday - 1];

  @override
  String get datePattern => 'dd/MM/y';

  @override
  String get dateMediumPattern => 'd MMM y';

  @override
  String get dateFullPattern => 'EEEE d MMMM y';

  @override
  String get monthYearPattern => 'LLLL y';

  @override
  String get dateHint => 'JJ/MM/AAAA';

  @override
  String get timePattern12 => 'h:mm a';

  @override
  String get previousMonth => 'Mois précédent';

  @override
  String get nextMonth => 'Mois suivant';

  @override
  String get chooseDate => 'Choisir une date';

  @override
  String get chooseTime => 'Choisir une heure';

  @override
  String get today => 'Aujourd’hui';

  @override
  String get hours => 'Heures';

  @override
  String get minutes => 'Minutes';

  @override
  String get rangeStart => 'Date de début';

  @override
  String get rangeEnd => 'Date de fin';

  @override
  String get inRange => 'Dans la période';

  @override
  String invalidDate(String format) => 'Saisissez une date au format $format.';

  @override
  String invalidTime(String example) => 'Saisissez une heure comme $example.';

  @override
  String get invalidNumber => 'Saisissez un nombre.';

  @override
  String dateTooEarly(String date) =>
      'Saisissez le $date ou une date ultérieure.';

  @override
  String dateTooLate(String date) =>
      'Saisissez le $date ou une date antérieure.';

  @override
  String get dateUnavailable => 'Cette date ne peut pas être choisie.';

  @override
  String numberTooSmall(String min) => 'Saisissez $min ou plus.';

  @override
  String numberTooLarge(String max) => 'Saisissez $max ou moins.';

  @override
  String get fieldRequired => 'Ce champ est obligatoire.';

  @override
  String textTooShort(int min) => min <= 1
      ? 'Saisissez au moins $min caractère.'
      : 'Saisissez au moins $min caractères.';

  @override
  String textTooLong(int max) => max <= 1
      ? 'Saisissez au plus $max caractère.'
      : 'Saisissez au plus $max caractères.';

  @override
  String get invalidEmail =>
      'Saisissez une adresse e-mail comme name@example.com.';

  @override
  String useCustom(String text) => 'Utiliser « $text »';

  @override
  String retryUpload(String name) => "Réessayer l'importation de $name";

  @override
  String get presenceOnline => 'En ligne';

  @override
  String get presenceAway => 'Absent';

  @override
  String get presenceBusy => 'Occupé';

  @override
  String get presenceOffline => 'Hors ligne';

  @override
  String get breadcrumbMore => 'Autres niveaux';

  @override
  String get rowActions => 'Actions';

  @override
  String rowActionsFor(String name) => 'Actions pour $name';

  @override
  String get delete => 'Supprimer';

  @override
  String get scanText => 'Scanner du texte';

  @override
  String get editAction => 'Action';

  @override
  String get imageUnavailable => 'Image indisponible';

  @override
  String tabOf(int index, int count) => 'Onglet $index sur $count';

  @override
  String get navigation => 'Navigation';

  @override
  String get keyCommand => 'Commande';

  @override
  String get keyOption => 'Option';

  @override
  String get keyShift => 'Maj';

  @override
  String get keyControl => 'Contrôle';

  @override
  String get keyBackspace => 'Retour arrière';

  @override
  String get keyEnter => 'Entrée';

  @override
  String positionOf(int index, int count) => '$index sur $count';
}
