// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'en.dart';

/// Hindi strings.
class DsLocalizationsHi extends DsLocalizationsEn {
  /// Creates the Hindi strings.
  const DsLocalizationsHi();

  @override
  String get localeName => 'hi';

  @override
  String get close => 'बंद करें';

  @override
  String get cancel => 'रद्द करें';

  @override
  String get confirm => 'पुष्टि करें';

  @override
  String get dismiss => 'खारिज करें';

  @override
  String get previousPage => 'पिछला पृष्ठ';

  @override
  String get nextPage => 'अगला पृष्ठ';

  @override
  String get selectPlaceholder => 'चुनें';

  @override
  String get selectNoResults => 'कोई परिणाम नहीं';

  @override
  String selectResultCount(int count) => '$count परिणाम';

  @override
  String get loading => 'लोड हो रहा है';

  @override
  String moreCount(int count) => '$count और';

  @override
  String page(int page) => 'पृष्ठ $page';

  @override
  String pageOf(int page, int count) => '$count में से पृष्ठ $page';

  @override
  String get currentPage => 'वर्तमान पृष्ठ';

  @override
  String get pagination => 'पृष्ठांकन';

  @override
  String get breadcrumb => 'नेविगेशन पथ';

  @override
  String get error => 'त्रुटि';

  @override
  String get warning => 'चेतावनी';

  @override
  String get success => 'सफल';

  @override
  String get info => 'जानकारी';

  @override
  String get selected => 'चयनित';

  @override
  String get notification => 'सूचना';

  @override
  String get dismissNotification => 'सूचना खारिज करें';

  @override
  String get dialog => 'संवाद';

  @override
  String get more => 'और';

  @override
  String get required => 'आवश्यक';

  @override
  String get increase => 'बढ़ाएँ';

  @override
  String get decrease => 'घटाएँ';

  @override
  String get clear => 'साफ़ करें';

  @override
  String get search => 'खोजें';

  @override
  String get cut => 'काटें';

  @override
  String get copy => 'कॉपी करें';

  @override
  String get paste => 'चिपकाएँ';

  @override
  String get selectAll => 'सभी चुनें';

  @override
  String get lookUp => 'लुक अप करें';

  @override
  String get share => 'शेयर करें';

  @override
  String get searchWeb => 'वेब पर खोजें';

  @override
  String get showPassword => 'पासवर्ड दिखाएँ';

  @override
  String get hidePassword => 'पासवर्ड छिपाएँ';

  @override
  String characterCountLabel(int count, int max) => '$max में से $count वर्ण';

  @override
  String charactersRemaining(int count) => '$count वर्ण शेष';

  @override
  String charactersOver(int count) => '$count वर्ण अधिक';

  @override
  String remove(String label) => '$label हटाएँ';

  @override
  String removed(String label) => '$label हटाया गया';

  @override
  String fileUploadPrompt(String browse) => 'फ़ाइलें यहाँ छोड़ें या $browse';

  @override
  String get fileUploadBrowse => 'ब्राउज़ करें';

  @override
  String get fileUploadDrop => 'अपलोड करने के लिए छोड़ें';

  @override
  String get uploading => 'अपलोड हो रहा है';

  @override
  String uploaded(String name) => '$name अपलोड हो गई';

  @override
  String uploadFailed(String name) => '$name अपलोड नहीं हो सकी';

  @override
  String get uploadError => 'अपलोड विफल';

  @override
  String cancelUpload(String name) => '$name का अपलोड रद्द करें';

  @override
  String get retry => 'फिर से कोशिश करें';

  @override
  String get tableSelectRow => 'पंक्ति चुनें';

  @override
  String get tableSelectAll => 'सभी पंक्तियाँ चुनें';

  @override
  String get sortedAscending => 'आरोही क्रम में';

  @override
  String get sortedDescending => 'अवरोही क्रम में';

  @override
  String get tableNoResults => 'कोई परिणाम नहीं';

  @override
  String rowCount(int count) => '$count पंक्तियाँ';

  @override
  String selectRowNamed(String name) => '$name चुनें';

  @override
  String get sortBy => 'इसके अनुसार क्रमबद्ध करें';

  @override
  String monthName(int month) => const [
    'जनवरी',
    'फ़रवरी',
    'मार्च',
    'अप्रैल',
    'मई',
    'जून',
    'जुलाई',
    'अगस्त',
    'सितंबर',
    'अक्तूबर',
    'नवंबर',
    'दिसंबर',
  ][month - 1];

  @override
  String monthNameInDate(int month) => const [
    'जनवरी',
    'फ़रवरी',
    'मार्च',
    'अप्रैल',
    'मई',
    'जून',
    'जुलाई',
    'अगस्त',
    'सितंबर',
    'अक्तूबर',
    'नवंबर',
    'दिसंबर',
  ][month - 1];

  @override
  String monthAbbr(int month) => const [
    'जन॰',
    'फ़र॰',
    'मार्च',
    'अप्रैल',
    'मई',
    'जून',
    'जुल॰',
    'अग॰',
    'सित॰',
    'अक्तू॰',
    'नव॰',
    'दिस॰',
  ][month - 1];

  @override
  String weekdayName(int weekday) => const [
    'सोमवार',
    'मंगलवार',
    'बुधवार',
    'गुरुवार',
    'शुक्रवार',
    'शनिवार',
    'रविवार',
  ][weekday - 1];

  @override
  String weekdayAbbr(int weekday) =>
      const ['सो', 'मं', 'बु', 'गु', 'शु', 'श', 'र'][weekday - 1];

  @override
  String get datePattern => 'd/M/y';

  @override
  String get dateMediumPattern => 'd MMM y';

  @override
  String get dateFullPattern => 'EEEE, d MMMM y';

  @override
  String get monthYearPattern => 'LLLL y';

  @override
  String get dateHint => 'DD/MM/YYYY';

  @override
  String get timePattern12 => 'h:mm a';

  @override
  String get am => 'am';

  @override
  String get pm => 'pm';

  @override
  String get previousMonth => 'पिछला महीना';

  @override
  String get nextMonth => 'अगला महीना';

  @override
  String get chooseDate => 'तारीख चुनें';

  @override
  String get chooseTime => 'समय चुनें';

  @override
  String get today => 'आज';

  @override
  String get hours => 'घंटे';

  @override
  String get minutes => 'मिनट';

  @override
  String get dayPeriod => 'am/pm';

  @override
  String get rangeStart => 'आरंभ तिथि';

  @override
  String get rangeEnd => 'समाप्ति तिथि';

  @override
  String get inRange => 'सीमा में';

  @override
  String invalidDate(String format) => 'तारीख $format प्रारूप में दर्ज करें।';

  @override
  String invalidTime(String example) => 'समय $example की तरह दर्ज करें।';

  @override
  String get invalidNumber => 'कोई संख्या दर्ज करें।';

  @override
  String dateTooEarly(String date) => '$date या उसके बाद की तारीख दर्ज करें।';

  @override
  String dateTooLate(String date) => '$date या उससे पहले की तारीख दर्ज करें।';

  @override
  String get dateUnavailable => 'यह तारीख नहीं चुनी जा सकती।';

  @override
  String numberTooSmall(String min) => '$min या उससे अधिक दर्ज करें।';

  @override
  String numberTooLarge(String max) => '$max या उससे कम दर्ज करें।';

  @override
  String get seconds => 'सेकंड';

  @override
  String get unavailable => 'उपलब्ध नहीं';

  @override
  String timeTooEarly(String time) => '$time या उसके बाद का समय दर्ज करें।';

  @override
  String timeTooLate(String time) => '$time या उससे पहले का समय दर्ज करें।';

  @override
  String timeOutsideRange(String first, String last) =>
      '$first से $last तक का समय दर्ज करें।';

  @override
  String get fieldRequired => 'यह फ़ील्ड आवश्यक है।';

  @override
  String textTooShort(int min) => 'कम से कम $min वर्ण दर्ज करें।';

  @override
  String textTooLong(int max) => 'अधिकतम $max वर्ण दर्ज करें।';

  @override
  String get invalidEmail => 'name@example.com जैसा ईमेल पता दर्ज करें।';

  @override
  String useCustom(String text) => '“$text” का उपयोग करें';

  @override
  String retryUpload(String name) => '$name को फिर से अपलोड करें';

  @override
  String get presenceOnline => 'ऑनलाइन';

  @override
  String get presenceAway => 'दूर';

  @override
  String get presenceBusy => 'व्यस्त';

  @override
  String get presenceOffline => 'ऑफ़लाइन';

  @override
  String get breadcrumbMore => 'और स्तर';

  @override
  String get rowActions => 'कार्रवाइयाँ';

  @override
  String rowActionsFor(String name) => '$name के लिए कार्रवाइयाँ';

  @override
  String get delete => 'मिटाएँ';

  @override
  String get scanText => 'टेक्स्ट स्कैन करें';

  @override
  String get editAction => 'कार्रवाई';

  @override
  String get imageUnavailable => 'छवि उपलब्ध नहीं';

  @override
  String tabOf(int index, int count) => '$count में से टैब $index';

  @override
  String get navigation => 'नेविगेशन';

  @override
  String numberAmbiguous(String grouped, String decimal) =>
      '$grouped या $decimal दर्ज करें।';

  @override
  String get keyCommand => 'कमांड';

  @override
  String get keyOption => 'ऑप्शन';

  @override
  String get keyShift => 'शिफ़्ट';

  @override
  String get keyControl => 'कंट्रोल';

  @override
  String get keyBackspace => 'बैकस्पेस';

  @override
  String get keyEnter => 'एंटर';

  @override
  String positionOf(int index, int count) => '$count में से $index';

  @override
  String get spellingSuggestions => 'वर्तनी सुझाव';

  @override
  String get noSpellingSuggestions => 'कोई विकल्प नहीं मिला';

  @override
  String get rangeMinimum => 'न्यूनतम';

  @override
  String get rangeMaximum => 'अधिकतम';

  @override
  String get moreActions => 'और कार्रवाइयाँ';

  @override
  String get showMenu => 'मेन्यू दिखाएं';

  @override
  String get opensExternally => 'ऐप के बाहर खुलता है';
}
