// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'en.dart';

/// Japanese strings.
class DsLocalizationsJa extends DsLocalizationsEn {
  /// Creates the Japanese strings.
  const DsLocalizationsJa();

  @override
  String get localeName => 'ja';

  @override
  String get close => '閉じる';

  @override
  String get cancel => 'キャンセル';

  @override
  String get confirm => '確認';

  @override
  String get dismiss => '閉じる';

  @override
  String get previousPage => '前のページ';

  @override
  String get nextPage => '次のページ';

  @override
  String get selectPlaceholder => '選択';

  @override
  String get selectNoResults => '結果なし';

  @override
  String selectResultCount(int count) => '$count 件の結果';

  @override
  String get loading => '読み込み中';

  @override
  String moreCount(int count) => '他 $count 件';

  @override
  String page(int page) => '$page ページ';

  @override
  String pageOf(int page, int count) => '$count ページ中 $page ページ';

  @override
  String get currentPage => '現在のページ';

  @override
  String get pagination => 'ページ送り';

  @override
  String get breadcrumb => 'パンくずリスト';

  @override
  String get error => 'エラー';

  @override
  String get warning => '警告';

  @override
  String get success => '成功';

  @override
  String get info => '情報';

  @override
  String get selected => '選択済み';

  @override
  String get notification => '通知';

  @override
  String get dismissNotification => '通知を閉じる';

  @override
  String get dialog => 'ダイアログ';

  @override
  String get more => 'その他';

  @override
  String get required => '必須';

  @override
  String get increase => '増やす';

  @override
  String get decrease => '減らす';

  @override
  String get clear => 'クリア';

  @override
  String get search => '検索';

  @override
  String get cut => '切り取り';

  @override
  String get copy => 'コピー';

  @override
  String get paste => 'ペースト';

  @override
  String get selectAll => 'すべてを選択';

  @override
  String get lookUp => '調べる';

  @override
  String get share => '共有';

  @override
  String get searchWeb => 'Web を検索';

  @override
  String get showPassword => 'パスワードを表示';

  @override
  String get hidePassword => 'パスワードを非表示';

  @override
  String characterCountLabel(int count, int max) => '$max 文字中 $count 文字';

  @override
  String charactersRemaining(int count) => '残り $count 文字';

  @override
  String charactersOver(int count) => '$count 文字超過';

  @override
  String remove(String label) => '$label を削除';

  @override
  String removed(String label) => '$label を削除しました';

  @override
  String fileUploadPrompt(String browse) => 'ここにファイルをドロップするか、$browse';

  @override
  String get fileUploadBrowse => 'ファイルを選択';

  @override
  String get fileUploadDrop => 'ドロップしてアップロード';

  @override
  String get uploading => 'アップロード中';

  @override
  String uploaded(String name) => '$name をアップロードしました';

  @override
  String uploadFailed(String name) => '$name をアップロードできませんでした';

  @override
  String get uploadError => 'アップロードに失敗しました';

  @override
  String cancelUpload(String name) => '$name のアップロードをキャンセル';

  @override
  String get retry => '再試行';

  @override
  String get tableSelectRow => '行を選択';

  @override
  String get tableSelectAll => 'すべての行を選択';

  @override
  String get sortedAscending => '昇順で並べ替え済み';

  @override
  String get sortedDescending => '降順で並べ替え済み';

  @override
  String get tableNoResults => '結果なし';

  @override
  String rowCount(int count) => '$count 行';

  @override
  String selectRowNamed(String name) => '$name を選択';

  @override
  String get sortBy => '並べ替え';

  @override
  String monthName(int month) => const [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ][month - 1];

  @override
  String monthNameInDate(int month) => const [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ][month - 1];

  @override
  String monthAbbr(int month) => const [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ][month - 1];

  @override
  String weekdayName(int weekday) =>
      const ['月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日', '日曜日'][weekday - 1];

  @override
  String weekdayAbbr(int weekday) =>
      const ['月', '火', '水', '木', '金', '土', '日'][weekday - 1];

  @override
  String get datePattern => 'y/MM/dd';

  @override
  String get dateMediumPattern => 'y年M月d日';

  @override
  String get dateFullPattern => 'y年M月d日EEEE';

  @override
  String get monthYearPattern => 'y年M月';

  @override
  String get dateHint => 'YYYY/MM/DD';

  @override
  String get timePattern12 => 'ah:mm';

  @override
  String get am => '午前';

  @override
  String get pm => '午後';

  @override
  String get previousMonth => '前の月';

  @override
  String get nextMonth => '次の月';

  @override
  String get chooseDate => '日付を選択';

  @override
  String get chooseTime => '時刻を選択';

  @override
  String get today => '今日';

  @override
  String get hours => '時';

  @override
  String get minutes => '分';

  @override
  String get dayPeriod => '午前/午後';

  @override
  String get rangeStart => '開始日';

  @override
  String get rangeEnd => '終了日';

  @override
  String get inRange => '期間内';

  @override
  String invalidDate(String format) => '日付を $format の形式で入力してください。';

  @override
  String invalidTime(String example) => '時刻を $example のように入力してください。';

  @override
  String get invalidNumber => '数値を入力してください。';

  @override
  String dateTooEarly(String date) => '$date 以降の日付を入力してください。';

  @override
  String dateTooLate(String date) => '$date 以前の日付を入力してください。';

  @override
  String get dateUnavailable => 'この日付は選択できません。';

  @override
  String numberTooSmall(String min) => '$min 以上の数値を入力してください。';

  @override
  String numberTooLarge(String max) => '$max 以下の数値を入力してください。';

  @override
  String get seconds => '秒';

  @override
  String get unavailable => '選択不可';

  @override
  String timeTooEarly(String time) => '$time 以降の時刻を入力してください。';

  @override
  String timeTooLate(String time) => '$time 以前の時刻を入力してください。';

  @override
  String get fieldRequired => 'この項目は必須です。';

  @override
  String textTooShort(int min) => '$min 文字以上で入力してください。';

  @override
  String textTooLong(int max) => '$max 文字以内で入力してください。';

  @override
  String get invalidEmail => 'name@example.com のようなメールアドレスを入力してください。';

  @override
  String useCustom(String text) => '「$text」を使用';

  @override
  String retryUpload(String name) => '$name のアップロードを再試行';

  @override
  String get presenceOnline => 'オンライン';

  @override
  String get presenceAway => '退席中';

  @override
  String get presenceBusy => '取り込み中';

  @override
  String get presenceOffline => 'オフライン';

  @override
  String get breadcrumbMore => 'その他の階層';

  @override
  String get rowActions => '操作';

  @override
  String rowActionsFor(String name) => '$name の操作';

  @override
  String get delete => '削除';

  @override
  String get scanText => 'テキストをスキャン';

  @override
  String get editAction => '操作';

  @override
  String get imageUnavailable => '画像を読み込めません';

  @override
  String tabOf(int index, int count) => 'タブ: $index/$count';

  @override
  String get navigation => 'ナビゲーション';

  @override
  String numberAmbiguous(String grouped, String decimal) =>
      '$grouped または $decimal と入力してください。';

  @override
  String get keyCommand => 'コマンド';

  @override
  String get keyOption => 'オプション';

  @override
  String get keyShift => 'シフト';

  @override
  String get keyControl => 'コントロール';

  @override
  String get keyBackspace => 'バックスペース';

  @override
  String get keyEnter => 'エンター';

  @override
  String positionOf(int index, int count) => '$index/$count';
}
