// GENERATED by tool/gen_l10n.py. Do not edit by hand.

part of '../localizations.dart';

/// The strings every language provides.
mixin _DsStrings {
  /// Closes a dialog, panel or popover.
  String get close;

  /// Dismisses a dialog without acting.
  String get cancel;

  /// Confirms a dialog.
  String get confirm;

  /// Removes a notification.
  String get dismiss;

  /// Pagination: the previous page.
  String get previousPage;

  /// Pagination: the next page.
  String get nextPage;

  /// A select with nothing chosen.
  String get selectPlaceholder;

  /// A search that matches no option.
  String get selectNoResults;

  /// Announces how many options match a search.
  String selectResultCount(int count);

  /// Announces that content or an action is loading.
  String get loading;

  /// A percentage, written the local way ("40%", "%40", "40 %").
  String percent(int value);

  /// Announces items hidden behind a "+N" overflow, e.g. in an avatar group.
  String moreCount(int count);

  /// The visible "+N" of hidden items.
  String overflowCount(int count);

  /// A count capped at max, e.g. "99+" on a badge.
  String countOverflow(int max);

  /// Pagination: a page button.
  String page(int page);

  /// Pagination: the current position.
  String pageOf(int page, int count);

  /// Pagination: marks the current page.
  String get currentPage;

  /// Names a pagination control.
  String get pagination;

  /// Names a breadcrumb trail.
  String get breadcrumb;

  /// A field or status in error.
  String get error;

  /// A warning status.
  String get warning;

  /// A success status.
  String get success;

  /// An informational status.
  String get info;

  /// Announces a selected item.
  String get selected;

  /// Names a notification (toast).
  String get notification;

  /// Closes a notification.
  String get dismissNotification;

  /// Names a dialog that has no title.
  String get dialog;

  /// Opens more actions, e.g. an overflow menu.
  String get more;

  /// Marks a required field.
  String get required;

  /// Increases a value, e.g. a stepper.
  String get increase;

  /// Decreases a value, e.g. a stepper.
  String get decrease;

  /// Clears a field or a selection.
  String get clear;

  /// Names a search field or action.
  String get search;

  /// Edit menu: cuts the selected text.
  String get cut;

  /// Edit menu: copies the selected text.
  String get copy;

  /// Edit menu: pastes the clipboard.
  String get paste;

  /// Edit menu: selects all text.
  String get selectAll;

  /// Edit menu: looks the selected word up.
  String get lookUp;

  /// Edit menu: shares the selected text.
  String get share;

  /// Edit menu: searches the web for the selected text.
  String get searchWeb;

  /// Reveals a password field's text.
  String get showPassword;

  /// Hides a revealed password again.
  String get hidePassword;

  /// A text field's visible counter, e.g. "12 / 100".
  String characterCount(int count, int max);

  /// The counter as screen readers hear it, e.g. "12 of 100 characters".
  String characterCountLabel(int count, int max);

  /// Announces how many characters can still be typed.
  String charactersRemaining(int count);

  /// How many characters are over a soft limit, e.g. "14 characters too many".
  String charactersOver(int count);

  /// Removes one chosen value, e.g. the remove button of a tag ("Remove Ayşe").
  String remove(String label);

  /// Announces that a chosen value was removed, e.g. a tag by Backspace.
  String removed(String label);

  /// A file drop zone's prompt; browse is fileUploadBrowse, shown as a link.
  String fileUploadPrompt(String browse);

  /// The "browse" word inside fileUploadPrompt.
  String get fileUploadBrowse;

  /// A file drop zone while files are dragged over it.
  String get fileUploadDrop;

  /// A file that is uploading.
  String get uploading;

  /// Announces a finished upload.
  String uploaded(String name);

  /// Announces a failed upload.
  String uploadFailed(String name);

  /// A failed upload's message when the app gives none.
  String get uploadError;

  /// Stops one file's upload.
  String cancelUpload(String name);

  /// Tries a failed action again, e.g. an upload.
  String get retry;

  /// How much of a file is uploaded, e.g. "2,4 / 3,1 MB".
  String fileProgress(String loaded, String total);

  /// The unit of a file size: power 0 is bytes, 1 kilobytes (1000 bytes), up to 4 terabytes.
  String fileSizeUnit(int power);

  /// Table: the checkbox that selects one row.
  String get tableSelectRow;

  /// Table: the header checkbox that selects every row.
  String get tableSelectAll;

  /// Table: a column header sorted from low to high.
  String get sortedAscending;

  /// Table: a column header sorted from high to low.
  String get sortedDescending;

  /// Table: there are no rows to show.
  String get tableNoResults;

  /// Table: how many rows it holds, also those scrolled out of view.
  String rowCount(int count);

  /// Table: the checkbox that selects one row, named by the row's first cell ("Select Kuzey Lojistik").
  String selectRowNamed(String name);

  /// Table in the card layout: the label before the sort buttons.
  String get sortBy;

  /// A month on its own, e.g. a calendar header ("October"); month is 1-12.
  String monthName(int month);

  /// A month inside a date ("5 October 2026"): Russian takes the genitive, French and Spanish lowercase.
  String monthNameInDate(int month);

  /// A short month inside a date ("Oct").
  String monthAbbr(int month);

  /// A weekday ("Monday"); weekday is 1 (Monday) to 7 (Sunday), as DateTime.weekday.
  String weekdayName(int weekday);

  /// A calendar column header ("Mo").
  String weekdayAbbr(int weekday);

  /// The numeric date a date field shows and reads, in DsDateFormat letters.
  String get datePattern;

  /// A date with a short month name ("Oct 5, 2026").
  String get dateMediumPattern;

  /// A date as screen readers hear it ("Monday, October 5, 2026").
  String get dateFullPattern;

  /// A calendar header ("October 2026").
  String get monthYearPattern;

  /// The placeholder of an empty date field, showing the order to type.
  String get dateHint;

  /// A 12-hour time ("3:05 PM"); 24-hour time is HH:mm everywhere.
  String get timePattern12;

  /// Before noon in a 12-hour time.
  String get am;

  /// After noon in a 12-hour time.
  String get pm;

  /// Calendar: shows the previous month.
  String get previousMonth;

  /// Calendar: shows the next month.
  String get nextMonth;

  /// Opens a calendar to choose a date.
  String get chooseDate;

  /// Opens a list to choose a time.
  String get chooseTime;

  /// Marks today in a calendar.
  String get today;

  /// Names the hour column of a time picker.
  String get hours;

  /// Names the minute column of a time picker.
  String get minutes;

  /// Names the AM/PM column of a time picker.
  String get dayPeriod;

  /// Marks the first day of a chosen date range.
  String get rangeStart;

  /// Marks the last day of a chosen date range.
  String get rangeEnd;

  /// Marks a day inside a chosen date range.
  String get inRange;

  /// A date field holds text that is not a date; format is its hint ("MM/DD/YYYY").
  String invalidDate(String format);

  /// A time field holds text that is not a time; example is a time in its clock ("2:30 PM").
  String invalidTime(String example);

  /// A number field holds text that is not a number.
  String get invalidNumber;

  /// A typed date is before the first one that can be chosen.
  String dateTooEarly(String date);

  /// A typed date is after the last one that can be chosen.
  String dateTooLate(String date);

  /// A typed date is in range but cannot be chosen.
  String get dateUnavailable;

  /// A typed number is under the minimum.
  String numberTooSmall(String min);

  /// A typed number is over the maximum.
  String numberTooLarge(String max);

  /// Names the seconds column of a time picker.
  String get seconds;

  /// Follows a value that cannot be chosen, e.g. a time outside a picker's limits.
  String get unavailable;

  /// A typed time is before the first one that can be chosen.
  String timeTooEarly(String time);

  /// A typed time is after the last one that can be chosen.
  String timeTooLate(String time);

  /// A typed time is outside a time picker's range across midnight, from `first` to `last`.
  String timeOutsideRange(String first, String last);

  /// A required form field is empty (DsValidators.required).
  String get fieldRequired;

  /// A text is shorter than its minimum length, in characters.
  String textTooShort(int min);

  /// A text is longer than its maximum length, in characters.
  String textTooLong(int max);

  /// A text is not an email address (DsValidators.email).
  String get invalidEmail;

  /// Offers typed text that matches no option as the value, in an autocomplete that takes free text.
  String useCustom(String text);

  /// Uploads one failed file again.
  String retryUpload(String name);

  /// An avatar status: the person is online.
  String get presenceOnline;

  /// An avatar status: the person is away.
  String get presenceAway;

  /// An avatar status: the person is busy (do not disturb).
  String get presenceBusy;

  /// An avatar status: the person is offline.
  String get presenceOffline;

  /// Breadcrumb: the "…" button listing the levels collapsed to fit.
  String get breadcrumbMore;

  /// Table: names the column of row action buttons.
  String get rowActions;

  /// Table: a row's actions button, with the row's name.
  String rowActionsFor(String name);

  /// Pagination: the compact pager's visible position, e.g. "3 / 10".
  String pageCounter(int page, int count);

  /// Edit menu: deletes the selected text.
  String get delete;

  /// Edit menu: Live Text, types in text the camera reads.
  String get scanText;

  /// Edit menu: an app's own action that came without a label.
  String get editAction;

  /// An image that could not be loaded.
  String get imageUnavailable;

  /// A tab's position, announced after its name ("Home, Tab 2 of 4"); index counts from 1.
  String tabOf(int index, int count);

  /// Names a navigation bar, e.g. the bottom navigation.
  String get navigation;

  /// A typed number reads two ways; grouped and decimal are both readings, already formatted.
  String numberAmbiguous(String grouped, String decimal);

  /// A shortcut's ⌘ key, as screen readers hear it.
  String get keyCommand;

  /// A shortcut's ⌥ key, as screen readers hear it.
  String get keyOption;

  /// A shortcut's ⇧ key, as screen readers hear it.
  String get keyShift;

  /// A shortcut's ⌃ key, as screen readers hear it.
  String get keyControl;

  /// A shortcut's ⌫ key, as screen readers hear it.
  String get keyBackspace;

  /// A shortcut's ⏎ key, as screen readers hear it.
  String get keyEnter;

  /// An item's position among its siblings, read after its name ("Home, 2 of 4"); index counts from 1.
  String positionOf(int index, int count);

  /// Names the toolbar of replacements for a misspelled word.
  String get spellingSuggestions;

  /// Spell check: the checker has no replacement for a misspelled word.
  String get noSpellingSuggestions;

  /// Names the lower thumb of a range slider.
  String get rangeMinimum;

  /// Names the upper thumb of a range slider.
  String get rangeMaximum;

  /// Names the button that opens a menu of the actions that do not fit, e.g. at the end of a toolbar.
  String get moreActions;

  /// Screen reader action: opens a row's or a card's context menu.
  String get showMenu;

  /// Screen reader hint of an external link: it leaves the app.
  String get opensExternally;

  /// Names a section index: the letter column beside a sorted list.
  String get sectionIndex;

  /// Reorderable list: moves an item one place up.
  String get reorderItemUp;

  /// Reorderable list: moves an item one place down.
  String get reorderItemDown;

  /// Reorderable list: moves an item one place left.
  String get reorderItemLeft;

  /// Reorderable list: moves an item one place right.
  String get reorderItemRight;

  /// Reorderable list: moves an item to the start.
  String get reorderItemToStart;

  /// Reorderable list: moves an item to the end.
  String get reorderItemToEnd;
}
