// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'en.dart';

/// Korean strings.
class DsLocalizationsKo extends DsLocalizationsEn {
  /// Creates the Korean strings.
  const DsLocalizationsKo();

  @override
  String get localeName => 'ko';

  @override
  String get close => '닫기';

  @override
  String get cancel => '취소';

  @override
  String get confirm => '확인';

  @override
  String get dismiss => '닫기';

  @override
  String get previousPage => '이전 페이지';

  @override
  String get nextPage => '다음 페이지';

  @override
  String get selectPlaceholder => '선택';

  @override
  String get selectNoResults => '결과 없음';

  @override
  String selectResultCount(int count) => '결과 $count개';

  @override
  String get loading => '로드 중';

  @override
  String moreCount(int count) => '$count개 더';

  @override
  String page(int page) => '$page페이지';

  @override
  String pageOf(int page, int count) => '$count페이지 중 $page페이지';

  @override
  String get currentPage => '현재 페이지';

  @override
  String get pagination => '페이지 매기기';

  @override
  String get breadcrumb => '탐색 경로';

  @override
  String get error => '오류';

  @override
  String get warning => '경고';

  @override
  String get success => '성공';

  @override
  String get info => '정보';

  @override
  String get selected => '선택됨';

  @override
  String get notification => '알림';

  @override
  String get dismissNotification => '알림 닫기';

  @override
  String get dialog => '대화상자';

  @override
  String get more => '더보기';

  @override
  String get required => '필수';

  @override
  String get increase => '증가';

  @override
  String get decrease => '감소';

  @override
  String get clear => '지우기';

  @override
  String get search => '검색';

  @override
  String get cut => '잘라내기';

  @override
  String get copy => '복사';

  @override
  String get paste => '붙여넣기';

  @override
  String get selectAll => '전체 선택';

  @override
  String get lookUp => '찾아보기';

  @override
  String get share => '공유';

  @override
  String get searchWeb => '웹 검색';

  @override
  String get showPassword => '비밀번호 표시';

  @override
  String get hidePassword => '비밀번호 숨기기';

  @override
  String characterCountLabel(int count, int max) => '$max자 중 $count자';

  @override
  String charactersRemaining(int count) => '$count자 남음';

  @override
  String charactersOver(int count) => '$count자 초과';

  @override
  String remove(String label) => '$label 삭제';

  @override
  String removed(String label) => '$label 삭제됨';

  @override
  String fileUploadPrompt(String browse) => '파일을 여기에 놓거나 $browse';

  @override
  String get fileUploadBrowse => '찾아보기';

  @override
  String get fileUploadDrop => '놓아서 업로드';

  @override
  String get uploading => '업로드 중';

  @override
  String uploaded(String name) => '$name 업로드됨';

  @override
  String uploadFailed(String name) => '$name 업로드할 수 없음';

  @override
  String get uploadError => '업로드 실패';

  @override
  String cancelUpload(String name) => '$name 업로드 취소';

  @override
  String get retry => '다시 시도';

  @override
  String get tableSelectRow => '행 선택';

  @override
  String get tableSelectAll => '모든 행 선택';

  @override
  String get sortedAscending => '오름차순 정렬됨';

  @override
  String get sortedDescending => '내림차순 정렬됨';

  @override
  String get tableNoResults => '결과 없음';

  @override
  String rowCount(int count) => '$count개 행';

  @override
  String selectRowNamed(String name) => '$name 선택';

  @override
  String get sortBy => '정렬 기준';

  @override
  String monthName(int month) => const [
    '1월',
    '2월',
    '3월',
    '4월',
    '5월',
    '6월',
    '7월',
    '8월',
    '9월',
    '10월',
    '11월',
    '12월',
  ][month - 1];

  @override
  String monthNameInDate(int month) => const [
    '1월',
    '2월',
    '3월',
    '4월',
    '5월',
    '6월',
    '7월',
    '8월',
    '9월',
    '10월',
    '11월',
    '12월',
  ][month - 1];

  @override
  String monthAbbr(int month) => const [
    '1월',
    '2월',
    '3월',
    '4월',
    '5월',
    '6월',
    '7월',
    '8월',
    '9월',
    '10월',
    '11월',
    '12월',
  ][month - 1];

  @override
  String weekdayName(int weekday) =>
      const ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일'][weekday - 1];

  @override
  String weekdayAbbr(int weekday) =>
      const ['월', '화', '수', '목', '금', '토', '일'][weekday - 1];

  @override
  String get datePattern => 'y. M. d.';

  @override
  String get dateMediumPattern => 'y년 M월 d일';

  @override
  String get dateFullPattern => 'y년 M월 d일 EEEE';

  @override
  String get monthYearPattern => 'y년 M월';

  @override
  String get dateHint => 'YYYY. MM. DD.';

  @override
  String get timePattern12 => 'a h:mm';

  @override
  String get am => '오전';

  @override
  String get pm => '오후';

  @override
  String get previousMonth => '이전 달';

  @override
  String get nextMonth => '다음 달';

  @override
  String get chooseDate => '날짜 선택';

  @override
  String get chooseTime => '시간 선택';

  @override
  String get today => '오늘';

  @override
  String get hours => '시';

  @override
  String get minutes => '분';

  @override
  String get dayPeriod => '오전/오후';

  @override
  String get rangeStart => '시작일';

  @override
  String get rangeEnd => '종료일';

  @override
  String get inRange => '기간 내';

  @override
  String invalidDate(String format) => '날짜를 $format 형식으로 입력하세요.';

  @override
  String invalidTime(String example) => '시간을 $example 형식으로 입력하세요.';

  @override
  String get invalidNumber => '숫자를 입력하세요.';

  @override
  String dateTooEarly(String date) => '$date 이후의 날짜를 입력하세요.';

  @override
  String dateTooLate(String date) => '$date 이전의 날짜를 입력하세요.';

  @override
  String get dateUnavailable => '이 날짜는 선택할 수 없습니다.';

  @override
  String numberTooSmall(String min) => '$min 이상의 숫자를 입력하세요.';

  @override
  String numberTooLarge(String max) => '$max 이하의 숫자를 입력하세요.';

  @override
  String get seconds => '초';

  @override
  String get unavailable => '선택 불가';

  @override
  String timeTooEarly(String time) => '$time 이후의 시간을 입력하세요.';

  @override
  String timeTooLate(String time) => '$time 이전의 시간을 입력하세요.';

  @override
  String timeOutsideRange(String first, String last) =>
      '$first부터 $last까지의 시간을 입력하세요.';

  @override
  String get fieldRequired => '필수 항목입니다.';

  @override
  String textTooShort(int min) => '$min자 이상 입력하세요.';

  @override
  String textTooLong(int max) => '$max자 이하로 입력하세요.';

  @override
  String get invalidEmail => 'name@example.com 형식의 이메일 주소를 입력하세요.';

  @override
  String useCustom(String text) => '“$text” 사용';

  @override
  String retryUpload(String name) => '$name 업로드 다시 시도';

  @override
  String get presenceOnline => '온라인';

  @override
  String get presenceAway => '자리 비움';

  @override
  String get presenceBusy => '다른 용무 중';

  @override
  String get presenceOffline => '오프라인';

  @override
  String get breadcrumbMore => '상위 경로 더보기';

  @override
  String get rowActions => '작업';

  @override
  String rowActionsFor(String name) => '$name 작업';

  @override
  String get delete => '삭제';

  @override
  String get scanText => '텍스트 스캔';

  @override
  String get editAction => '작업';

  @override
  String get imageUnavailable => '이미지를 불러올 수 없음';

  @override
  String tabOf(int index, int count) => '탭 $count개 중 $index번째';

  @override
  String get navigation => '탐색';

  @override
  String numberAmbiguous(String grouped, String decimal) =>
      '$grouped 또는 $decimal 중 하나를 입력하세요.';

  @override
  String get keyCommand => '커맨드';

  @override
  String get keyOption => '옵션';

  @override
  String get keyShift => '시프트';

  @override
  String get keyControl => '컨트롤';

  @override
  String get keyBackspace => '백스페이스';

  @override
  String get keyEnter => '엔터';

  @override
  String positionOf(int index, int count) => '$count개 중 $index번째';

  @override
  String get spellingSuggestions => '맞춤법 제안';

  @override
  String get noSpellingSuggestions => '대치 항목 없음';

  @override
  String get rangeMinimum => '최솟값';

  @override
  String get rangeMaximum => '최댓값';

  @override
  String get moreActions => '추가 작업';

  @override
  String get showMenu => '메뉴 표시';
}
