// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'en.dart';

/// Russian strings.
class DsLocalizationsRu extends DsLocalizationsEn {
  /// Creates the Russian strings.
  const DsLocalizationsRu();

  @override
  String get localeName => 'ru';

  @override
  String get close => 'Закрыть';

  @override
  String get cancel => 'Отмена';

  @override
  String get confirm => 'Подтвердить';

  @override
  String get dismiss => 'Закрыть';

  @override
  String get previousPage => 'Предыдущая страница';

  @override
  String get nextPage => 'Следующая страница';

  @override
  String get selectPlaceholder => 'Выберите';

  @override
  String get selectNoResults => 'Нет результатов';

  @override
  String selectResultCount(int count) =>
      '$count ${count % 10 == 1 && count % 100 != 11
          ? 'результат'
          : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 12 || count % 100 > 14)
          ? 'результата'
          : 'результатов'}';

  @override
  String get loading => 'Загрузка';

  @override
  String percent(int value) => '$value\u00A0%';

  @override
  String moreCount(int count) => 'ещё $count';

  @override
  String page(int page) => 'Страница $page';

  @override
  String pageOf(int page, int count) => 'Страница $page из $count';

  @override
  String get currentPage => 'Текущая страница';

  @override
  String get pagination => 'Нумерация страниц';

  @override
  String get breadcrumb => 'Навигационная цепочка';

  @override
  String get error => 'Ошибка';

  @override
  String get warning => 'Предупреждение';

  @override
  String get success => 'Успешно';

  @override
  String get info => 'Информация';

  @override
  String get selected => 'Выбрано';

  @override
  String get notification => 'Уведомление';

  @override
  String get dismissNotification => 'Закрыть уведомление';

  @override
  String get dialog => 'Диалоговое окно';

  @override
  String get more => 'Ещё';

  @override
  String get required => 'Обязательно';

  @override
  String get increase => 'Увеличить';

  @override
  String get decrease => 'Уменьшить';

  @override
  String get clear => 'Очистить';

  @override
  String get search => 'Поиск';

  @override
  String get cut => 'Вырезать';

  @override
  String get copy => 'Копировать';

  @override
  String get paste => 'Вставить';

  @override
  String get selectAll => 'Выбрать все';

  @override
  String get lookUp => 'Найти';

  @override
  String get share => 'Поделиться';

  @override
  String get searchWeb => 'Искать в интернете';

  @override
  String get showPassword => 'Показать пароль';

  @override
  String get hidePassword => 'Скрыть пароль';

  @override
  String characterCountLabel(int count, int max) =>
      '$count из $max ${max % 10 == 1 && max % 100 != 11 ? 'символа' : 'символов'}';

  @override
  String charactersRemaining(int count) => count % 10 == 1 && count % 100 != 11
      ? 'Остался $count символ'
      : count % 10 >= 2 &&
            count % 10 <= 4 &&
            (count % 100 < 12 || count % 100 > 14)
      ? 'Осталось $count символа'
      : 'Осталось $count символов';

  @override
  String charactersOver(int count) => 'Лишних символов: $count';

  @override
  String remove(String label) => 'Удалить: $label';

  @override
  String removed(String label) => 'Удалено: $label';

  @override
  String fileUploadPrompt(String browse) => 'Перетащите файлы сюда или $browse';

  @override
  String get fileUploadBrowse => 'выберите';

  @override
  String get fileUploadDrop => 'Отпустите, чтобы загрузить';

  @override
  String get uploading => 'Загрузка';

  @override
  String uploaded(String name) => 'Файл $name загружен';

  @override
  String uploadFailed(String name) => 'Не удалось загрузить $name';

  @override
  String get uploadError => 'Ошибка загрузки';

  @override
  String cancelUpload(String name) => 'Отменить загрузку $name';

  @override
  String get retry => 'Повторить';

  @override
  String fileSizeUnit(int power) => const ['Б', 'КБ', 'МБ', 'ГБ', 'ТБ'][power];

  @override
  String get tableSelectRow => 'Выбрать строку';

  @override
  String get tableSelectAll => 'Выбрать все строки';

  @override
  String get sortedAscending => 'Сортировка по возрастанию';

  @override
  String get sortedDescending => 'Сортировка по убыванию';

  @override
  String get tableNoResults => 'Нет результатов';

  @override
  String rowCount(int count) =>
      '$count ${count % 10 == 1 && count % 100 != 11
          ? 'строка'
          : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 12 || count % 100 > 14)
          ? 'строки'
          : 'строк'}';

  @override
  String selectRowNamed(String name) => 'Выбрать: $name';

  @override
  String get sortBy => 'Сортировать по';

  @override
  String monthName(int month) => const [
    'Январь',
    'Февраль',
    'Март',
    'Апрель',
    'Май',
    'Июнь',
    'Июль',
    'Август',
    'Сентябрь',
    'Октябрь',
    'Ноябрь',
    'Декабрь',
  ][month - 1];

  @override
  String monthNameInDate(int month) => const [
    'января',
    'февраля',
    'марта',
    'апреля',
    'мая',
    'июня',
    'июля',
    'августа',
    'сентября',
    'октября',
    'ноября',
    'декабря',
  ][month - 1];

  @override
  String monthAbbr(int month) => const [
    'янв.',
    'февр.',
    'мар.',
    'апр.',
    'мая',
    'июн.',
    'июл.',
    'авг.',
    'сент.',
    'окт.',
    'нояб.',
    'дек.',
  ][month - 1];

  @override
  String weekdayName(int weekday) => const [
    'понедельник',
    'вторник',
    'среда',
    'четверг',
    'пятница',
    'суббота',
    'воскресенье',
  ][weekday - 1];

  @override
  String weekdayAbbr(int weekday) =>
      const ['пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс'][weekday - 1];

  @override
  String get datePattern => 'dd.MM.y';

  @override
  String get dateMediumPattern => 'd MMM y \'г\'.';

  @override
  String get dateFullPattern => 'EEEE, d MMMM y \'г\'.';

  @override
  String get monthYearPattern => 'LLLL y';

  @override
  String get dateHint => 'ДД.ММ.ГГГГ';

  @override
  String get timePattern12 => 'h:mm a';

  @override
  String get previousMonth => 'Предыдущий месяц';

  @override
  String get nextMonth => 'Следующий месяц';

  @override
  String get chooseDate => 'Выбрать дату';

  @override
  String get chooseTime => 'Выбрать время';

  @override
  String get today => 'Сегодня';

  @override
  String get hours => 'Часы';

  @override
  String get minutes => 'Минуты';

  @override
  String get rangeStart => 'Дата начала';

  @override
  String get rangeEnd => 'Дата окончания';

  @override
  String get inRange => 'В диапазоне';

  @override
  String invalidDate(String format) => 'Введите дату в формате $format.';

  @override
  String invalidTime(String example) => 'Введите время, например $example.';

  @override
  String get invalidNumber => 'Введите число.';

  @override
  String dateTooEarly(String date) => 'Введите дату не раньше $date.';

  @override
  String dateTooLate(String date) => 'Введите дату не позже $date.';

  @override
  String get dateUnavailable => 'Эту дату нельзя выбрать.';

  @override
  String numberTooSmall(String min) => 'Введите число не меньше $min.';

  @override
  String numberTooLarge(String max) => 'Введите число не больше $max.';

  @override
  String get fieldRequired => 'Это поле обязательно.';

  @override
  String textTooShort(int min) =>
      'Введите не меньше $min ${min % 10 == 1 && min % 100 != 11 ? 'символа' : 'символов'}.';

  @override
  String textTooLong(int max) =>
      'Введите не больше $max ${max % 10 == 1 && max % 100 != 11 ? 'символа' : 'символов'}.';

  @override
  String get invalidEmail =>
      'Введите адрес электронной почты, например name@example.com.';

  @override
  String useCustom(String text) => 'Использовать «$text»';

  @override
  String retryUpload(String name) => 'Повторить загрузку $name';

  @override
  String get presenceOnline => 'В сети';

  @override
  String get presenceAway => 'Отошёл';

  @override
  String get presenceBusy => 'Занят';

  @override
  String get presenceOffline => 'Не в сети';

  @override
  String get breadcrumbMore => 'Другие уровни';

  @override
  String get rowActions => 'Действия';

  @override
  String rowActionsFor(String name) => 'Действия: $name';

  @override
  String get delete => 'Удалить';

  @override
  String get scanText => 'Сканировать текст';

  @override
  String get editAction => 'Действие';

  @override
  String get imageUnavailable => 'Изображение недоступно';

  @override
  String tabOf(int index, int count) => 'Вкладка $index из $count';

  @override
  String get navigation => 'Навигация';

  @override
  String numberAmbiguous(String grouped, String decimal) =>
      'Введите $grouped или $decimal.';

  @override
  String get keyCommand => 'Command';

  @override
  String get keyOption => 'Option';

  @override
  String get keyShift => 'Shift';

  @override
  String get keyControl => 'Control';

  @override
  String get keyBackspace => 'Backspace';

  @override
  String get keyEnter => 'Ввод';

  @override
  String positionOf(int index, int count) => '$index из $count';

  @override
  String get spellingSuggestions => 'Варианты правописания';

  @override
  String get noSpellingSuggestions => 'Замены не найдены';
}
