// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'en.dart';

/// Turkish strings.
class DsLocalizationsTr extends DsLocalizationsEn {
  /// Creates the Turkish strings.
  const DsLocalizationsTr();

  @override
  String get localeName => 'tr';

  @override
  String get close => 'Kapat';

  @override
  String get cancel => 'Vazgeç';

  @override
  String get confirm => 'Onayla';

  @override
  String get dismiss => 'Kapat';

  @override
  String get previousPage => 'Önceki sayfa';

  @override
  String get nextPage => 'Sonraki sayfa';

  @override
  String get selectPlaceholder => 'Seçin';

  @override
  String get selectNoResults => 'Sonuç yok';

  @override
  String selectResultCount(int count) => '$count sonuç';

  @override
  String get loading => 'Yükleniyor';

  @override
  String percent(int value) => '%$value';

  @override
  String moreCount(int count) => '$count tane daha';

  @override
  String page(int page) => 'Sayfa $page';

  @override
  String pageOf(int page, int count) => '$page. sayfa, toplam $count';

  @override
  String get currentPage => 'Geçerli sayfa';

  @override
  String get pagination => 'Sayfalama';

  @override
  String get breadcrumb => 'Gezinme yolu';

  @override
  String get error => 'Hata';

  @override
  String get warning => 'Uyarı';

  @override
  String get success => 'Başarılı';

  @override
  String get info => 'Bilgi';

  @override
  String get selected => 'Seçili';

  @override
  String get notification => 'Bildirim';

  @override
  String get dismissNotification => 'Bildirimi kapat';

  @override
  String get dialog => 'İletişim kutusu';

  @override
  String get more => 'Daha fazla';

  @override
  String get required => 'Zorunlu';

  @override
  String get increase => 'Artır';

  @override
  String get decrease => 'Azalt';

  @override
  String get clear => 'Temizle';

  @override
  String get search => 'Ara';

  @override
  String get cut => 'Kes';

  @override
  String get copy => 'Kopyala';

  @override
  String get paste => 'Yapıştır';

  @override
  String get selectAll => 'Tümünü seç';

  @override
  String get lookUp => 'Araştır';

  @override
  String get share => 'Paylaş';

  @override
  String get searchWeb => 'Web\'de ara';

  @override
  String get showPassword => 'Parolayı göster';

  @override
  String get hidePassword => 'Parolayı gizle';

  @override
  String characterCountLabel(int count, int max) =>
      '$count karakter, en fazla $max';

  @override
  String charactersRemaining(int count) => '$count karakter kaldı';

  @override
  String charactersOver(int count) => '$count karakter fazla';

  @override
  String remove(String label) => 'Kaldır: $label';

  @override
  String removed(String label) => '$label kaldırıldı';

  @override
  String fileUploadPrompt(String browse) =>
      'Dosyaları buraya bırakın ya da $browse';

  @override
  String get fileUploadBrowse => 'seçin';

  @override
  String get fileUploadDrop => 'Yüklemek için bırakın';

  @override
  String get uploading => 'Yükleniyor';

  @override
  String uploaded(String name) => '$name yüklendi';

  @override
  String uploadFailed(String name) => '$name yüklenemedi';

  @override
  String get uploadError => 'Yüklenemedi';

  @override
  String cancelUpload(String name) => '$name yüklemesini iptal et';

  @override
  String get retry => 'Yeniden dene';

  @override
  String get tableSelectRow => 'Satırı seç';

  @override
  String get tableSelectAll => 'Tüm satırları seç';

  @override
  String get sortedAscending => 'Artan sıralı';

  @override
  String get sortedDescending => 'Azalan sıralı';

  @override
  String get tableNoResults => 'Sonuç bulunamadı';

  @override
  String rowCount(int count) => '$count satır';

  @override
  String selectRowNamed(String name) => '$name satırını seç';

  @override
  String get sortBy => 'Sırala';

  @override
  String monthName(int month) => const [
    'Ocak',
    'Şubat',
    'Mart',
    'Nisan',
    'Mayıs',
    'Haziran',
    'Temmuz',
    'Ağustos',
    'Eylül',
    'Ekim',
    'Kasım',
    'Aralık',
  ][month - 1];

  @override
  String monthNameInDate(int month) => const [
    'Ocak',
    'Şubat',
    'Mart',
    'Nisan',
    'Mayıs',
    'Haziran',
    'Temmuz',
    'Ağustos',
    'Eylül',
    'Ekim',
    'Kasım',
    'Aralık',
  ][month - 1];

  @override
  String monthAbbr(int month) => const [
    'Oca',
    'Şub',
    'Mar',
    'Nis',
    'May',
    'Haz',
    'Tem',
    'Ağu',
    'Eyl',
    'Eki',
    'Kas',
    'Ara',
  ][month - 1];

  @override
  String weekdayName(int weekday) => const [
    'Pazartesi',
    'Salı',
    'Çarşamba',
    'Perşembe',
    'Cuma',
    'Cumartesi',
    'Pazar',
  ][weekday - 1];

  @override
  String weekdayAbbr(int weekday) =>
      const ['Pt', 'Sa', 'Ça', 'Pe', 'Cu', 'Ct', 'Pz'][weekday - 1];

  @override
  String get datePattern => 'dd.MM.y';

  @override
  String get dateMediumPattern => 'd MMM y';

  @override
  String get dateFullPattern => 'd MMMM y EEEE';

  @override
  String get monthYearPattern => 'LLLL y';

  @override
  String get dateHint => 'GG.AA.YYYY';

  @override
  String get timePattern12 => 'a h:mm';

  @override
  String get am => 'ÖÖ';

  @override
  String get pm => 'ÖS';

  @override
  String get previousMonth => 'Önceki ay';

  @override
  String get nextMonth => 'Sonraki ay';

  @override
  String get chooseDate => 'Tarih seç';

  @override
  String get chooseTime => 'Saat seç';

  @override
  String get today => 'Bugün';

  @override
  String get hours => 'Saat';

  @override
  String get minutes => 'Dakika';

  @override
  String get dayPeriod => 'ÖÖ/ÖS';

  @override
  String get rangeStart => 'Başlangıç tarihi';

  @override
  String get rangeEnd => 'Bitiş tarihi';

  @override
  String get inRange => 'Aralıkta';

  @override
  String invalidDate(String format) => 'Tarihi $format biçiminde girin.';

  @override
  String invalidTime(String example) => 'Saati $example gibi girin.';

  @override
  String get invalidNumber => 'Bir sayı girin.';

  @override
  String dateTooEarly(String date) => '$date ya da sonraki bir tarih girin.';

  @override
  String dateTooLate(String date) => '$date ya da önceki bir tarih girin.';

  @override
  String get dateUnavailable => 'Bu tarih seçilemez.';

  @override
  String numberTooSmall(String min) => '$min ya da daha büyük bir sayı girin.';

  @override
  String numberTooLarge(String max) => '$max ya da daha küçük bir sayı girin.';

  @override
  String get fieldRequired => 'Bu alan zorunludur.';

  @override
  String textTooShort(int min) => 'En az $min karakter girin.';

  @override
  String textTooLong(int max) => 'En fazla $max karakter girin.';

  @override
  String get invalidEmail => 'name@example.com gibi bir e-posta adresi girin.';

  @override
  String useCustom(String text) => '“$text” kullan';

  @override
  String retryUpload(String name) => '$name yüklemesini yeniden dene';

  @override
  String get presenceOnline => 'Çevrimiçi';

  @override
  String get presenceAway => 'Uzakta';

  @override
  String get presenceBusy => 'Meşgul';

  @override
  String get presenceOffline => 'Çevrimdışı';

  @override
  String get breadcrumbMore => 'Diğer düzeyler';

  @override
  String get rowActions => 'İşlemler';

  @override
  String rowActionsFor(String name) => '$name işlemleri';

  @override
  String get delete => 'Sil';

  @override
  String get scanText => 'Metni tara';

  @override
  String get editAction => 'İşlem';

  @override
  String get imageUnavailable => 'Görsel yüklenemedi';

  @override
  String tabOf(int index, int count) => '$index. sekme, toplam $count';

  @override
  String get navigation => 'Gezinme';
}
