// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'en.dart';

/// Chinese (Simplified) strings.
class DsLocalizationsZh extends DsLocalizationsEn {
  /// Creates the Chinese (Simplified) strings.
  const DsLocalizationsZh();

  @override
  String get localeName => 'zh';

  @override
  String get close => '关闭';

  @override
  String get cancel => '取消';

  @override
  String get confirm => '确认';

  @override
  String get dismiss => '关闭';

  @override
  String get previousPage => '上一页';

  @override
  String get nextPage => '下一页';

  @override
  String get selectPlaceholder => '请选择';

  @override
  String get selectNoResults => '无结果';

  @override
  String selectResultCount(int count) => '$count 个结果';

  @override
  String get loading => '正在加载';

  @override
  String moreCount(int count) => '还有 $count 个';

  @override
  String page(int page) => '第 $page 页';

  @override
  String pageOf(int page, int count) => '第 $page 页，共 $count 页';

  @override
  String get currentPage => '当前页';

  @override
  String get pagination => '分页';

  @override
  String get breadcrumb => '面包屑导航';

  @override
  String get error => '错误';

  @override
  String get warning => '警告';

  @override
  String get success => '成功';

  @override
  String get info => '信息';

  @override
  String get selected => '已选择';

  @override
  String get notification => '通知';

  @override
  String get dismissNotification => '关闭通知';

  @override
  String get dialog => '对话框';

  @override
  String get more => '更多';

  @override
  String get required => '必填';

  @override
  String get increase => '增加';

  @override
  String get decrease => '减少';

  @override
  String get clear => '清除';

  @override
  String get search => '搜索';

  @override
  String get cut => '剪切';

  @override
  String get copy => '复制';

  @override
  String get paste => '粘贴';

  @override
  String get selectAll => '全选';

  @override
  String get lookUp => '查询';

  @override
  String get share => '分享';

  @override
  String get searchWeb => '网页搜索';

  @override
  String get showPassword => '显示密码';

  @override
  String get hidePassword => '隐藏密码';

  @override
  String characterCountLabel(int count, int max) => '已输入 $count 个字符，最多 $max 个';

  @override
  String charactersRemaining(int count) => '还可输入 $count 个字符';

  @override
  String charactersOver(int count) => '超出 $count 个字符';

  @override
  String remove(String label) => '移除 $label';

  @override
  String removed(String label) => '已移除 $label';

  @override
  String fileUploadPrompt(String browse) => '将文件拖放到此处，或$browse';

  @override
  String get fileUploadBrowse => '浏览';

  @override
  String get fileUploadDrop => '松开即可上传';

  @override
  String get uploading => '正在上传';

  @override
  String uploaded(String name) => '已上传 $name';

  @override
  String uploadFailed(String name) => '无法上传 $name';

  @override
  String get uploadError => '上传失败';

  @override
  String cancelUpload(String name) => '取消上传 $name';

  @override
  String get retry => '重试';

  @override
  String get tableSelectRow => '选择行';

  @override
  String get tableSelectAll => '选择所有行';

  @override
  String get sortedAscending => '升序排列';

  @override
  String get sortedDescending => '降序排列';

  @override
  String get tableNoResults => '无结果';

  @override
  String rowCount(int count) => '$count 行';

  @override
  String selectRowNamed(String name) => '选择 $name';

  @override
  String get sortBy => '排序方式';

  @override
  String monthName(int month) => const [
    '一月',
    '二月',
    '三月',
    '四月',
    '五月',
    '六月',
    '七月',
    '八月',
    '九月',
    '十月',
    '十一月',
    '十二月',
  ][month - 1];

  @override
  String monthNameInDate(int month) => const [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ][month - 1];

  @override
  String monthAbbr(int month) => const [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ][month - 1];

  @override
  String weekdayName(int weekday) =>
      const ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'][weekday - 1];

  @override
  String weekdayAbbr(int weekday) =>
      const ['一', '二', '三', '四', '五', '六', '日'][weekday - 1];

  @override
  String get datePattern => 'y/M/d';

  @override
  String get dateMediumPattern => 'y年M月d日';

  @override
  String get dateFullPattern => 'y年M月d日EEEE';

  @override
  String get monthYearPattern => 'y年M月';

  @override
  String get dateHint => 'YYYY/MM/DD';

  @override
  String get timePattern12 => 'ah:mm';

  @override
  String get am => '上午';

  @override
  String get pm => '下午';

  @override
  String get previousMonth => '上个月';

  @override
  String get nextMonth => '下个月';

  @override
  String get chooseDate => '选择日期';

  @override
  String get chooseTime => '选择时间';

  @override
  String get today => '今天';

  @override
  String get hours => '小时';

  @override
  String get minutes => '分钟';

  @override
  String get dayPeriod => '上午/下午';

  @override
  String get rangeStart => '开始日期';

  @override
  String get rangeEnd => '结束日期';

  @override
  String get inRange => '范围内';

  @override
  String invalidDate(String format) => '请按 $format 格式输入日期。';

  @override
  String invalidTime(String example) => '请输入时间，例如 $example。';

  @override
  String get invalidNumber => '请输入数字。';

  @override
  String dateTooEarly(String date) => '请输入 $date 或之后的日期。';

  @override
  String dateTooLate(String date) => '请输入 $date 或之前的日期。';

  @override
  String get dateUnavailable => '无法选择此日期。';

  @override
  String numberTooSmall(String min) => '请输入不小于 $min 的数字。';

  @override
  String numberTooLarge(String max) => '请输入不大于 $max 的数字。';

  @override
  String get seconds => '秒';

  @override
  String get unavailable => '不可选';

  @override
  String timeTooEarly(String time) => '请输入 $time 或之后的时间。';

  @override
  String timeTooLate(String time) => '请输入 $time 或之前的时间。';

  @override
  String timeOutsideRange(String first, String last) =>
      '请输入 $first 至 $last 之间的时间。';

  @override
  String get fieldRequired => '此字段为必填项。';

  @override
  String textTooShort(int min) => '请至少输入 $min 个字符。';

  @override
  String textTooLong(int max) => '最多可输入 $max 个字符。';

  @override
  String get invalidEmail => '请输入电子邮件地址，例如 name@example.com。';

  @override
  String useCustom(String text) => '使用“$text”';

  @override
  String retryUpload(String name) => '重试上传 $name';

  @override
  String get presenceOnline => '在线';

  @override
  String get presenceAway => '离开';

  @override
  String get presenceBusy => '忙碌';

  @override
  String get presenceOffline => '离线';

  @override
  String get breadcrumbMore => '更多层级';

  @override
  String get rowActions => '操作';

  @override
  String rowActionsFor(String name) => '$name 的操作';

  @override
  String get delete => '删除';

  @override
  String get scanText => '扫描文本';

  @override
  String get editAction => '操作';

  @override
  String get imageUnavailable => '图片无法加载';

  @override
  String tabOf(int index, int count) => '第 $index 个标签，共 $count 个';

  @override
  String get navigation => '导航';

  @override
  String numberAmbiguous(String grouped, String decimal) =>
      '请输入 $grouped 或 $decimal。';

  @override
  String get keyCommand => '命令';

  @override
  String get keyOption => '选项';

  @override
  String get keyShift => '上档';

  @override
  String get keyControl => '控制';

  @override
  String get keyBackspace => '退格';

  @override
  String get keyEnter => '回车';

  @override
  String positionOf(int index, int count) => '第 $index 个，共 $count 个';

  @override
  String get spellingSuggestions => '拼写建议';

  @override
  String get noSpellingSuggestions => '未找到替换项';

  @override
  String get rangeMinimum => '最小值';

  @override
  String get rangeMaximum => '最大值';

  @override
  String get moreActions => '更多操作';

  @override
  String get showMenu => '显示菜单';

  @override
  String get opensExternally => '在应用外打开';
}
