// GENERATED by tool/gen_l10n.py. Do not edit by hand.

import 'zh.dart';

/// Traditional Chinese strings.
class DsLocalizationsZhHant extends DsLocalizationsZh {
  /// Creates the Traditional Chinese strings.
  const DsLocalizationsZhHant();

  @override
  String get localeName => 'zh_Hant';

  @override
  String get close => '關閉';

  @override
  String get confirm => '確認';

  @override
  String get dismiss => '關閉';

  @override
  String get previousPage => '上一頁';

  @override
  String get nextPage => '下一頁';

  @override
  String get selectPlaceholder => '請選擇';

  @override
  String get selectNoResults => '沒有結果';

  @override
  String selectResultCount(int count) => '$count 項結果';

  @override
  String get loading => '載入中';

  @override
  String moreCount(int count) => '還有 $count 個';

  @override
  String page(int page) => '第 $page 頁';

  @override
  String pageOf(int page, int count) => '第 $page 頁，共 $count 頁';

  @override
  String get currentPage => '目前頁面';

  @override
  String get pagination => '分頁';

  @override
  String get breadcrumb => '導覽路徑';

  @override
  String get error => '錯誤';

  @override
  String get info => '資訊';

  @override
  String get selected => '已選取';

  @override
  String get dismissNotification => '關閉通知';

  @override
  String get dialog => '對話方塊';

  @override
  String get decrease => '減少';

  @override
  String get search => '搜尋';

  @override
  String get cut => '剪下';

  @override
  String get copy => '拷貝';

  @override
  String get paste => '貼上';

  @override
  String get selectAll => '全選';

  @override
  String get lookUp => '查詢';

  @override
  String get searchWeb => '搜尋網頁';

  @override
  String get showPassword => '顯示密碼';

  @override
  String get hidePassword => '隱藏密碼';

  @override
  String characterCountLabel(int count, int max) => '已輸入 $count 個字元，上限 $max 個';

  @override
  String charactersRemaining(int count) => '還可輸入 $count 個字元';

  @override
  String charactersOver(int count) => '超出 $count 個字元';

  @override
  String fileUploadPrompt(String browse) => '將檔案拖放到此處，或$browse';

  @override
  String get fileUploadBrowse => '瀏覽';

  @override
  String get fileUploadDrop => '放開即可上傳';

  @override
  String get uploading => '正在上傳';

  @override
  String uploaded(String name) => '已上傳 $name';

  @override
  String uploadFailed(String name) => '無法上傳 $name';

  @override
  String get uploadError => '上傳失敗';

  @override
  String cancelUpload(String name) => '取消上傳 $name';

  @override
  String get retry => '重試';

  @override
  String get tableSelectRow => '選取列';

  @override
  String get tableSelectAll => '選取所有列';

  @override
  String get sortedAscending => '遞增排序';

  @override
  String get sortedDescending => '遞減排序';

  @override
  String get tableNoResults => '沒有結果';

  @override
  String rowCount(int count) => '$count 列';

  @override
  String selectRowNamed(String name) => '選取 $name';

  @override
  String get dateFullPattern => 'y年M月d日 EEEE';

  @override
  String get previousMonth => '上個月';

  @override
  String get nextMonth => '下個月';

  @override
  String get chooseDate => '選擇日期';

  @override
  String get chooseTime => '選擇時間';

  @override
  String get hours => '小時';

  @override
  String get minutes => '分鐘';

  @override
  String get rangeStart => '開始日期';

  @override
  String get rangeEnd => '結束日期';

  @override
  String get inRange => '範圍內';

  @override
  String invalidDate(String format) => '請按 $format 格式輸入日期。';

  @override
  String invalidTime(String example) => '請輸入時間，例如 $example。';

  @override
  String get invalidNumber => '請輸入數字。';

  @override
  String dateTooEarly(String date) => '請輸入 $date 或之後的日期。';

  @override
  String dateTooLate(String date) => '請輸入 $date 或之前的日期。';

  @override
  String get dateUnavailable => '無法選擇此日期。';

  @override
  String numberTooSmall(String min) => '請輸入不小於 $min 的數字。';

  @override
  String numberTooLarge(String max) => '請輸入不大於 $max 的數字。';

  @override
  String get unavailable => '不可選';

  @override
  String timeTooEarly(String time) => '請輸入 $time 或之後的時間。';

  @override
  String timeTooLate(String time) => '請輸入 $time 或之前的時間。';

  @override
  String get fieldRequired => '此欄位為必填。';

  @override
  String textTooShort(int min) => '請至少輸入 $min 個字元。';

  @override
  String textTooLong(int max) => '最多可輸入 $max 個字元。';

  @override
  String get invalidEmail => '請輸入電子郵件地址，例如 name@example.com。';

  @override
  String useCustom(String text) => '使用「$text」';

  @override
  String retryUpload(String name) => '重試上傳 $name';

  @override
  String get presenceOnline => '線上';

  @override
  String get presenceAway => '離開';

  @override
  String get presenceOffline => '離線';

  @override
  String get breadcrumbMore => '更多層級';

  @override
  String get delete => '刪除';

  @override
  String get scanText => '掃描文字';

  @override
  String get imageUnavailable => '圖片無法載入';

  @override
  String tabOf(int index, int count) => '第 $index 個分頁，共 $count 個';

  @override
  String get navigation => '導覽';

  @override
  String numberAmbiguous(String grouped, String decimal) =>
      '請輸入 $grouped 或 $decimal。';

  @override
  String get keyOption => '選項';

  @override
  String get keyShift => 'Shift';

  @override
  String get keyEnter => '輸入';

  @override
  String positionOf(int index, int count) => '第 $index 個，共 $count 個';
}
