// GENERATED by tool/gen_icons.py from tool/icons/. Do not edit by hand.

import 'package:desen_ui/desen_ui.dart';

part 'icon_catalog/accessibility.dart';
part 'icon_catalog/account.dart';
part 'icon_catalog/animals.dart';
part 'icon_catalog/arrows.dart';
part 'icon_catalog/buildings.dart';
part 'icon_catalog/charts.dart';
part 'icon_catalog/connectivity.dart';
part 'icon_catalog/design.dart';
part 'icon_catalog/development.dart';
part 'icon_catalog/devices.dart';
part 'icon_catalog/files.dart';
part 'icon_catalog/finance.dart';
part 'icon_catalog/food_beverage.dart';
part 'icon_catalog/gaming.dart';
part 'icon_catalog/home.dart';
part 'icon_catalog/layout.dart';
part 'icon_catalog/mail.dart';
part 'icon_catalog/math.dart';
part 'icon_catalog/medical.dart';
part 'icon_catalog/multimedia.dart';
part 'icon_catalog/nature.dart';
part 'icon_catalog/navigation.dart';
part 'icon_catalog/notifications.dart';
part 'icon_catalog/photography.dart';
part 'icon_catalog/science.dart';
part 'icon_catalog/security.dart';
part 'icon_catalog/shapes.dart';
part 'icon_catalog/shopping.dart';
part 'icon_catalog/social.dart';
part 'icon_catalog/sports.dart';
part 'icon_catalog/text.dart';
part 'icon_catalog/time.dart';
part 'icon_catalog/tools.dart';
part 'icon_catalog/transportation.dart';
part 'icon_catalog/travel.dart';
part 'icon_catalog/weather.dart';

/// One built-in icon, with the words the icon browser searches.
class IconEntry {
  const IconEntry(
    this.name,
    this.icon, {
    required this.category,
    this.aliases = const [],
    this.tags = const [],
  });

  final String name;
  final DsIconData icon;
  final String category;
  final List<String> aliases;
  final List<String> tags;
}

/// Every built-in icon, by category, then by name.
const iconCatalog = <IconEntry>[
  ..._accessibility,
  ..._account,
  ..._animals,
  ..._arrows,
  ..._buildings,
  ..._charts,
  ..._connectivity,
  ..._design,
  ..._development,
  ..._devices,
  ..._files,
  ..._finance,
  ..._foodBeverage,
  ..._gaming,
  ..._home,
  ..._layout,
  ..._mail,
  ..._math,
  ..._medical,
  ..._multimedia,
  ..._nature,
  ..._navigation,
  ..._notifications,
  ..._photography,
  ..._science,
  ..._security,
  ..._shapes,
  ..._shopping,
  ..._social,
  ..._sports,
  ..._text,
  ..._time,
  ..._tools,
  ..._transportation,
  ..._travel,
  ..._weather,
];
