// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';
import '../button/button_style.dart';

/// The look of a `DsSelect` trigger.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsSelectStyle(hovered: …)` is the selected-and-hovered look.
///
/// [readOnly] is a state too, passed to [resolve] as a flag: it applies
/// after the interaction states and before the structural ones, so
/// `error: DsSelectStyle(readOnly: …)` styles an error while [readOnly] is set.
@immutable
class DsSelectStyle with Diagnosticable {
  /// Creates a style.
  const DsSelectStyle({
    this.height,
    this.padding,
    this.background,
    this.borderColor,
    this.borderWidth,
    this.borderRadius,
    this.foreground,
    this.placeholderColor,
    this.iconColor,
    this.errorIconColor,
    this.iconSize,
    this.textStyle,
    this.gap,
    this.clearStyle,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.error,
    this.disabled,
    this.readOnly,
  });

  /// Minimum height.
  final double? height;

  /// Inner padding.
  final EdgeInsetsGeometry? padding;

  /// Fill.
  final Color? background;

  /// Inner outline.
  final Color? borderColor;

  /// Width of the inner outline.
  final double? borderWidth;

  /// Corners. When no layer sets them, rounded as a control of `height` (`DsRadii.controlCorners`), so a style that changes only the height keeps them in proportion.
  final BorderRadiusGeometry? borderRadius;

  /// Value color.
  final Color? foreground;

  /// Placeholder color.
  final Color? placeholderColor;

  /// Leading icon and chevron color.
  final Color? iconColor;

  /// Error icon color; the error edge color when null.
  final Color? errorIconColor;

  /// Icon size.
  final double? iconSize;

  /// Value style, merged.
  final TextStyle? textStyle;

  /// Space between parts.
  final double? gap;

  /// The clear button of a clearable select, laid over a ghost extra-small icon button.
  final DsButtonStyle? clearStyle;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsSelectStyle? focused;

  /// Laid over the base while hovered.
  final DsSelectStyle? hovered;

  /// Laid over the base while pressed.
  final DsSelectStyle? pressed;

  /// Laid over the base while error.
  final DsSelectStyle? error;

  /// Laid over the base while disabled.
  final DsSelectStyle? disabled;

  /// Laid over the base while the select is read-only: it shows a value that cannot be changed.
  final DsSelectStyle? readOnly;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsSelectStyle merge(DsSelectStyle? other) {
    if (other == null) return this;
    return DsSelectStyle(
      height: other.height ?? height,
      padding: other.padding ?? padding,
      background: other.background ?? background,
      borderColor: other.borderColor ?? borderColor,
      borderWidth: other.borderWidth ?? borderWidth,
      borderRadius: other.borderRadius ?? borderRadius,
      foreground: other.foreground ?? foreground,
      placeholderColor: other.placeholderColor ?? placeholderColor,
      iconColor: other.iconColor ?? iconColor,
      errorIconColor: other.errorIconColor ?? errorIconColor,
      iconSize: other.iconSize ?? iconSize,
      textStyle: textStyle?.merge(other.textStyle) ?? other.textStyle,
      gap: other.gap ?? gap,
      clearStyle: clearStyle?.merge(other.clearStyle) ?? other.clearStyle,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      error: error == null ? other.error : error!.merge(other.error),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
      readOnly: readOnly == null
          ? other.readOnly
          : readOnly!.merge(other.readOnly),
    );
  }

  DsSelectStyle get _base => DsSelectStyle(
    height: height,
    padding: padding,
    background: background,
    borderColor: borderColor,
    borderWidth: borderWidth,
    borderRadius: borderRadius,
    foreground: foreground,
    placeholderColor: placeholderColor,
    iconColor: iconColor,
    errorIconColor: errorIconColor,
    iconSize: iconSize,
    textStyle: textStyle,
    gap: gap,
    clearStyle: clearStyle,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsSelectStyle resolve(Set<WidgetState> states, {bool readOnly = false}) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (readOnly && this.readOnly != null) {
      s = s.merge(this.readOnly!.resolve(states));
    }
    if (states.contains(WidgetState.error) && error != null) {
      s = s.merge(
        error!.resolve(
          {...states}..remove(WidgetState.error),
          readOnly: readOnly,
        ),
      );
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(
        disabled!.resolve(
          {...states}..remove(WidgetState.disabled),
          readOnly: readOnly,
        ),
      );
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsSelectStyle resolveLayers(
    Iterable<DsSelectStyle?> layers,
    Set<WidgetState> states, {
    bool readOnly = false,
  }) {
    var result = const DsSelectStyle();
    for (final layer in layers) {
      if (layer != null) {
        result = result.merge(layer.resolve(states, readOnly: readOnly));
      }
    }
    return result;
  }

  List<Object?> get _fields => [
    height,
    padding,
    background,
    borderColor,
    borderWidth,
    borderRadius,
    foreground,
    placeholderColor,
    iconColor,
    errorIconColor,
    iconSize,
    textStyle,
    gap,
    clearStyle,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    error,
    disabled,
    readOnly,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsSelectStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(
      ColorProperty('borderColor', borderColor, defaultValue: null),
    );
    properties.add(
      DoubleProperty('borderWidth', borderWidth, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(
      ColorProperty('placeholderColor', placeholderColor, defaultValue: null),
    );
    properties.add(ColorProperty('iconColor', iconColor, defaultValue: null));
    properties.add(
      ColorProperty('errorIconColor', errorIconColor, defaultValue: null),
    );
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(
      DiagnosticsProperty('textStyle', textStyle, defaultValue: null),
    );
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
    properties.add(
      DiagnosticsProperty('clearStyle', clearStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(DiagnosticsProperty('error', error, defaultValue: null));
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('readOnly', readOnly, defaultValue: null),
    );
  }
}

/// Defaults for every `DsSelect` in a subtree; see [DsSelectTheme].
class DsSelectThemeData extends DsComponentThemeData<DsSelectThemeData> {
  /// Creates defaults.
  const DsSelectThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsSelectStyle? style;

  @override
  DsSelectThemeData merge(DsSelectThemeData? other) {
    if (other == null) return this;
    return DsSelectThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsSelectThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsSelectThemeData] to a subtree, merged over any outer one.
class DsSelectTheme extends DsComponentTheme<DsSelectThemeData> {
  /// Applies [data] to [child].
  const DsSelectTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsSelectThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsSelectThemeData>(context) ??
      const DsSelectThemeData();
}
