// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsProgressBar`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsProgressBarStyle with Diagnosticable {
  /// Creates a style.
  const DsProgressBarStyle({
    this.width,
    this.height,
    this.trackColor,
    this.trackShadows,
    this.fillColor,
    this.borderRadius,
  });

  /// Width when the parent leaves it unbounded (e.g. in a Row); otherwise the bar fills the width.
  final double? width;

  /// Track thickness.
  final double? height;

  /// Unfilled track.
  final Color? trackColor;

  /// Track edge, e.g. an inner line (`DsShadows.channel`, empty by default). The fill covers it.
  final List<DsShadow>? trackShadows;

  /// Filled part.
  final Color? fillColor;

  /// Corners of track and fill.
  final BorderRadiusGeometry? borderRadius;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsProgressBarStyle merge(DsProgressBarStyle? other) {
    if (other == null) return this;
    return DsProgressBarStyle(
      width: other.width ?? width,
      height: other.height ?? height,
      trackColor: other.trackColor ?? trackColor,
      trackShadows: other.trackShadows ?? trackShadows,
      fillColor: other.fillColor ?? fillColor,
      borderRadius: other.borderRadius ?? borderRadius,
    );
  }

  /// This style; it has no state styles.
  DsProgressBarStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsProgressBarStyle resolveLayers(
    Iterable<DsProgressBarStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsProgressBarStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    width,
    height,
    trackColor,
    trackShadows,
    fillColor,
    borderRadius,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsProgressBarStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('width', width, defaultValue: null));
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(ColorProperty('trackColor', trackColor, defaultValue: null));
    properties.add(
      DiagnosticsProperty('trackShadows', trackShadows, defaultValue: null),
    );
    properties.add(ColorProperty('fillColor', fillColor, defaultValue: null));
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
  }
}

/// Defaults for every `DsProgressBar` in a subtree; see [DsProgressBarTheme].
class DsProgressBarThemeData
    extends DsComponentThemeData<DsProgressBarThemeData> {
  /// Creates defaults.
  const DsProgressBarThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsProgressBarStyle? style;

  @override
  DsProgressBarThemeData merge(DsProgressBarThemeData? other) {
    if (other == null) return this;
    return DsProgressBarThemeData(
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsProgressBarThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsProgressBarThemeData] to a subtree, merged over any outer one.
class DsProgressBarTheme extends DsComponentTheme<DsProgressBarThemeData> {
  /// Applies [data] to [child].
  const DsProgressBarTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsProgressBarThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsProgressBarThemeData>(context) ??
      const DsProgressBarThemeData();
}
