// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';

/// The look of a `DsProgressRing`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsProgressRingStyle with Diagnosticable {
  /// Creates a style.
  const DsProgressRingStyle({
    this.size,
    this.strokeWidth,
    this.trackColor,
    this.trackEdgeColor,
    this.fillColor,
    this.foreground,
  });

  /// Diameter.
  final double? size;

  /// Ring thickness.
  final double? strokeWidth;

  /// Unfilled ring.
  final Color? trackColor;

  /// Hairlines along both edges of the ring, from `DsShadows.channel`; transparent for none (the default).
  final Color? trackEdgeColor;

  /// Filled arc.
  final Color? fillColor;

  /// Text color of the centered content.
  final Color? foreground;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsProgressRingStyle merge(DsProgressRingStyle? other) {
    if (other == null) return this;
    return DsProgressRingStyle(
      size: other.size ?? size,
      strokeWidth: other.strokeWidth ?? strokeWidth,
      trackColor: other.trackColor ?? trackColor,
      trackEdgeColor: other.trackEdgeColor ?? trackEdgeColor,
      fillColor: other.fillColor ?? fillColor,
      foreground: other.foreground ?? foreground,
    );
  }

  /// This style; it has no state styles.
  DsProgressRingStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsProgressRingStyle resolveLayers(
    Iterable<DsProgressRingStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsProgressRingStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    size,
    strokeWidth,
    trackColor,
    trackEdgeColor,
    fillColor,
    foreground,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsProgressRingStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('size', size, defaultValue: null));
    properties.add(
      DoubleProperty('strokeWidth', strokeWidth, defaultValue: null),
    );
    properties.add(ColorProperty('trackColor', trackColor, defaultValue: null));
    properties.add(
      ColorProperty('trackEdgeColor', trackEdgeColor, defaultValue: null),
    );
    properties.add(ColorProperty('fillColor', fillColor, defaultValue: null));
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
  }
}

/// Defaults for every `DsProgressRing` in a subtree; see [DsProgressRingTheme].
class DsProgressRingThemeData
    extends DsComponentThemeData<DsProgressRingThemeData> {
  /// Creates defaults.
  const DsProgressRingThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsProgressRingStyle? style;

  @override
  DsProgressRingThemeData merge(DsProgressRingThemeData? other) {
    if (other == null) return this;
    return DsProgressRingThemeData(
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsProgressRingThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsProgressRingThemeData] to a subtree, merged over any outer one.
class DsProgressRingTheme extends DsComponentTheme<DsProgressRingThemeData> {
  /// Applies [data] to [child].
  const DsProgressRingTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsProgressRingThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsProgressRingThemeData>(context) ??
      const DsProgressRingThemeData();
}
