"""Collects the code examples of the docs site (example/lib/site).

A region in any site source becomes a snippet the page shows under its
live example, so the code shown is the code that runs:

    // #region button-variants
    DsButton(onPressed: save, child: const Text('Save')),
    // #endregion

The lines are dedented, a trailing comma or semicolon on the last line is
dropped (the region usually sits in a list of children), and a leading
`child: `, `return ` or `final x = ` is dropped. Writes
example/lib/site/snippets.g.dart.

Usage: python3 tool/gen_snippets.py   (add --check to fail when stale)
"""
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(__file__), '..', 'example', 'lib', 'site')
OUT = os.path.join(ROOT, 'snippets.g.dart')
START = re.compile(r'^\s*// #region ([\w-]+)\s*$')
END = re.compile(r'^\s*// #endregion\s*$')


def collect():
    snippets = {}
    for base, _, files in sorted(os.walk(ROOT)):
        for name in sorted(files):
            if not name.endswith('.dart') or name.endswith('.g.dart'):
                continue
            path = os.path.join(base, name)
            current, lines = None, []
            for n, line in enumerate(open(path, encoding='utf-8'), 1):
                line = line.rstrip('\n')
                if m := START.match(line):
                    if current:
                        sys.exit(f'{path}:{n}: region {m[1]} inside {current}')
                    current, lines = m[1], []
                elif END.match(line):
                    if not current:
                        sys.exit(f'{path}:{n}: #endregion without #region')
                    if current in snippets:
                        sys.exit(f'{path}:{n}: duplicate region {current}')
                    snippets[current] = tidy(lines)
                    current = None
                elif current:
                    lines.append(line)
            if current:
                sys.exit(f'{path}: region {current} is not closed')
    return snippets


def tidy(lines):
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
    lines = [l[indent:] for l in lines]
    if lines and lines[-1].endswith((',', ';')):
        lines[-1] = lines[-1][:-1]
    # A region that starts mid-expression ("child: DsCard(", "return
    # Row(") shows the expression alone.
    if lines:
        lines[0] = re.sub(r'^(?:return |(?:final|var) \w+ = |\w+: )', '', lines[0])
    return '\n'.join(lines)


def dart_string(s):
    s = s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$')
    return "'" + s.replace('\n', '\\n') + "'"


def render(snippets):
    out = [
        '// GENERATED by tool/gen_snippets.py. Do not edit by hand.',
        '',
        '/// The source of every `// #region` in the site, by name.',
        'const siteSnippets = <String, String>{',
    ]
    for name, code in sorted(snippets.items()):
        out.append(f"  '{name}':")
        out.append(f'      {dart_string(code)},')
    out.append('};')
    return '\n'.join(out) + '\n'


def formatted(text):
    # The checked-in file is `dart format`ted; compare like with like.
    import subprocess
    import tempfile
    with tempfile.NamedTemporaryFile('w', suffix='.dart', delete=False,
                                     encoding='utf-8') as f:
        f.write(text)
    subprocess.run(['dart', 'format', f.name], check=True,
                   stdout=subprocess.DEVNULL)
    result = open(f.name, encoding='utf-8').read()
    os.unlink(f.name)
    return result


if __name__ == '__main__':
    snippets = collect()
    text = formatted(render(snippets))
    if '--check' in sys.argv:
        old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if old != text:
            sys.exit('snippets.g.dart is stale: run python3 tool/gen_snippets.py')
        print('snippets up to date')
    else:
        open(OUT, 'w', encoding='utf-8').write(text)
        print(f'snippets.g.dart: {len(snippets)} snippets')
