"""Generates the Dart icon set from tool/icons/.

  python3 tool/gen_icons.py            write the files
  python3 tool/gen_icons.py --check    fail if they are out of date

tool/icons/ holds one SVG and one JSON file per icon (see import_icons.py).
The output:

  lib/src/icons/icons.dart          the DsIcons class: one constant per icon
                                    and per alias, documented with its tags
  lib/src/icons/set/<category>.dart the shapes, one part file per category
  example/lib/site/icon_catalog.dart and icon_catalog/<category>.dart
                                    names, aliases and tags for the site's
                                    icon browser (not part of the package)

Dart has no partial classes, so the shapes live in per-category part files as
private constants and DsIcons refers to them. Unused icons cost nothing in an
app: the compiler drops constants that nothing references.

A few Lucide shapes fill a small dot (`fill="currentColor"`, radius 1 or
less). The 2-unit stroke already covers such a dot, so the fill is dropped.
"""

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'tool', 'icons')

LIB = 'lib/src/icons/icons.dart'
LIB_SET = 'lib/src/icons/set'
SITE = 'example/lib/site/icon_catalog.dart'
SITE_SET = 'example/lib/site/icon_catalog'

HEADER = '// GENERATED by tool/gen_icons.py from tool/icons/. Do not edit by hand.'

# Reserved words, and Object's members. Built-in identifiers (`factory`,
# `import`, `type`…) are fine as member names.
RESERVED = set('''
assert break case catch class const continue default do else enum extends
false final finally for if in is new null rethrow return super switch this
throw true try var void while with hashCode runtimeType toString noSuchMethod
'''.split())


def f(v):
    s = ('%.3f' % v).rstrip('0').rstrip('.')
    return s if s not in ('-0', '') else '0'


def attrs(tag):
    return {k: v for k, v in re.findall(r'([\w-]+)="([^"]*)"', tag)}


def num(a, key, default=0.0):
    return float(a[key]) if key in a else default


def ellipse(cx, cy, rx, ry):
    return (f'M{f(cx - rx)} {f(cy)}a{f(rx)} {f(ry)} 0 1 0 {f(2 * rx)} 0'
            f'a{f(rx)} {f(ry)} 0 1 0 {f(-2 * rx)} 0')


def rect(x, y, w, h, rx, ry):
    rx, ry = min(rx, w / 2), min(ry, h / 2)
    if rx == 0 or ry == 0:
        return f'M{f(x)} {f(y)}h{f(w)}v{f(h)}h{f(-w)}z'
    arc = f'a{f(rx)} {f(ry)} 0 0 1'
    return (f'M{f(x + rx)} {f(y)}h{f(w - 2 * rx)}{arc} {f(rx)} {f(ry)}'
            f'v{f(h - 2 * ry)}{arc} {f(-rx)} {f(ry)}h{f(-(w - 2 * rx))}'
            f'{arc} {f(-rx)} {f(-ry)}v{f(-(h - 2 * ry))}{arc} {f(rx)} {f(-ry)}z')


def points(p, close):
    xs = [float(v) for v in re.split(r'[\s,]+', p.strip())]
    pairs = list(zip(xs[0::2], xs[1::2]))
    d = f'M{f(pairs[0][0])} {f(pairs[0][1])}' + ''.join(
        f'L{f(x)} {f(y)}' for x, y in pairs[1:])
    return d + ('z' if close else '')


def paths_of(svg, name):
    out = []
    for kind, body in re.findall(r'<(\w+)\b([^>]*?)/?>', svg):
        a = attrs(body)
        if kind == 'svg':
            if (a.get('viewBox') != '0 0 24 24' or a.get('fill') != 'none'
                    or a.get('stroke-width') != '2'):
                raise SystemExit(f'{name}: unexpected <svg> attributes')
            continue
        if kind == 'path':
            out.append(a['d'])
        elif kind == 'circle':
            r = num(a, 'r')
            out.append(ellipse(num(a, 'cx'), num(a, 'cy'), r, r))
        elif kind == 'ellipse':
            out.append(ellipse(num(a, 'cx'), num(a, 'cy'),
                               num(a, 'rx'), num(a, 'ry')))
        elif kind == 'rect':
            rx = a.get('rx', a.get('ry', '0'))
            ry = a.get('ry', rx)
            out.append(rect(num(a, 'x'), num(a, 'y'), num(a, 'width'),
                            num(a, 'height'), float(rx), float(ry)))
        elif kind == 'line':
            out.append(f'M{f(num(a, "x1"))} {f(num(a, "y1"))}'
                       f'L{f(num(a, "x2"))} {f(num(a, "y2"))}')
        elif kind in ('polyline', 'polygon'):
            out.append(points(a['points'], kind == 'polygon'))
        else:
            raise SystemExit(f'{name}: unsupported <{kind}>')
    if not out:
        raise SystemExit(f'{name}: no shapes')
    return out


def camel(kebab):
    parts = kebab.split('-')
    return parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])


def file_name(category):
    return category.replace('-', '_')


def title(kebab):
    words = kebab.replace('-', ' ')
    return words[:1].upper() + words[1:]


def dart_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"


def load():
    icons = []
    for fn in sorted(os.listdir(SRC)):
        if not fn.endswith('.json'):
            continue
        kebab = fn[:-5]
        with open(os.path.join(SRC, fn)) as fh:
            meta = json.load(fh)
        with open(os.path.join(SRC, kebab + '.svg')) as fh:
            svg = fh.read()
        icons.append({
            'kebab': kebab,
            'name': camel(kebab),
            'category': meta['category'],
            'tags': meta['tags'],
            'aliases': meta['aliases'],
            'mirror': meta['mirror'],
            'paths': paths_of(svg, kebab),
        })
    seen = {}
    for icon in icons:
        for n in [icon['name'], *icon['aliases']]:
            if not re.fullmatch(r'[a-z][A-Za-z0-9]*', n) or n in RESERVED:
                raise SystemExit(f'{icon["kebab"]}: "{n}" is not a usable name')
            if n in seen:
                raise SystemExit(f'"{n}" names both {seen[n]} and {icon["kebab"]}')
            seen[n] = icon['kebab']
    return icons


def doc(icon):
    # Plain words only: symbols such as `$` or `<` would read as markup in a
    # doc comment. The site's catalog keeps every tag.
    tags = [t for t in icon['tags']
            if t.lower() != icon['kebab'].replace('-', ' ')
            and re.fullmatch(r"[A-Za-z0-9 .'&+-]+", t)]
    text = title(icon['kebab']) + '.'
    if tags:
        text += ' Tags: ' + ', '.join(tags[:8]) + '.'
    if icon['mirror']:
        text += ' Mirrors in right-to-left text.'
    return text


def generate(icons):
    files = {}
    by_category = {}
    for icon in icons:
        by_category.setdefault(icon['category'], []).append(icon)
    categories = sorted(by_category)

    # Shapes, one part file per category.
    for category in categories:
        lines = [HEADER, '', "part of '../icons.dart';", '']
        for icon in by_category[category]:
            paths = ', '.join(dart_str(p) for p in icon['paths'])
            extra = ', matchTextDirection: true' if icon['mirror'] else ''
            lines.append(f'const _{icon["name"]} = DsIconData([{paths}]{extra});')
            lines.append('')
        files[f'{LIB_SET}/{file_name(category)}.dart'] = '\n'.join(lines)

    # The public class.
    lines = [HEADER, '', "import 'icon.dart';", '']
    lines += [f"part 'set/{file_name(c)}.dart';" for c in categories]
    lines += [
        '',
        f'/// The built-in icons: {len(icons)} stroke icons on a 24-unit grid, from',
        '/// Lucide (https://lucide.dev, ISC license).',
        '///',
        '/// Names follow Lucide\'s, in lowerCamelCase: `triangle-alert` on',
        '/// lucide.dev is `DsIcons.triangleAlert`. Some icons also have an',
        '/// alias, a more common name for the same shape (`volume2` is also',
        '/// `volumeUp`). Icons an app does not use add nothing to its size.',
        'abstract final class DsIcons {',
    ]
    entries = []
    for icon in icons:
        entries.append((icon['name'], doc(icon), icon['name']))
        for alias in icon['aliases']:
            entries.append((alias, f'Same icon as [{icon["name"]}].', icon['name']))
    for name, text, target in sorted(entries, key=lambda e: e[0].lower()):
        lines.append(f'  /// {text}')
        lines.append(f'  static const {name} = _{target};')
    lines.append('}')
    files[LIB] = '\n'.join(lines)

    # The site's catalog.
    lines = [HEADER, '', "import 'package:desen_ui/desen_ui.dart';", '']
    lines += [f"part 'icon_catalog/{file_name(c)}.dart';" for c in categories]
    lines += [
        '',
        '/// One built-in icon, with the words the icon browser searches.',
        'class IconEntry {',
        '  const IconEntry(',
        '    this.name,',
        '    this.icon, {',
        '    required this.category,',
        '    this.aliases = const [],',
        '    this.tags = const [],',
        '  });',
        '',
        '  final String name;',
        '  final DsIconData icon;',
        '  final String category;',
        '  final List<String> aliases;',
        '  final List<String> tags;',
        '}',
        '',
        '/// Every built-in icon, by category, then by name.',
        'const iconCatalog = <IconEntry>[',
    ]
    lines += [f'  ..._{camel(c)},' for c in categories]
    lines += ['];', '']
    files[SITE] = '\n'.join(lines)
    for category in categories:
        lines = [HEADER, '', "part of '../icon_catalog.dart';", '',
                 f'const _{camel(category)} = <IconEntry>[']
        for icon in by_category[category]:
            args = [dart_str(icon['name']), f'DsIcons.{icon["name"]}',
                    f'category: {dart_str(category)}']
            if icon['aliases']:
                args.append('aliases: [' + ', '.join(dart_str(a) for a in icon['aliases']) + ']')
            if icon['tags']:
                args.append('tags: [' + ', '.join(dart_str(t) for t in icon['tags']) + ']')
            lines.append(f'  IconEntry({", ".join(args)}),')
        lines += ['];', '']
        files[f'{SITE_SET}/{file_name(category)}.dart'] = '\n'.join(lines)
    return files


def write_formatted(files, root):
    for rel, text in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as fh:
            fh.write(text + '\n')
    run = subprocess.run(
        ['dart', 'format', '-o', 'write', *[os.path.join(root, r) for r in files]],
        capture_output=True, text=True)
    if run.returncode != 0:
        raise SystemExit('dart format failed:\n' + run.stderr[-3000:])


def main():
    check = '--check' in sys.argv[1:]
    icons = load()
    files = generate(icons)
    with tempfile.TemporaryDirectory() as tmp:
        write_formatted(files, tmp)
        stale = []
        for rel in files:
            with open(os.path.join(tmp, rel)) as fh:
                new = fh.read()
            dest = os.path.join(ROOT, rel)
            old = open(dest).read() if os.path.exists(dest) else None
            if old != new:
                stale.append(rel)
                if not check:
                    os.makedirs(os.path.dirname(dest), exist_ok=True)
                    shutil.copyfile(os.path.join(tmp, rel), dest)
        for folder in (LIB_SET, SITE_SET):
            full = os.path.join(ROOT, folder)
            if not os.path.isdir(full):
                continue
            for fn in os.listdir(full):
                rel = f'{folder}/{fn}'
                if rel not in files:
                    stale.append(rel)
                    if not check:
                        os.remove(os.path.join(full, fn))
    if check:
        if stale:
            print('Out of date (run python3 tool/gen_icons.py):', *stale, sep='\n  ')
            return 1
        print(f'{len(icons)} icons, generated files up to date')
        return 0
    aliases = sum(len(i['aliases']) for i in icons)
    print(f'{len(icons)} icons, {aliases} aliases, {len(stale)} files written')
    return 0


if __name__ == '__main__':
    sys.exit(main())
