// GENERATED by tool/gen_colors.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/painting.dart';

import '../foundation/color_utils.dart';

/// The colors for one status (danger, success, warning, info, neutral).
@immutable
class DsStatusColors {
  /// Creates status colors.
  ///
  /// Building them by hand is meant for tests and tools. It is not covered
  /// by the compatibility promise: later versions may add fields. To change
  /// a status, use `DsThemeData(adjustColors: …)` with [copyWith].
  const DsStatusColors({
    required this.fill,
    required this.fillHover,
    required this.fillPress,
    required this.onFill,
    required this.tint,
    required this.tintHover,
    required this.tintPress,
    required this.text,
    required this.signal,
  });

  /// Solid fill, e.g. a destructive button or a count bubble.
  final Color fill;

  /// [fill] while hovered: a step away from [onFill].
  final Color fillHover;

  /// [fill] while pressed: one step beyond [fillHover].
  final Color fillPress;

  /// Icons and text on [fill].
  ///
  /// Danger reaches 4.5:1 for body text. Success, warning and info fills are
  /// meant for icons, dots and bold labels, and guarantee 3:1 (WCAG 1.4.11).
  final Color onFill;

  /// Soft background: badges, light-mode alerts, soft buttons. Opaque.
  final Color tint;

  /// [tint] while hovered.
  final Color tintHover;

  /// [tint] while pressed: one step beyond [tintHover].
  final Color tintPress;

  /// Status-colored text on a surface or on [tint].
  final Color text;

  /// Vivid status color for marks with no text on them: status dots, alert
  /// and toast icons, status icons in lists. Stands 3:1 off the canvas, the
  /// surface and floating layers (WCAG 1.4.11), and in light mode off
  /// [tint] too. Not for text: use [text].
  final Color signal;

  /// Returns a copy with the given fields replaced.
  DsStatusColors copyWith({
    Color? fill,
    Color? fillHover,
    Color? fillPress,
    Color? onFill,
    Color? tint,
    Color? tintHover,
    Color? tintPress,
    Color? text,
    Color? signal,
  }) => DsStatusColors(
    fill: fill ?? this.fill,
    fillHover: fillHover ?? this.fillHover,
    fillPress: fillPress ?? this.fillPress,
    onFill: onFill ?? this.onFill,
    tint: tint ?? this.tint,
    tintHover: tintHover ?? this.tintHover,
    tintPress: tintPress ?? this.tintPress,
    text: text ?? this.text,
    signal: signal ?? this.signal,
  );

  /// Linearly interpolates between two sets.
  static DsStatusColors lerp(DsStatusColors a, DsStatusColors b, double t) {
    if (identical(a, b)) return a;
    return DsStatusColors(
      fill: DsColorUtils.lerp(a.fill, b.fill, t)!,
      fillHover: DsColorUtils.lerp(a.fillHover, b.fillHover, t)!,
      fillPress: DsColorUtils.lerp(a.fillPress, b.fillPress, t)!,
      onFill: DsColorUtils.lerp(a.onFill, b.onFill, t)!,
      tint: DsColorUtils.lerp(a.tint, b.tint, t)!,
      tintHover: DsColorUtils.lerp(a.tintHover, b.tintHover, t)!,
      tintPress: DsColorUtils.lerp(a.tintPress, b.tintPress, t)!,
      text: DsColorUtils.lerp(a.text, b.text, t)!,
      signal: DsColorUtils.lerp(a.signal, b.signal, t)!,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsStatusColors &&
      other.fill == fill &&
      other.fillHover == fillHover &&
      other.fillPress == fillPress &&
      other.onFill == onFill &&
      other.tint == tint &&
      other.tintHover == tintHover &&
      other.tintPress == tintPress &&
      other.text == text &&
      other.signal == signal;

  @override
  int get hashCode => Object.hash(
    fill,
    fillHover,
    fillPress,
    onFill,
    tint,
    tintHover,
    tintPress,
    text,
    signal,
  );
}

/// Every color role in a Desen theme.
///
/// Generated by the theme from its seed: read them from
/// `DsThemeData(seed: …).colors` or `DsTheme.colorsOf(context)`. Every
/// role can be replaced with [copyWith]. Component code reads colors only
/// from here, never from literals.
///
/// Translucent roles ([hover], [press], [border], tints…) are meant to be
/// layered on top of a surface, so they adapt to whatever is underneath.
@immutable
class DsColors {
  /// Creates a color set with every role given.
  ///
  /// Building one by hand is meant for tests and tools. It is not covered
  /// by the compatibility promise: later versions may add roles. To
  /// customize colors, use `DsThemeData(adjustColors: …)` with [copyWith]
  /// on the generated set (`DsThemeData(seed: …).colors`).
  const DsColors({
    required this.canvas,
    required this.surface,
    required this.sidebar,
    required this.control,
    required this.controlHover,
    required this.controlPress,
    required this.overlay,
    required this.field,
    required this.text,
    required this.textMuted,
    required this.textSubtle,
    required this.accent,
    required this.accentHover,
    required this.accentPress,
    required this.onAccent,
    required this.accentEdge,
    required this.indicator,
    required this.accentTint,
    required this.accentText,
    required this.link,
    required this.selection,
    required this.selectionHover,
    required this.onSelection,
    required this.selectionStrong,
    required this.selectionStrongHover,
    required this.onSelectionStrong,
    required this.focus,
    required this.border,
    required this.borderControl,
    required this.borderField,
    required this.borderChip,
    required this.channel,
    required this.channelStrong,
    required this.rail,
    required this.channelThumb,
    required this.knob,
    required this.shimmer,
    required this.hover,
    required this.press,
    required this.disabled,
    required this.onDisabled,
    required this.scrim,
    required this.tooltip,
    required this.onTooltip,
    required this.onTooltipMuted,
    required this.neutral,
    required this.danger,
    required this.success,
    required this.warning,
    required this.info,
  });

  // Surfaces

  /// Page background, the lowest layer.
  final Color canvas;

  /// Cards, list groups, tables.
  final Color surface;

  /// Side navigation background.
  final Color sidebar;

  /// Secondary buttons and other raised controls.
  final Color control;

  /// [control] while hovered.
  final Color controlHover;

  /// [control] while pressed: one step beyond [controlHover].
  final Color controlPress;

  /// Floating layers: menus, popovers, toasts, dialogs.
  final Color overlay;

  /// Text field and checkbox well.
  final Color field;

  // Text

  /// Primary text.
  final Color text;

  /// Secondary text, field labels.
  final Color textMuted;

  /// Tertiary text, placeholders, meta.
  final Color textSubtle;

  // Accent

  /// Brand fill: primary button, checked controls, switch track. Usually labeled white; a light brand (yellow, orange, sky) keeps its own bright fill with a dark [onAccent] instead.
  final Color accent;

  /// [accent] while hovered: a step away from [onAccent].
  final Color accentHover;

  /// [accent] while pressed: one step beyond [accentHover], further from [onAccent].
  final Color accentPress;

  /// Text and icons on [accent]: white, or a dark ink tinted toward the seed on a bright accent.
  final Color onAccent;

  /// 1px edge of an [accent] fill that stands under 3:1 off the surfaces it sits on: a bright accent (dark [onAccent]). Checked checkboxes and radios, the switch's on track and filled selections draw it inside their fill, so their shape does not melt into a white card (WCAG 1.4.11). The dark label at the lowest opacity that brings the edge to 3:1, hover and press included; transparent when the fill stands on its own.
  final Color accentEdge;

  /// Accent marks with no label on them: progress and slider fill, tab underline, text caret. [accent] in light mode (darkened under a bright accent), a lighter accent in dark mode. Stands 3:1 off [channelStrong], the surface and the field.
  final Color indicator;

  /// Translucent accent wash, e.g. date range band.
  final Color accentTint;

  /// Accent used as text, e.g. today in a calendar.
  final Color accentText;

  /// Links and text buttons.
  final Color link;

  // Selection

  /// Soft selection background (chips, menu rows, nav items).
  final Color selection;

  /// [selection] while hovered or keyboard focused: a stronger tint, so focus stays visible on a selected item.
  final Color selectionHover;

  /// Text on [selection] and [selectionHover].
  final Color onSelection;

  /// Filled selection background.
  final Color selectionStrong;

  /// [selectionStrong] while hovered or keyboard focused; darkens under its light label.
  final Color selectionStrongHover;

  /// Text on [selectionStrong] and [selectionStrongHover].
  final Color onSelectionStrong;

  // Focus

  /// Keyboard focus outline. Stands 3:1 off the page and the surfaces.
  final Color focus;

  // Lines

  /// Dividers and container outlines.
  final Color border;

  /// Edge of raised controls.
  final Color borderControl;

  /// Inner outline of text fields and checkboxes: 3:1 at standard contrast; a light edge (about 1.5:1) at soft contrast.
  final Color borderField;

  /// Outline of unselected chips.
  final Color borderChip;

  // Channels and rails

  /// Recessed channel of segmented controls and steppers; skeleton blocks. May be translucent; layer it on a surface.
  final Color channel;

  /// A step stronger than [channel]: the unfilled part of slider and progress tracks, strong skeleton lines, and small neutral fills such as the sheet grabber.
  final Color channelStrong;

  /// The switch's track while off. Meets 3:1 against surfaces (WCAG 1.4.11) at standard contrast, unlike the decorative channels; a light, iOS-like fill at soft contrast.
  final Color rail;

  /// The raised piece in a [channel]: the selected segment of a soft segmented control, stepper buttons.
  final Color channelThumb;

  /// Switch knob and slider thumb.
  final Color knob;

  /// Highlight swept across skeletons while loading.
  final Color shimmer;

  // Interaction

  /// Translucent hover layer.
  final Color hover;

  /// Translucent pressed layer.
  final Color press;

  /// Disabled control background.
  final Color disabled;

  /// Disabled text and icons.
  final Color onDisabled;

  /// Modal barrier.
  final Color scrim;

  // Tooltip

  /// Tooltip background.
  final Color tooltip;

  /// Tooltip text.
  final Color onTooltip;

  /// Secondary tooltip text, e.g. shortcuts.
  final Color onTooltipMuted;

  // Status

  /// Neutral badges.
  final DsStatusColors neutral;

  /// Errors and destructive actions.
  final DsStatusColors danger;

  /// Success.
  final DsStatusColors success;

  /// Warnings.
  final DsStatusColors warning;

  /// Information.
  final DsStatusColors info;

  /// Returns a copy with the given roles replaced.
  DsColors copyWith({
    Color? canvas,
    Color? surface,
    Color? sidebar,
    Color? control,
    Color? controlHover,
    Color? controlPress,
    Color? overlay,
    Color? field,
    Color? text,
    Color? textMuted,
    Color? textSubtle,
    Color? accent,
    Color? accentHover,
    Color? accentPress,
    Color? onAccent,
    Color? accentEdge,
    Color? indicator,
    Color? accentTint,
    Color? accentText,
    Color? link,
    Color? selection,
    Color? selectionHover,
    Color? onSelection,
    Color? selectionStrong,
    Color? selectionStrongHover,
    Color? onSelectionStrong,
    Color? focus,
    Color? border,
    Color? borderControl,
    Color? borderField,
    Color? borderChip,
    Color? channel,
    Color? channelStrong,
    Color? rail,
    Color? channelThumb,
    Color? knob,
    Color? shimmer,
    Color? hover,
    Color? press,
    Color? disabled,
    Color? onDisabled,
    Color? scrim,
    Color? tooltip,
    Color? onTooltip,
    Color? onTooltipMuted,
    DsStatusColors? neutral,
    DsStatusColors? danger,
    DsStatusColors? success,
    DsStatusColors? warning,
    DsStatusColors? info,
  }) => DsColors(
    canvas: canvas ?? this.canvas,
    surface: surface ?? this.surface,
    sidebar: sidebar ?? this.sidebar,
    control: control ?? this.control,
    controlHover: controlHover ?? this.controlHover,
    controlPress: controlPress ?? this.controlPress,
    overlay: overlay ?? this.overlay,
    field: field ?? this.field,
    text: text ?? this.text,
    textMuted: textMuted ?? this.textMuted,
    textSubtle: textSubtle ?? this.textSubtle,
    accent: accent ?? this.accent,
    accentHover: accentHover ?? this.accentHover,
    accentPress: accentPress ?? this.accentPress,
    onAccent: onAccent ?? this.onAccent,
    accentEdge: accentEdge ?? this.accentEdge,
    indicator: indicator ?? this.indicator,
    accentTint: accentTint ?? this.accentTint,
    accentText: accentText ?? this.accentText,
    link: link ?? this.link,
    selection: selection ?? this.selection,
    selectionHover: selectionHover ?? this.selectionHover,
    onSelection: onSelection ?? this.onSelection,
    selectionStrong: selectionStrong ?? this.selectionStrong,
    selectionStrongHover: selectionStrongHover ?? this.selectionStrongHover,
    onSelectionStrong: onSelectionStrong ?? this.onSelectionStrong,
    focus: focus ?? this.focus,
    border: border ?? this.border,
    borderControl: borderControl ?? this.borderControl,
    borderField: borderField ?? this.borderField,
    borderChip: borderChip ?? this.borderChip,
    channel: channel ?? this.channel,
    channelStrong: channelStrong ?? this.channelStrong,
    rail: rail ?? this.rail,
    channelThumb: channelThumb ?? this.channelThumb,
    knob: knob ?? this.knob,
    shimmer: shimmer ?? this.shimmer,
    hover: hover ?? this.hover,
    press: press ?? this.press,
    disabled: disabled ?? this.disabled,
    onDisabled: onDisabled ?? this.onDisabled,
    scrim: scrim ?? this.scrim,
    tooltip: tooltip ?? this.tooltip,
    onTooltip: onTooltip ?? this.onTooltip,
    onTooltipMuted: onTooltipMuted ?? this.onTooltipMuted,
    neutral: neutral ?? this.neutral,
    danger: danger ?? this.danger,
    success: success ?? this.success,
    warning: warning ?? this.warning,
    info: info ?? this.info,
  );

  /// Every role as a flat map, status sets expanded (`danger.fill`, …).
  /// Keys are the field names; useful for export, debugging and snapshots.
  Map<String, Color> toMap() => {
    'canvas': canvas,
    'surface': surface,
    'sidebar': sidebar,
    'control': control,
    'controlHover': controlHover,
    'controlPress': controlPress,
    'overlay': overlay,
    'field': field,
    'text': text,
    'textMuted': textMuted,
    'textSubtle': textSubtle,
    'accent': accent,
    'accentHover': accentHover,
    'accentPress': accentPress,
    'onAccent': onAccent,
    'accentEdge': accentEdge,
    'indicator': indicator,
    'accentTint': accentTint,
    'accentText': accentText,
    'link': link,
    'selection': selection,
    'selectionHover': selectionHover,
    'onSelection': onSelection,
    'selectionStrong': selectionStrong,
    'selectionStrongHover': selectionStrongHover,
    'onSelectionStrong': onSelectionStrong,
    'focus': focus,
    'border': border,
    'borderControl': borderControl,
    'borderField': borderField,
    'borderChip': borderChip,
    'channel': channel,
    'channelStrong': channelStrong,
    'rail': rail,
    'channelThumb': channelThumb,
    'knob': knob,
    'shimmer': shimmer,
    'hover': hover,
    'press': press,
    'disabled': disabled,
    'onDisabled': onDisabled,
    'scrim': scrim,
    'tooltip': tooltip,
    'onTooltip': onTooltip,
    'onTooltipMuted': onTooltipMuted,
    'neutral.fill': neutral.fill,
    'neutral.fillHover': neutral.fillHover,
    'neutral.fillPress': neutral.fillPress,
    'neutral.onFill': neutral.onFill,
    'neutral.tint': neutral.tint,
    'neutral.tintHover': neutral.tintHover,
    'neutral.tintPress': neutral.tintPress,
    'neutral.text': neutral.text,
    'neutral.signal': neutral.signal,
    'danger.fill': danger.fill,
    'danger.fillHover': danger.fillHover,
    'danger.fillPress': danger.fillPress,
    'danger.onFill': danger.onFill,
    'danger.tint': danger.tint,
    'danger.tintHover': danger.tintHover,
    'danger.tintPress': danger.tintPress,
    'danger.text': danger.text,
    'danger.signal': danger.signal,
    'success.fill': success.fill,
    'success.fillHover': success.fillHover,
    'success.fillPress': success.fillPress,
    'success.onFill': success.onFill,
    'success.tint': success.tint,
    'success.tintHover': success.tintHover,
    'success.tintPress': success.tintPress,
    'success.text': success.text,
    'success.signal': success.signal,
    'warning.fill': warning.fill,
    'warning.fillHover': warning.fillHover,
    'warning.fillPress': warning.fillPress,
    'warning.onFill': warning.onFill,
    'warning.tint': warning.tint,
    'warning.tintHover': warning.tintHover,
    'warning.tintPress': warning.tintPress,
    'warning.text': warning.text,
    'warning.signal': warning.signal,
    'info.fill': info.fill,
    'info.fillHover': info.fillHover,
    'info.fillPress': info.fillPress,
    'info.onFill': info.onFill,
    'info.tint': info.tint,
    'info.tintHover': info.tintHover,
    'info.tintPress': info.tintPress,
    'info.text': info.text,
    'info.signal': info.signal,
  };

  /// Linearly interpolates between two color sets.
  static DsColors lerp(DsColors a, DsColors b, double t) {
    if (identical(a, b)) return a;
    return DsColors(
      canvas: DsColorUtils.lerp(a.canvas, b.canvas, t)!,
      surface: DsColorUtils.lerp(a.surface, b.surface, t)!,
      sidebar: DsColorUtils.lerp(a.sidebar, b.sidebar, t)!,
      control: DsColorUtils.lerp(a.control, b.control, t)!,
      controlHover: DsColorUtils.lerp(a.controlHover, b.controlHover, t)!,
      controlPress: DsColorUtils.lerp(a.controlPress, b.controlPress, t)!,
      overlay: DsColorUtils.lerp(a.overlay, b.overlay, t)!,
      field: DsColorUtils.lerp(a.field, b.field, t)!,
      text: DsColorUtils.lerp(a.text, b.text, t)!,
      textMuted: DsColorUtils.lerp(a.textMuted, b.textMuted, t)!,
      textSubtle: DsColorUtils.lerp(a.textSubtle, b.textSubtle, t)!,
      accent: DsColorUtils.lerp(a.accent, b.accent, t)!,
      accentHover: DsColorUtils.lerp(a.accentHover, b.accentHover, t)!,
      accentPress: DsColorUtils.lerp(a.accentPress, b.accentPress, t)!,
      onAccent: DsColorUtils.lerp(a.onAccent, b.onAccent, t)!,
      accentEdge: DsColorUtils.lerp(a.accentEdge, b.accentEdge, t)!,
      indicator: DsColorUtils.lerp(a.indicator, b.indicator, t)!,
      accentTint: DsColorUtils.lerp(a.accentTint, b.accentTint, t)!,
      accentText: DsColorUtils.lerp(a.accentText, b.accentText, t)!,
      link: DsColorUtils.lerp(a.link, b.link, t)!,
      selection: DsColorUtils.lerp(a.selection, b.selection, t)!,
      selectionHover: DsColorUtils.lerp(a.selectionHover, b.selectionHover, t)!,
      onSelection: DsColorUtils.lerp(a.onSelection, b.onSelection, t)!,
      selectionStrong: DsColorUtils.lerp(
        a.selectionStrong,
        b.selectionStrong,
        t,
      )!,
      selectionStrongHover: DsColorUtils.lerp(
        a.selectionStrongHover,
        b.selectionStrongHover,
        t,
      )!,
      onSelectionStrong: DsColorUtils.lerp(
        a.onSelectionStrong,
        b.onSelectionStrong,
        t,
      )!,
      focus: DsColorUtils.lerp(a.focus, b.focus, t)!,
      border: DsColorUtils.lerp(a.border, b.border, t)!,
      borderControl: DsColorUtils.lerp(a.borderControl, b.borderControl, t)!,
      borderField: DsColorUtils.lerp(a.borderField, b.borderField, t)!,
      borderChip: DsColorUtils.lerp(a.borderChip, b.borderChip, t)!,
      channel: DsColorUtils.lerp(a.channel, b.channel, t)!,
      channelStrong: DsColorUtils.lerp(a.channelStrong, b.channelStrong, t)!,
      rail: DsColorUtils.lerp(a.rail, b.rail, t)!,
      channelThumb: DsColorUtils.lerp(a.channelThumb, b.channelThumb, t)!,
      knob: DsColorUtils.lerp(a.knob, b.knob, t)!,
      shimmer: DsColorUtils.lerp(a.shimmer, b.shimmer, t)!,
      hover: DsColorUtils.lerp(a.hover, b.hover, t)!,
      press: DsColorUtils.lerp(a.press, b.press, t)!,
      disabled: DsColorUtils.lerp(a.disabled, b.disabled, t)!,
      onDisabled: DsColorUtils.lerp(a.onDisabled, b.onDisabled, t)!,
      scrim: DsColorUtils.lerp(a.scrim, b.scrim, t)!,
      tooltip: DsColorUtils.lerp(a.tooltip, b.tooltip, t)!,
      onTooltip: DsColorUtils.lerp(a.onTooltip, b.onTooltip, t)!,
      onTooltipMuted: DsColorUtils.lerp(a.onTooltipMuted, b.onTooltipMuted, t)!,
      neutral: DsStatusColors.lerp(a.neutral, b.neutral, t),
      danger: DsStatusColors.lerp(a.danger, b.danger, t),
      success: DsStatusColors.lerp(a.success, b.success, t),
      warning: DsStatusColors.lerp(a.warning, b.warning, t),
      info: DsStatusColors.lerp(a.info, b.info, t),
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsColors &&
      other.canvas == canvas &&
      other.surface == surface &&
      other.sidebar == sidebar &&
      other.control == control &&
      other.controlHover == controlHover &&
      other.controlPress == controlPress &&
      other.overlay == overlay &&
      other.field == field &&
      other.text == text &&
      other.textMuted == textMuted &&
      other.textSubtle == textSubtle &&
      other.accent == accent &&
      other.accentHover == accentHover &&
      other.accentPress == accentPress &&
      other.onAccent == onAccent &&
      other.accentEdge == accentEdge &&
      other.indicator == indicator &&
      other.accentTint == accentTint &&
      other.accentText == accentText &&
      other.link == link &&
      other.selection == selection &&
      other.selectionHover == selectionHover &&
      other.onSelection == onSelection &&
      other.selectionStrong == selectionStrong &&
      other.selectionStrongHover == selectionStrongHover &&
      other.onSelectionStrong == onSelectionStrong &&
      other.focus == focus &&
      other.border == border &&
      other.borderControl == borderControl &&
      other.borderField == borderField &&
      other.borderChip == borderChip &&
      other.channel == channel &&
      other.channelStrong == channelStrong &&
      other.rail == rail &&
      other.channelThumb == channelThumb &&
      other.knob == knob &&
      other.shimmer == shimmer &&
      other.hover == hover &&
      other.press == press &&
      other.disabled == disabled &&
      other.onDisabled == onDisabled &&
      other.scrim == scrim &&
      other.tooltip == tooltip &&
      other.onTooltip == onTooltip &&
      other.onTooltipMuted == onTooltipMuted &&
      other.neutral == neutral &&
      other.danger == danger &&
      other.success == success &&
      other.warning == warning &&
      other.info == info;

  @override
  int get hashCode => Object.hashAll([
    canvas,
    surface,
    sidebar,
    control,
    controlHover,
    controlPress,
    overlay,
    field,
    text,
    textMuted,
    textSubtle,
    accent,
    accentHover,
    accentPress,
    onAccent,
    accentEdge,
    indicator,
    accentTint,
    accentText,
    link,
    selection,
    selectionHover,
    onSelection,
    selectionStrong,
    selectionStrongHover,
    onSelectionStrong,
    focus,
    border,
    borderControl,
    borderField,
    borderChip,
    channel,
    channelStrong,
    rail,
    channelThumb,
    knob,
    shimmer,
    hover,
    press,
    disabled,
    onDisabled,
    scrim,
    tooltip,
    onTooltip,
    onTooltipMuted,
    neutral,
    danger,
    success,
    warning,
    info,
  ]);
}
