// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsReorderableList`: the drag handle beside each item (resolved for its own states) and the item while it is lifted.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsReorderableListStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsReorderableListStyle with Diagnosticable {
  /// Creates a style.
  const DsReorderableListStyle({
    this.handleColor,
    this.handleSize,
    this.handleGap,
    this.liftedBackground,
    this.liftedShadows,
    this.liftedBorderRadius,
    this.liftedScale,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.disabled,
  });

  /// Grip icon color.
  final Color? handleColor;

  /// Grip icon size.
  final double? handleSize;

  /// Space on each side of the handle: between it and the item, and between it and the list's end edge.
  final double? handleGap;

  /// Fill of the lifted item, so it covers the items it passes over.
  final Color? liftedBackground;

  /// Shadow of the lifted item.
  final List<DsShadow>? liftedShadows;

  /// Corners of the lifted item.
  final BorderRadiusGeometry? liftedBorderRadius;

  /// How much the lifted item grows, 1 for none; ignored under reduced motion.
  final double? liftedScale;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsReorderableListStyle? focused;

  /// Laid over the base while hovered.
  final DsReorderableListStyle? hovered;

  /// Laid over the base while pressed.
  final DsReorderableListStyle? pressed;

  /// Laid over the base while disabled.
  final DsReorderableListStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsReorderableListStyle merge(DsReorderableListStyle? other) {
    if (other == null) return this;
    return DsReorderableListStyle(
      handleColor: other.handleColor ?? handleColor,
      handleSize: other.handleSize ?? handleSize,
      handleGap: other.handleGap ?? handleGap,
      liftedBackground: other.liftedBackground ?? liftedBackground,
      liftedShadows: other.liftedShadows ?? liftedShadows,
      liftedBorderRadius: other.liftedBorderRadius ?? liftedBorderRadius,
      liftedScale: other.liftedScale ?? liftedScale,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsReorderableListStyle get _base => DsReorderableListStyle(
    handleColor: handleColor,
    handleSize: handleSize,
    handleGap: handleGap,
    liftedBackground: liftedBackground,
    liftedShadows: liftedShadows,
    liftedBorderRadius: liftedBorderRadius,
    liftedScale: liftedScale,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsReorderableListStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsReorderableListStyle resolveLayers(
    Iterable<DsReorderableListStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsReorderableListStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    handleColor,
    handleSize,
    handleGap,
    liftedBackground,
    liftedShadows,
    liftedBorderRadius,
    liftedScale,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsReorderableListStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(
      ColorProperty('handleColor', handleColor, defaultValue: null),
    );
    properties.add(
      DoubleProperty('handleSize', handleSize, defaultValue: null),
    );
    properties.add(DoubleProperty('handleGap', handleGap, defaultValue: null));
    properties.add(
      ColorProperty('liftedBackground', liftedBackground, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('liftedShadows', liftedShadows, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty(
        'liftedBorderRadius',
        liftedBorderRadius,
        defaultValue: null,
      ),
    );
    properties.add(
      DoubleProperty('liftedScale', liftedScale, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsReorderableList` in a subtree; see [DsReorderableListTheme].
class DsReorderableListThemeData
    extends DsComponentThemeData<DsReorderableListThemeData> {
  /// Creates defaults.
  const DsReorderableListThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsReorderableListStyle? style;

  @override
  DsReorderableListThemeData merge(DsReorderableListThemeData? other) {
    if (other == null) return this;
    return DsReorderableListThemeData(
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsReorderableListThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsReorderableListThemeData] to a subtree, merged over any outer one.
class DsReorderableListTheme
    extends DsComponentTheme<DsReorderableListThemeData> {
  /// Applies [data] to [child].
  const DsReorderableListTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsReorderableListThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsReorderableListThemeData>(context) ??
      const DsReorderableListThemeData();
}
