// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsStepper`. `disabled` also styles a button at its limit.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsStepperStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsStepperStyle with Diagnosticable {
  /// Creates a style.
  const DsStepperStyle({
    this.height,
    this.inset,
    this.trackColor,
    this.trackShadows,
    this.borderRadius,
    this.buttonWidth,
    this.buttonColor,
    this.buttonShadows,
    this.buttonRadius,
    this.foreground,
    this.iconSize,
    this.valueWidth,
    this.valueStyle,
    this.unitStyle,
    this.unitGap,
    this.pressScale,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.disabled,
  });

  /// Button height.
  final double? height;

  /// Space between the track edge and the buttons.
  final double? inset;

  /// Track fill.
  final Color? trackColor;

  /// Track edge.
  final List<DsShadow>? trackShadows;

  /// Track corners. When no layer sets them, the track is rounded as a control of its height (`height` plus `inset` on each side, `DsRadii.controlCorners`), so a style that changes only the height or the inset keeps them in proportion.
  final BorderRadiusGeometry? borderRadius;

  /// Width of the minus and plus buttons.
  final double? buttonWidth;

  /// Button fill.
  final Color? buttonColor;

  /// Button edge and lift.
  final List<DsShadow>? buttonShadows;

  /// Button corners. When no layer sets them, concentric with the track corners (`DsRadii.nestedCorners` by `inset`).
  final BorderRadiusGeometry? buttonRadius;

  /// Icon and value color.
  final Color? foreground;

  /// Minus and plus icon size.
  final double? iconSize;

  /// Fixed width of the value, so the control does not jump.
  final double? valueWidth;

  /// Value style, merged (tabular figures).
  final TextStyle? valueStyle;

  /// Unit and prefix text, merged.
  final TextStyle? unitStyle;

  /// Space between the number and its unit or prefix.
  final double? unitGap;

  /// Button scale while pressed; `DsPressEffect` can turn it off.
  final double? pressScale;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsStepperStyle? focused;

  /// Laid over the base while hovered.
  final DsStepperStyle? hovered;

  /// Laid over the base while pressed.
  final DsStepperStyle? pressed;

  /// Laid over the base while disabled.
  final DsStepperStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsStepperStyle merge(DsStepperStyle? other) {
    if (other == null) return this;
    return DsStepperStyle(
      height: other.height ?? height,
      inset: other.inset ?? inset,
      trackColor: other.trackColor ?? trackColor,
      trackShadows: other.trackShadows ?? trackShadows,
      borderRadius: other.borderRadius ?? borderRadius,
      buttonWidth: other.buttonWidth ?? buttonWidth,
      buttonColor: other.buttonColor ?? buttonColor,
      buttonShadows: other.buttonShadows ?? buttonShadows,
      buttonRadius: other.buttonRadius ?? buttonRadius,
      foreground: other.foreground ?? foreground,
      iconSize: other.iconSize ?? iconSize,
      valueWidth: other.valueWidth ?? valueWidth,
      valueStyle: valueStyle?.merge(other.valueStyle) ?? other.valueStyle,
      unitStyle: unitStyle?.merge(other.unitStyle) ?? other.unitStyle,
      unitGap: other.unitGap ?? unitGap,
      pressScale: other.pressScale ?? pressScale,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsStepperStyle get _base => DsStepperStyle(
    height: height,
    inset: inset,
    trackColor: trackColor,
    trackShadows: trackShadows,
    borderRadius: borderRadius,
    buttonWidth: buttonWidth,
    buttonColor: buttonColor,
    buttonShadows: buttonShadows,
    buttonRadius: buttonRadius,
    foreground: foreground,
    iconSize: iconSize,
    valueWidth: valueWidth,
    valueStyle: valueStyle,
    unitStyle: unitStyle,
    unitGap: unitGap,
    pressScale: pressScale,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsStepperStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsStepperStyle resolveLayers(
    Iterable<DsStepperStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsStepperStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    height,
    inset,
    trackColor,
    trackShadows,
    borderRadius,
    buttonWidth,
    buttonColor,
    buttonShadows,
    buttonRadius,
    foreground,
    iconSize,
    valueWidth,
    valueStyle,
    unitStyle,
    unitGap,
    pressScale,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsStepperStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(DoubleProperty('inset', inset, defaultValue: null));
    properties.add(ColorProperty('trackColor', trackColor, defaultValue: null));
    properties.add(
      DiagnosticsProperty('trackShadows', trackShadows, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(
      DoubleProperty('buttonWidth', buttonWidth, defaultValue: null),
    );
    properties.add(
      ColorProperty('buttonColor', buttonColor, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('buttonShadows', buttonShadows, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('buttonRadius', buttonRadius, defaultValue: null),
    );
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(
      DoubleProperty('valueWidth', valueWidth, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('valueStyle', valueStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('unitStyle', unitStyle, defaultValue: null),
    );
    properties.add(DoubleProperty('unitGap', unitGap, defaultValue: null));
    properties.add(
      DoubleProperty('pressScale', pressScale, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsStepper` in a subtree; see [DsStepperTheme].
class DsStepperThemeData extends DsComponentThemeData<DsStepperThemeData> {
  /// Creates defaults.
  const DsStepperThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsStepperStyle? style;

  @override
  DsStepperThemeData merge(DsStepperThemeData? other) {
    if (other == null) return this;
    return DsStepperThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsStepperThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsStepperThemeData] to a subtree, merged over any outer one.
class DsStepperTheme extends DsComponentTheme<DsStepperThemeData> {
  /// Applies [data] to [child].
  const DsStepperTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsStepperThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsStepperThemeData>(context) ??
      const DsStepperThemeData();
}
