// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsSectionIndex`. Each letter resolves for its own states (hovered, pressed, focused, selected); the bar, the dots and the bubble use the plain style, or the disabled one.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsSectionIndexStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsSectionIndexStyle with Diagnosticable {
  /// Creates a style.
  const DsSectionIndexStyle({
    this.width,
    this.letterHeight,
    this.textStyle,
    this.color,
    this.background,
    this.markerSize,
    this.dotSize,
    this.bubbleSize,
    this.bubbleGap,
    this.bubbleColor,
    this.bubbleTextStyle,
    this.bubbleShadows,
    this.bubbleRadius,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
    this.disabled,
  });

  /// Width of the bar; at least the theme's `minTapTarget`, so a finger reaches the letters across it.
  final double? width;

  /// Height of one letter at text scale 1; it grows with the text. Letters that do not fit give way to dots.
  final double? letterHeight;

  /// Letter style, merged.
  final TextStyle? textStyle;

  /// Letter and dot color.
  final Color? color;

  /// Fill behind a letter: the current section, a hovered letter.
  final Color? background;

  /// Diameter of the fill behind a letter.
  final double? markerSize;

  /// Diameter of a dot that stands for letters that do not fit.
  final double? dotSize;

  /// Width and height of the bubble that shows the letter under the pointer.
  final double? bubbleSize;

  /// Space between the bar and the bubble.
  final double? bubbleGap;

  /// Bubble fill.
  final Color? bubbleColor;

  /// Bubble letter style, merged.
  final TextStyle? bubbleTextStyle;

  /// Bubble shadow.
  final List<DsShadow>? bubbleShadows;

  /// Bubble corners. When no layer sets them, rounded as a control of `bubbleSize`, so a style that changes only the size keeps them in proportion.
  final BorderRadiusGeometry? bubbleRadius;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsSectionIndexStyle? focused;

  /// Laid over the base while hovered.
  final DsSectionIndexStyle? hovered;

  /// Laid over the base while pressed.
  final DsSectionIndexStyle? pressed;

  /// Laid over the base while selected.
  final DsSectionIndexStyle? selected;

  /// Laid over the base while disabled.
  final DsSectionIndexStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsSectionIndexStyle merge(DsSectionIndexStyle? other) {
    if (other == null) return this;
    return DsSectionIndexStyle(
      width: other.width ?? width,
      letterHeight: other.letterHeight ?? letterHeight,
      textStyle: textStyle?.merge(other.textStyle) ?? other.textStyle,
      color: other.color ?? color,
      background: other.background ?? background,
      markerSize: other.markerSize ?? markerSize,
      dotSize: other.dotSize ?? dotSize,
      bubbleSize: other.bubbleSize ?? bubbleSize,
      bubbleGap: other.bubbleGap ?? bubbleGap,
      bubbleColor: other.bubbleColor ?? bubbleColor,
      bubbleTextStyle:
          bubbleTextStyle?.merge(other.bubbleTextStyle) ??
          other.bubbleTextStyle,
      bubbleShadows: other.bubbleShadows ?? bubbleShadows,
      bubbleRadius: other.bubbleRadius ?? bubbleRadius,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsSectionIndexStyle get _base => DsSectionIndexStyle(
    width: width,
    letterHeight: letterHeight,
    textStyle: textStyle,
    color: color,
    background: background,
    markerSize: markerSize,
    dotSize: dotSize,
    bubbleSize: bubbleSize,
    bubbleGap: bubbleGap,
    bubbleColor: bubbleColor,
    bubbleTextStyle: bubbleTextStyle,
    bubbleShadows: bubbleShadows,
    bubbleRadius: bubbleRadius,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsSectionIndexStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsSectionIndexStyle resolveLayers(
    Iterable<DsSectionIndexStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsSectionIndexStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    width,
    letterHeight,
    textStyle,
    color,
    background,
    markerSize,
    dotSize,
    bubbleSize,
    bubbleGap,
    bubbleColor,
    bubbleTextStyle,
    bubbleShadows,
    bubbleRadius,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsSectionIndexStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('width', width, defaultValue: null));
    properties.add(
      DoubleProperty('letterHeight', letterHeight, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('textStyle', textStyle, defaultValue: null),
    );
    properties.add(ColorProperty('color', color, defaultValue: null));
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(
      DoubleProperty('markerSize', markerSize, defaultValue: null),
    );
    properties.add(DoubleProperty('dotSize', dotSize, defaultValue: null));
    properties.add(
      DoubleProperty('bubbleSize', bubbleSize, defaultValue: null),
    );
    properties.add(DoubleProperty('bubbleGap', bubbleGap, defaultValue: null));
    properties.add(
      ColorProperty('bubbleColor', bubbleColor, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty(
        'bubbleTextStyle',
        bubbleTextStyle,
        defaultValue: null,
      ),
    );
    properties.add(
      DiagnosticsProperty('bubbleShadows', bubbleShadows, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('bubbleRadius', bubbleRadius, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsSectionIndex` in a subtree; see [DsSectionIndexTheme].
class DsSectionIndexThemeData
    extends DsComponentThemeData<DsSectionIndexThemeData> {
  /// Creates defaults.
  const DsSectionIndexThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsSectionIndexStyle? style;

  @override
  DsSectionIndexThemeData merge(DsSectionIndexThemeData? other) {
    if (other == null) return this;
    return DsSectionIndexThemeData(
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsSectionIndexThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsSectionIndexThemeData] to a subtree, merged over any outer one.
class DsSectionIndexTheme extends DsComponentTheme<DsSectionIndexThemeData> {
  /// Applies [data] to [child].
  const DsSectionIndexTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsSectionIndexThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsSectionIndexThemeData>(context) ??
      const DsSectionIndexThemeData();
}
