// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsCheckbox`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsCheckboxStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsCheckboxStyle with Diagnosticable {
  /// Creates a style.
  const DsCheckboxStyle({
    this.size,
    this.background,
    this.borderColor,
    this.borderWidth,
    this.borderRadius,
    this.markColor,
    this.markSize,
    this.shadows,
    this.focusShadows,
    this.labelStyle,
    this.descriptionStyle,
    this.textGap,
    this.gap,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
    this.error,
    this.disabled,
  });

  /// Box width and height.
  final double? size;

  /// Box fill.
  final Color? background;

  /// Inner outline of the box.
  final Color? borderColor;

  /// Width of the inner outline; 2 for errors.
  final double? borderWidth;

  /// Box corners.
  final BorderRadiusGeometry? borderRadius;

  /// Check or dash color.
  final Color? markColor;

  /// Check or dash size.
  final double? markSize;

  /// Extra shadows on the box.
  final List<DsShadow>? shadows;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Label text style, merged.
  final TextStyle? labelStyle;

  /// Description text style (under the label), merged.
  final TextStyle? descriptionStyle;

  /// Space between label and description.
  final double? textGap;

  /// Space between box and label.
  final double? gap;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsCheckboxStyle? focused;

  /// Laid over the base while hovered.
  final DsCheckboxStyle? hovered;

  /// Laid over the base while pressed.
  final DsCheckboxStyle? pressed;

  /// Laid over the base while selected.
  final DsCheckboxStyle? selected;

  /// Laid over the base while error.
  final DsCheckboxStyle? error;

  /// Laid over the base while disabled.
  final DsCheckboxStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsCheckboxStyle merge(DsCheckboxStyle? other) {
    if (other == null) return this;
    return DsCheckboxStyle(
      size: other.size ?? size,
      background: other.background ?? background,
      borderColor: other.borderColor ?? borderColor,
      borderWidth: other.borderWidth ?? borderWidth,
      borderRadius: other.borderRadius ?? borderRadius,
      markColor: other.markColor ?? markColor,
      markSize: other.markSize ?? markSize,
      shadows: other.shadows ?? shadows,
      focusShadows: other.focusShadows ?? focusShadows,
      labelStyle: labelStyle?.merge(other.labelStyle) ?? other.labelStyle,
      descriptionStyle:
          descriptionStyle?.merge(other.descriptionStyle) ??
          other.descriptionStyle,
      textGap: other.textGap ?? textGap,
      gap: other.gap ?? gap,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
      error: error == null ? other.error : error!.merge(other.error),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsCheckboxStyle get _base => DsCheckboxStyle(
    size: size,
    background: background,
    borderColor: borderColor,
    borderWidth: borderWidth,
    borderRadius: borderRadius,
    markColor: markColor,
    markSize: markSize,
    shadows: shadows,
    focusShadows: focusShadows,
    labelStyle: labelStyle,
    descriptionStyle: descriptionStyle,
    textGap: textGap,
    gap: gap,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsCheckboxStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    if (states.contains(WidgetState.error) && error != null) {
      s = s.merge(error!.resolve({...states}..remove(WidgetState.error)));
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsCheckboxStyle resolveLayers(
    Iterable<DsCheckboxStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsCheckboxStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    size,
    background,
    borderColor,
    borderWidth,
    borderRadius,
    markColor,
    markSize,
    shadows,
    focusShadows,
    labelStyle,
    descriptionStyle,
    textGap,
    gap,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
    error,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsCheckboxStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('size', size, defaultValue: null));
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(
      ColorProperty('borderColor', borderColor, defaultValue: null),
    );
    properties.add(
      DoubleProperty('borderWidth', borderWidth, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(ColorProperty('markColor', markColor, defaultValue: null));
    properties.add(DoubleProperty('markSize', markSize, defaultValue: null));
    properties.add(DiagnosticsProperty('shadows', shadows, defaultValue: null));
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('labelStyle', labelStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty(
        'descriptionStyle',
        descriptionStyle,
        defaultValue: null,
      ),
    );
    properties.add(DoubleProperty('textGap', textGap, defaultValue: null));
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('error', error, defaultValue: null));
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsCheckbox` in a subtree; see [DsCheckboxTheme].
class DsCheckboxThemeData extends DsComponentThemeData<DsCheckboxThemeData> {
  /// Creates defaults.
  const DsCheckboxThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsCheckboxStyle? style;

  @override
  DsCheckboxThemeData merge(DsCheckboxThemeData? other) {
    if (other == null) return this;
    return DsCheckboxThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsCheckboxThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsCheckboxThemeData] to a subtree, merged over any outer one.
class DsCheckboxTheme extends DsComponentTheme<DsCheckboxThemeData> {
  /// Applies [data] to [child].
  const DsCheckboxTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsCheckboxThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsCheckboxThemeData>(context) ??
      const DsCheckboxThemeData();
}
