// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';
import 'radio_style.dart';

/// The look of a `DsRadioCard`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsRadioCardStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsRadioCardStyle with Diagnosticable {
  /// Creates a style.
  const DsRadioCardStyle({
    this.padding,
    this.background,
    this.shadows,
    this.borderColor,
    this.borderWidth,
    this.borderRadius,
    this.labelStyle,
    this.descriptionStyle,
    this.textGap,
    this.contentGap,
    this.gap,
    this.showRadio,
    this.radioStyle,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
    this.error,
    this.disabled,
  });

  /// Inner padding.
  final EdgeInsetsGeometry? padding;

  /// Card fill.
  final Color? background;

  /// Card edge and lift.
  final List<DsShadow>? shadows;

  /// Inner outline over the edge; transparent for none.
  final Color? borderColor;

  /// Width of the inner outline; 2 for errors.
  final double? borderWidth;

  /// Card corners.
  final BorderRadiusGeometry? borderRadius;

  /// Label text style, merged.
  final TextStyle? labelStyle;

  /// Description text style, merged.
  final TextStyle? descriptionStyle;

  /// Space between label and description.
  final double? textGap;

  /// Space between the text and the extra content under it.
  final double? contentGap;

  /// Space between the radio circle and the text.
  final double? gap;

  /// Whether the card shows a radio circle before its text, so the selection does not rest on the fill alone (WCAG 1.4.1).
  final bool? showRadio;

  /// The radio circle, laid over the radio theme and resolved with the card states (focus draws its ring around the card instead).
  final DsRadioStyle? radioStyle;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsRadioCardStyle? focused;

  /// Laid over the base while hovered.
  final DsRadioCardStyle? hovered;

  /// Laid over the base while pressed.
  final DsRadioCardStyle? pressed;

  /// Laid over the base while selected.
  final DsRadioCardStyle? selected;

  /// Laid over the base while error.
  final DsRadioCardStyle? error;

  /// Laid over the base while disabled.
  final DsRadioCardStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsRadioCardStyle merge(DsRadioCardStyle? other) {
    if (other == null) return this;
    return DsRadioCardStyle(
      padding: other.padding ?? padding,
      background: other.background ?? background,
      shadows: other.shadows ?? shadows,
      borderColor: other.borderColor ?? borderColor,
      borderWidth: other.borderWidth ?? borderWidth,
      borderRadius: other.borderRadius ?? borderRadius,
      labelStyle: labelStyle?.merge(other.labelStyle) ?? other.labelStyle,
      descriptionStyle:
          descriptionStyle?.merge(other.descriptionStyle) ??
          other.descriptionStyle,
      textGap: other.textGap ?? textGap,
      contentGap: other.contentGap ?? contentGap,
      gap: other.gap ?? gap,
      showRadio: other.showRadio ?? showRadio,
      radioStyle: radioStyle?.merge(other.radioStyle) ?? other.radioStyle,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
      error: error == null ? other.error : error!.merge(other.error),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsRadioCardStyle get _base => DsRadioCardStyle(
    padding: padding,
    background: background,
    shadows: shadows,
    borderColor: borderColor,
    borderWidth: borderWidth,
    borderRadius: borderRadius,
    labelStyle: labelStyle,
    descriptionStyle: descriptionStyle,
    textGap: textGap,
    contentGap: contentGap,
    gap: gap,
    showRadio: showRadio,
    radioStyle: radioStyle,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsRadioCardStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    if (states.contains(WidgetState.error) && error != null) {
      s = s.merge(error!.resolve({...states}..remove(WidgetState.error)));
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsRadioCardStyle resolveLayers(
    Iterable<DsRadioCardStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsRadioCardStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    padding,
    background,
    shadows,
    borderColor,
    borderWidth,
    borderRadius,
    labelStyle,
    descriptionStyle,
    textGap,
    contentGap,
    gap,
    showRadio,
    radioStyle,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
    error,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsRadioCardStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(DiagnosticsProperty('shadows', shadows, defaultValue: null));
    properties.add(
      ColorProperty('borderColor', borderColor, defaultValue: null),
    );
    properties.add(
      DoubleProperty('borderWidth', borderWidth, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('labelStyle', labelStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty(
        'descriptionStyle',
        descriptionStyle,
        defaultValue: null,
      ),
    );
    properties.add(DoubleProperty('textGap', textGap, defaultValue: null));
    properties.add(
      DoubleProperty('contentGap', contentGap, defaultValue: null),
    );
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
    properties.add(
      DiagnosticsProperty('showRadio', showRadio, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('radioStyle', radioStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('error', error, defaultValue: null));
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsRadioCard` in a subtree; see [DsRadioCardTheme].
class DsRadioCardThemeData extends DsComponentThemeData<DsRadioCardThemeData> {
  /// Creates defaults.
  const DsRadioCardThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsRadioCardStyle? style;

  @override
  DsRadioCardThemeData merge(DsRadioCardThemeData? other) {
    if (other == null) return this;
    return DsRadioCardThemeData(
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsRadioCardThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsRadioCardThemeData] to a subtree, merged over any outer one.
class DsRadioCardTheme extends DsComponentTheme<DsRadioCardThemeData> {
  /// Applies [data] to [child].
  const DsRadioCardTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsRadioCardThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsRadioCardThemeData>(context) ??
      const DsRadioCardThemeData();
}
