// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsSwitch`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsSwitchStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsSwitchStyle with Diagnosticable {
  /// Creates a style.
  const DsSwitchStyle({
    this.width,
    this.height,
    this.inset,
    this.trackColor,
    this.trackShadows,
    this.knobColor,
    this.knobShadows,
    this.labelStyle,
    this.descriptionStyle,
    this.textGap,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
    this.error,
    this.disabled,
  });

  /// Track width.
  final double? width;

  /// Track height.
  final double? height;

  /// Space between the track edge and the knob.
  final double? inset;

  /// Track fill.
  final Color? trackColor;

  /// Track edge or inner shadow.
  final List<DsShadow>? trackShadows;

  /// Knob fill.
  final Color? knobColor;

  /// Knob shadow.
  final List<DsShadow>? knobShadows;

  /// Label text style; the color follows the state.
  final TextStyle? labelStyle;

  /// Description text style; the color follows the state.
  final TextStyle? descriptionStyle;

  /// Space between label and description.
  final double? textGap;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsSwitchStyle? focused;

  /// Laid over the base while hovered.
  final DsSwitchStyle? hovered;

  /// Laid over the base while pressed.
  final DsSwitchStyle? pressed;

  /// Laid over the base while selected.
  final DsSwitchStyle? selected;

  /// Laid over the base while error.
  final DsSwitchStyle? error;

  /// Laid over the base while disabled.
  final DsSwitchStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsSwitchStyle merge(DsSwitchStyle? other) {
    if (other == null) return this;
    return DsSwitchStyle(
      width: other.width ?? width,
      height: other.height ?? height,
      inset: other.inset ?? inset,
      trackColor: other.trackColor ?? trackColor,
      trackShadows: other.trackShadows ?? trackShadows,
      knobColor: other.knobColor ?? knobColor,
      knobShadows: other.knobShadows ?? knobShadows,
      labelStyle: labelStyle?.merge(other.labelStyle) ?? other.labelStyle,
      descriptionStyle:
          descriptionStyle?.merge(other.descriptionStyle) ??
          other.descriptionStyle,
      textGap: other.textGap ?? textGap,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
      error: error == null ? other.error : error!.merge(other.error),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsSwitchStyle get _base => DsSwitchStyle(
    width: width,
    height: height,
    inset: inset,
    trackColor: trackColor,
    trackShadows: trackShadows,
    knobColor: knobColor,
    knobShadows: knobShadows,
    labelStyle: labelStyle,
    descriptionStyle: descriptionStyle,
    textGap: textGap,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsSwitchStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    if (states.contains(WidgetState.error) && error != null) {
      s = s.merge(error!.resolve({...states}..remove(WidgetState.error)));
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsSwitchStyle resolveLayers(
    Iterable<DsSwitchStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsSwitchStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    width,
    height,
    inset,
    trackColor,
    trackShadows,
    knobColor,
    knobShadows,
    labelStyle,
    descriptionStyle,
    textGap,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
    error,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsSwitchStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('width', width, defaultValue: null));
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(DoubleProperty('inset', inset, defaultValue: null));
    properties.add(ColorProperty('trackColor', trackColor, defaultValue: null));
    properties.add(
      DiagnosticsProperty('trackShadows', trackShadows, defaultValue: null),
    );
    properties.add(ColorProperty('knobColor', knobColor, defaultValue: null));
    properties.add(
      DiagnosticsProperty('knobShadows', knobShadows, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('labelStyle', labelStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty(
        'descriptionStyle',
        descriptionStyle,
        defaultValue: null,
      ),
    );
    properties.add(DoubleProperty('textGap', textGap, defaultValue: null));
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('error', error, defaultValue: null));
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsSwitch` in a subtree; see [DsSwitchTheme].
class DsSwitchThemeData extends DsComponentThemeData<DsSwitchThemeData> {
  /// Creates defaults.
  const DsSwitchThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsSwitchStyle? style;

  @override
  DsSwitchThemeData merge(DsSwitchThemeData? other) {
    if (other == null) return this;
    return DsSwitchThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsSwitchThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsSwitchThemeData] to a subtree, merged over any outer one.
class DsSwitchTheme extends DsComponentTheme<DsSwitchThemeData> {
  /// Applies [data] to [child].
  const DsSwitchTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsSwitchThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsSwitchThemeData>(context) ??
      const DsSwitchThemeData();
}
