// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../text_field/text_field_style.dart';

/// The look of a `DsNumberField`: its text field, the unit, and the decrease and increase buttons. `hovered`, `pressed` and `disabled` style a button; `disabled` also one at a limit.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsNumberFieldStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsNumberFieldStyle with Diagnosticable {
  /// Creates a style.
  const DsNumberFieldStyle({
    this.fieldStyle,
    this.unitStyle,
    this.buttonWidth,
    this.buttonColor,
    this.foreground,
    this.iconSize,
    this.dividerColor,
    this.dividerWidth,
    this.cursor,
    this.hovered,
    this.pressed,
    this.disabled,
  });

  /// The text field, laid over its own defaults and theme: a narrower default width.
  final DsTextFieldStyle? fieldStyle;

  /// Unit and prefix text, merged; the color comes from the field (its placeholder color).
  final TextStyle? unitStyle;

  /// Drawn width of each button; never less than the minimum tap target.
  final double? buttonWidth;

  /// Button fill.
  final Color? buttonColor;

  /// Button icon color.
  final Color? foreground;

  /// Minus and plus icon size, scaled with the text.
  final double? iconSize;

  /// Hairline before and between the buttons.
  final Color? dividerColor;

  /// Width of the hairlines.
  final double? dividerWidth;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while hovered.
  final DsNumberFieldStyle? hovered;

  /// Laid over the base while pressed.
  final DsNumberFieldStyle? pressed;

  /// Laid over the base while disabled.
  final DsNumberFieldStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsNumberFieldStyle merge(DsNumberFieldStyle? other) {
    if (other == null) return this;
    return DsNumberFieldStyle(
      fieldStyle: fieldStyle?.merge(other.fieldStyle) ?? other.fieldStyle,
      unitStyle: unitStyle?.merge(other.unitStyle) ?? other.unitStyle,
      buttonWidth: other.buttonWidth ?? buttonWidth,
      buttonColor: other.buttonColor ?? buttonColor,
      foreground: other.foreground ?? foreground,
      iconSize: other.iconSize ?? iconSize,
      dividerColor: other.dividerColor ?? dividerColor,
      dividerWidth: other.dividerWidth ?? dividerWidth,
      cursor: other.cursor ?? cursor,
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsNumberFieldStyle get _base => DsNumberFieldStyle(
    fieldStyle: fieldStyle,
    unitStyle: unitStyle,
    buttonWidth: buttonWidth,
    buttonColor: buttonColor,
    foreground: foreground,
    iconSize: iconSize,
    dividerColor: dividerColor,
    dividerWidth: dividerWidth,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsNumberFieldStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsNumberFieldStyle resolveLayers(
    Iterable<DsNumberFieldStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsNumberFieldStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    fieldStyle,
    unitStyle,
    buttonWidth,
    buttonColor,
    foreground,
    iconSize,
    dividerColor,
    dividerWidth,
    cursor,
    hovered,
    pressed,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsNumberFieldStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(
      DiagnosticsProperty('fieldStyle', fieldStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('unitStyle', unitStyle, defaultValue: null),
    );
    properties.add(
      DoubleProperty('buttonWidth', buttonWidth, defaultValue: null),
    );
    properties.add(
      ColorProperty('buttonColor', buttonColor, defaultValue: null),
    );
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(
      ColorProperty('dividerColor', dividerColor, defaultValue: null),
    );
    properties.add(
      DoubleProperty('dividerWidth', dividerWidth, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsNumberField` in a subtree; see [DsNumberFieldTheme].
class DsNumberFieldThemeData
    extends DsComponentThemeData<DsNumberFieldThemeData> {
  /// Creates defaults.
  const DsNumberFieldThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsNumberFieldStyle? style;

  @override
  DsNumberFieldThemeData merge(DsNumberFieldThemeData? other) {
    if (other == null) return this;
    return DsNumberFieldThemeData(
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsNumberFieldThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsNumberFieldThemeData] to a subtree, merged over any outer one.
class DsNumberFieldTheme extends DsComponentTheme<DsNumberFieldThemeData> {
  /// Applies [data] to [child].
  const DsNumberFieldTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsNumberFieldThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsNumberFieldThemeData>(context) ??
      const DsNumberFieldThemeData();
}
