// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsListRow`.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsListRowStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsListRowStyle with Diagnosticable {
  /// Creates a style.
  const DsListRowStyle({
    this.height,
    this.padding,
    this.borderRadius,
    this.background,
    this.borderColor,
    this.foreground,
    this.iconColor,
    this.iconSize,
    this.titleStyle,
    this.detailStyle,
    this.maxLines,
    this.chevronColor,
    this.gap,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
    this.disabled,
  });

  /// Minimum row height.
  final double? height;

  /// Row padding.
  final EdgeInsetsGeometry? padding;

  /// Row corners (visible on hover and selection).
  final BorderRadiusGeometry? borderRadius;

  /// Row fill.
  final Color? background;

  /// Inner 1px outline, e.g. the edge a bright filled selection needs off a light card.
  final Color? borderColor;

  /// Title color.
  final Color? foreground;

  /// Leading icon color.
  final Color? iconColor;

  /// Leading icon size.
  final double? iconSize;

  /// Title style, merged.
  final TextStyle? titleStyle;

  /// Trailing detail style, merged.
  final TextStyle? detailStyle;

  /// Lines the title and the detail may each take before they ellipsize.
  final int? maxLines;

  /// Disclosure chevron color.
  final Color? chevronColor;

  /// Space between parts.
  final double? gap;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsListRowStyle? focused;

  /// Laid over the base while hovered.
  final DsListRowStyle? hovered;

  /// Laid over the base while pressed.
  final DsListRowStyle? pressed;

  /// Laid over the base while selected.
  final DsListRowStyle? selected;

  /// Laid over the base while disabled.
  final DsListRowStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsListRowStyle merge(DsListRowStyle? other) {
    if (other == null) return this;
    return DsListRowStyle(
      height: other.height ?? height,
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
      background: other.background ?? background,
      borderColor: other.borderColor ?? borderColor,
      foreground: other.foreground ?? foreground,
      iconColor: other.iconColor ?? iconColor,
      iconSize: other.iconSize ?? iconSize,
      titleStyle: titleStyle?.merge(other.titleStyle) ?? other.titleStyle,
      detailStyle: detailStyle?.merge(other.detailStyle) ?? other.detailStyle,
      maxLines: other.maxLines ?? maxLines,
      chevronColor: other.chevronColor ?? chevronColor,
      gap: other.gap ?? gap,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsListRowStyle get _base => DsListRowStyle(
    height: height,
    padding: padding,
    borderRadius: borderRadius,
    background: background,
    borderColor: borderColor,
    foreground: foreground,
    iconColor: iconColor,
    iconSize: iconSize,
    titleStyle: titleStyle,
    detailStyle: detailStyle,
    maxLines: maxLines,
    chevronColor: chevronColor,
    gap: gap,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsListRowStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsListRowStyle resolveLayers(
    Iterable<DsListRowStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsListRowStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    height,
    padding,
    borderRadius,
    background,
    borderColor,
    foreground,
    iconColor,
    iconSize,
    titleStyle,
    detailStyle,
    maxLines,
    chevronColor,
    gap,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsListRowStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(
      ColorProperty('borderColor', borderColor, defaultValue: null),
    );
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(ColorProperty('iconColor', iconColor, defaultValue: null));
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(
      DiagnosticsProperty('titleStyle', titleStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('detailStyle', detailStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('maxLines', maxLines, defaultValue: null),
    );
    properties.add(
      ColorProperty('chevronColor', chevronColor, defaultValue: null),
    );
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsListRow` in a subtree; see [DsListRowTheme].
class DsListRowThemeData extends DsComponentThemeData<DsListRowThemeData> {
  /// Creates defaults.
  const DsListRowThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsListRowStyle? style;

  @override
  DsListRowThemeData merge(DsListRowThemeData? other) {
    if (other == null) return this;
    return DsListRowThemeData(style: style?.merge(other.style) ?? other.style);
  }

  @override
  bool operator ==(Object other) =>
      other is DsListRowThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsListRowThemeData] to a subtree, merged over any outer one.
class DsListRowTheme extends DsComponentTheme<DsListRowThemeData> {
  /// Applies [data] to [child].
  const DsListRowTheme({super.key, required super.data, required super.child});

  /// The merged defaults for [context]; empty when there are none.
  static DsListRowThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsListRowThemeData>(context) ??
      const DsListRowThemeData();
}
