// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsListSection`: a card holding list rows.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
@immutable
class DsListSectionStyle with Diagnosticable {
  /// Creates a style.
  const DsListSectionStyle({
    this.background,
    this.shadows,
    this.borderRadius,
    this.padding,
    this.headerStyle,
    this.headerPadding,
    this.dividerColor,
    this.dividerEndIndent,
  });

  /// Card fill.
  final Color? background;

  /// Card edge.
  final List<DsShadow>? shadows;

  /// Card corners.
  final BorderRadiusGeometry? borderRadius;

  /// Inset between the card edge and the rows.
  final EdgeInsetsGeometry? padding;

  /// Section header style, merged.
  final TextStyle? headerStyle;

  /// Padding around the header.
  final EdgeInsetsGeometry? headerPadding;

  /// Line between rows.
  final Color? dividerColor;

  /// Space between the line end and the card edge.
  final double? dividerEndIndent;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsListSectionStyle merge(DsListSectionStyle? other) {
    if (other == null) return this;
    return DsListSectionStyle(
      background: other.background ?? background,
      shadows: other.shadows ?? shadows,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      headerStyle: headerStyle?.merge(other.headerStyle) ?? other.headerStyle,
      headerPadding: other.headerPadding ?? headerPadding,
      dividerColor: other.dividerColor ?? dividerColor,
      dividerEndIndent: other.dividerEndIndent ?? dividerEndIndent,
    );
  }

  /// This style; it has no state styles.
  DsListSectionStyle resolve(Set<WidgetState> states) => this;

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsListSectionStyle resolveLayers(
    Iterable<DsListSectionStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsListSectionStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    background,
    shadows,
    borderRadius,
    padding,
    headerStyle,
    headerPadding,
    dividerColor,
    dividerEndIndent,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsListSectionStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(ColorProperty('background', background, defaultValue: null));
    properties.add(DiagnosticsProperty('shadows', shadows, defaultValue: null));
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('padding', padding, defaultValue: null));
    properties.add(
      DiagnosticsProperty('headerStyle', headerStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('headerPadding', headerPadding, defaultValue: null),
    );
    properties.add(
      ColorProperty('dividerColor', dividerColor, defaultValue: null),
    );
    properties.add(
      DoubleProperty('dividerEndIndent', dividerEndIndent, defaultValue: null),
    );
  }
}

/// Defaults for every `DsListSection` in a subtree; see [DsListSectionTheme].
class DsListSectionThemeData
    extends DsComponentThemeData<DsListSectionThemeData> {
  /// Creates defaults.
  const DsListSectionThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsListSectionStyle? style;

  @override
  DsListSectionThemeData merge(DsListSectionThemeData? other) {
    if (other == null) return this;
    return DsListSectionThemeData(
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsListSectionThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsListSectionThemeData] to a subtree, merged over any outer one.
class DsListSectionTheme extends DsComponentTheme<DsListSectionThemeData> {
  /// Applies [data] to [child].
  const DsListSectionTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsListSectionThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsListSectionThemeData>(context) ??
      const DsListSectionThemeData();
}
