// GENERATED by tool/gen_styles.py. Do not edit by hand.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../foundation/component_theme.dart';
import '../../painting/shadow.dart';

/// The look of a `DsSegmentedControl`. Channel and thumb fields are read unresolved; item fields resolve per segment.
///
/// Every field is optional; null means "keep the layer below". To remove
/// something, pass an empty value (`const []`, a transparent color).
///
/// State styles lay over the base like CSS blocks. Interaction states
/// (focused, hovered, pressed) apply first; structural ones (selected,
/// error, disabled) apply after and resolve their own nested states, so
/// `selected: DsSegmentedControlStyle(hovered: …)` is the selected-and-hovered look.
@immutable
class DsSegmentedControlStyle with Diagnosticable {
  /// Creates a style.
  const DsSegmentedControlStyle({
    this.height,
    this.inset,
    this.gap,
    this.trackColor,
    this.trackShadows,
    this.borderRadius,
    this.thumbColor,
    this.thumbShadows,
    this.thumbRadius,
    this.foreground,
    this.textStyle,
    this.itemPadding,
    this.iconSize,
    this.focusShadows,
    this.cursor,
    this.focused,
    this.hovered,
    this.pressed,
    this.selected,
    this.disabled,
  });

  /// Segment height.
  final double? height;

  /// Space between channel edge and segments.
  final double? inset;

  /// Space between segments.
  final double? gap;

  /// Channel fill.
  final Color? trackColor;

  /// Channel edge.
  final List<DsShadow>? trackShadows;

  /// Channel corners. When no layer sets them, the channel is rounded as a control of its height (`height` plus `inset` on each side, `DsRadii.controlCorners`), so a style that changes only the height or the inset keeps them in proportion.
  final BorderRadiusGeometry? borderRadius;

  /// Sliding indicator fill.
  final Color? thumbColor;

  /// Sliding indicator shadow.
  final List<DsShadow>? thumbShadows;

  /// Indicator and segment corners. When no layer sets them, concentric with the channel corners (`DsRadii.nestedCorners` by `inset`).
  final BorderRadiusGeometry? thumbRadius;

  /// Segment label and icon color.
  final Color? foreground;

  /// Segment label style, merged.
  final TextStyle? textStyle;

  /// Space around each label.
  final EdgeInsetsGeometry? itemPadding;

  /// Icon size.
  final double? iconSize;

  /// Added while focused from the keyboard: the focus ring.
  final List<DsShadow>? focusShadows;

  /// Mouse cursor.
  final MouseCursor? cursor;

  /// Laid over the base while focused.
  final DsSegmentedControlStyle? focused;

  /// Laid over the base while hovered.
  final DsSegmentedControlStyle? hovered;

  /// Laid over the base while pressed.
  final DsSegmentedControlStyle? pressed;

  /// Laid over the base while selected.
  final DsSegmentedControlStyle? selected;

  /// Laid over the base while disabled.
  final DsSegmentedControlStyle? disabled;

  /// Lays [other] over this: its set fields win; state styles merge.
  DsSegmentedControlStyle merge(DsSegmentedControlStyle? other) {
    if (other == null) return this;
    return DsSegmentedControlStyle(
      height: other.height ?? height,
      inset: other.inset ?? inset,
      gap: other.gap ?? gap,
      trackColor: other.trackColor ?? trackColor,
      trackShadows: other.trackShadows ?? trackShadows,
      borderRadius: other.borderRadius ?? borderRadius,
      thumbColor: other.thumbColor ?? thumbColor,
      thumbShadows: other.thumbShadows ?? thumbShadows,
      thumbRadius: other.thumbRadius ?? thumbRadius,
      foreground: other.foreground ?? foreground,
      textStyle: textStyle?.merge(other.textStyle) ?? other.textStyle,
      itemPadding: other.itemPadding ?? itemPadding,
      iconSize: other.iconSize ?? iconSize,
      focusShadows: other.focusShadows ?? focusShadows,
      cursor: other.cursor ?? cursor,
      focused: focused == null ? other.focused : focused!.merge(other.focused),
      hovered: hovered == null ? other.hovered : hovered!.merge(other.hovered),
      pressed: pressed == null ? other.pressed : pressed!.merge(other.pressed),
      selected: selected == null
          ? other.selected
          : selected!.merge(other.selected),
      disabled: disabled == null
          ? other.disabled
          : disabled!.merge(other.disabled),
    );
  }

  DsSegmentedControlStyle get _base => DsSegmentedControlStyle(
    height: height,
    inset: inset,
    gap: gap,
    trackColor: trackColor,
    trackShadows: trackShadows,
    borderRadius: borderRadius,
    thumbColor: thumbColor,
    thumbShadows: thumbShadows,
    thumbRadius: thumbRadius,
    foreground: foreground,
    textStyle: textStyle,
    itemPadding: itemPadding,
    iconSize: iconSize,
    focusShadows: focusShadows,
    cursor: cursor,
  );

  /// This style flattened for [states] (see the class docs for the order).
  DsSegmentedControlStyle resolve(Set<WidgetState> states) {
    var s = _base;
    if (states.contains(WidgetState.focused) && focused != null) {
      s = s.merge(focused!._base);
    }
    if (states.contains(WidgetState.hovered) && hovered != null) {
      s = s.merge(hovered!._base);
    }
    if (states.contains(WidgetState.pressed) && pressed != null) {
      s = s.merge(pressed!._base);
    }
    if (states.contains(WidgetState.selected) && selected != null) {
      s = s.merge(selected!.resolve({...states}..remove(WidgetState.selected)));
    }
    if (states.contains(WidgetState.disabled) && disabled != null) {
      s = s.merge(disabled!.resolve({...states}..remove(WidgetState.disabled)));
    }
    return s;
  }

  /// Resolves each layer for [states] and lays them over each other,
  /// weakest first.
  static DsSegmentedControlStyle resolveLayers(
    Iterable<DsSegmentedControlStyle?> layers,
    Set<WidgetState> states,
  ) {
    var result = const DsSegmentedControlStyle();
    for (final layer in layers) {
      if (layer != null) result = result.merge(layer.resolve(states));
    }
    return result;
  }

  List<Object?> get _fields => [
    height,
    inset,
    gap,
    trackColor,
    trackShadows,
    borderRadius,
    thumbColor,
    thumbShadows,
    thumbRadius,
    foreground,
    textStyle,
    itemPadding,
    iconSize,
    focusShadows,
    cursor,
    focused,
    hovered,
    pressed,
    selected,
    disabled,
  ];

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! DsSegmentedControlStyle) return false;
    final a = _fields, b = other._fields;
    for (var i = 0; i < a.length; i++) {
      final x = a[i], y = b[i];
      if (x is List && y is List ? !listEquals(x, y) : x != y) return false;
    }
    return true;
  }

  @override
  int get hashCode =>
      Object.hashAll(_fields.map((f) => f is List ? Object.hashAll(f) : f));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('height', height, defaultValue: null));
    properties.add(DoubleProperty('inset', inset, defaultValue: null));
    properties.add(DoubleProperty('gap', gap, defaultValue: null));
    properties.add(ColorProperty('trackColor', trackColor, defaultValue: null));
    properties.add(
      DiagnosticsProperty('trackShadows', trackShadows, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('borderRadius', borderRadius, defaultValue: null),
    );
    properties.add(ColorProperty('thumbColor', thumbColor, defaultValue: null));
    properties.add(
      DiagnosticsProperty('thumbShadows', thumbShadows, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('thumbRadius', thumbRadius, defaultValue: null),
    );
    properties.add(ColorProperty('foreground', foreground, defaultValue: null));
    properties.add(
      DiagnosticsProperty('textStyle', textStyle, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('itemPadding', itemPadding, defaultValue: null),
    );
    properties.add(DoubleProperty('iconSize', iconSize, defaultValue: null));
    properties.add(
      DiagnosticsProperty('focusShadows', focusShadows, defaultValue: null),
    );
    properties.add(DiagnosticsProperty('cursor', cursor, defaultValue: null));
    properties.add(DiagnosticsProperty('focused', focused, defaultValue: null));
    properties.add(DiagnosticsProperty('hovered', hovered, defaultValue: null));
    properties.add(DiagnosticsProperty('pressed', pressed, defaultValue: null));
    properties.add(
      DiagnosticsProperty('selected', selected, defaultValue: null),
    );
    properties.add(
      DiagnosticsProperty('disabled', disabled, defaultValue: null),
    );
  }
}

/// Defaults for every `DsSegmentedControl` in a subtree; see [DsSegmentedControlTheme].
class DsSegmentedControlThemeData
    extends DsComponentThemeData<DsSegmentedControlThemeData> {
  /// Creates defaults.
  const DsSegmentedControlThemeData({this.style});

  /// Laid over Desen's defaults.
  final DsSegmentedControlStyle? style;

  @override
  DsSegmentedControlThemeData merge(DsSegmentedControlThemeData? other) {
    if (other == null) return this;
    return DsSegmentedControlThemeData(
      style: style?.merge(other.style) ?? other.style,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DsSegmentedControlThemeData && other.style == style;

  @override
  int get hashCode => style.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('style', style, defaultValue: null));
  }
}

/// Applies [DsSegmentedControlThemeData] to a subtree, merged over any outer one.
class DsSegmentedControlTheme
    extends DsComponentTheme<DsSegmentedControlThemeData> {
  /// Applies [data] to [child].
  const DsSegmentedControlTheme({
    super.key,
    required super.data,
    required super.child,
  });

  /// The merged defaults for [context]; empty when there are none.
  static DsSegmentedControlThemeData of(BuildContext context) =>
      DsComponentTheme.maybeOf<DsSegmentedControlThemeData>(context) ??
      const DsSegmentedControlThemeData();
}
